### PR TITLE
docs: add_scan2html_to_trivy_ecosystem

### PR DESCRIPTION
**Pull request by fatihtokus**
## Description
I have created this as per our discussion with @knqyf263 and @DmitriyLewen on https://github.com/aquasecurity/trivy/discussions/5388

### CODE REVIEW

**Comment by itaysk** [comment]
I thought about it a still don't have a good idea. My best suggestion would to rename "security management" to "miscellaneous" and add this PR to the page. when the misc list grows big enough we can split it based on the entries that we see there.

**Comment by fatihtokus** [comment]
I have applied @itaysk 's suggestion, please review @knqyf263.

**Review by knqyf263 — APPROVED** [review]

**Comment by AnaisUrlichs** [comment]
What about renaming "Security Management" into "Report Management" or just "Reporting", same as the section on output formats in the docs: https://aquasecurity.github.io/trivy/v0.48/docs/configuration/reporting/
Thoughts?

**Comment by AnaisUrlichs** [comment]
We also need to update the new file name here: https://github.com/aquasecurity/trivy/blob/ae134a9b3884c5fedaad1400863374e2c8c6897e/mkdocs.yml#L179

**Comment by fatihtokus** [comment]
> We also need to update the new file name here:
> 
> https://github.com/aquasecurity/trivy/blob/ae134a9b3884c5fedaad1400863374e2c8c6897e/mkdocs.yml#L179

I like the suggestion of 'Reporting' and I am happy to update mkdocs.yml as well. Wdyt guys, @itaysk , @knqyf263 ?

**Comment by knqyf263** [comment]
I don't have a strong opinion on the category. I'd defer to @itaysk.

**Comment by itaysk** [comment]
sounds good to me :)

**Comment by fatihtokus** [comment]
Created the new PR

**Pull request merged**
