### PR TITLE
Create sonarqube.tpl

### PR DESCRIPTION
**Pull request by eoraita**
Trivy SonarQube report template

## Description
Template used to gererante a report that you can push to sonarQube

### CODE REVIEW

**Comment by afdesk** [comment]
it would be great to have integration tests for this template, isn't it?

**Comment by krol3** [comment]
@eoraita  Nice feature!  @afdesk  how can we test this? maybe we could add some documentation about how to use this template.

**Comment by afdesk** [comment]
> how can we test this?

@krol3 i meant that we could add some golden files for this templates. 
`Trviy` already has them for ASFF, GitLab, html, json etc.

**Comment by knqyf263** [comment]
There is a nice plugin. I hope the plugin helps.
https://github.com/aquasecurity/trivy/pull/3347

**Pull request closed without merging**
