### PR TITLE
docs: add note about temporary podman socket

### PR DESCRIPTION
**Pull request by Ferenc-**
## Related issues
- Close #XXX

## Related PRs
- [ ] #XXX
- [ ] #YYY

Remove this section if you don't have related PRs.

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [x] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Review by knqyf263 — COMMENTED** [review]
I think this way should be located after the normal way here.
https://github.com/aquasecurity/trivy/blob/62d73421cfdb50d8301f988420ab4b3bcb2b0aef/docs/docs/target/container_image.md?plain=1#L303

**Comment by Ferenc-** [comment]
> I think this way should be located after the normal way here.

@knqyf263 Done.

**Review by knqyf263 — APPROVED** [review]
Thanks

**Comment by DmitriyLewen** [comment]
@knqyf263 Is https://github.com/aquasecurity/trivy/pull/7921/commits/98506b8de6aaf697e6e47eb9f43f89cec4159c86 and https://github.com/aquasecurity/trivy/pull/7921/commits/98506b8de6aaf697e6e47eb9f43f89cec4159c86 expected here?

**Comment by knqyf263** [comment]
oh... mistake...

**Comment by knqyf263** [comment]
My main branch was broken. Thanks.

**Pull request merged**
