### PR TITLE
feat(report): add secrets template for codequality report

### PR DESCRIPTION
**Pull request by natefive**
## Description

Adds templating for secrets to the gitlab code quality report. After adding a private key to a repository and scanning, the pipeline's code quality report will include the following JSON

```
 {
    "type": "issue",
    "check_name": "container_scanning",
    "categories": [
      "Security"
    ],
    "description": "Secret - private-key - Asymmetric Private Key",
    "fingerprint": "eaa88a2beb47fe5efa45979013ff09c01a434912",
    "content": "Asymmetric Private Key",
    "severity": "major",
    "location": {
      "path": "key",
      "lines": {
        "begin": 1
      }
    }
  }
```
and the pipeline's code quality UI will include `Major - Secret - private-key - Asymmetric Private Key`, like below:
Screenshot from 2022-07-20 10-57-58

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)

- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by knqyf263** [comment]
@DmitriyLewen Could you test it please?

**Comment by DmitriyLewen** [comment]
Looks good! @natefive can you add description and example for secret to the PR description?

**Comment by DmitriyLewen** [comment]
@natefive Thanks a lot for your work!
@knqyf263 i think we can merge this PR.

**Comment by natefive** [comment]
@knqyf263  we good to merge?

**Review by knqyf263 — APPROVED** [review]

**Comment by knqyf263** [comment]
Thanks

**Pull request merged**
