### PR TITLE
fix(sbom): fix incompliant license format for spdx

### LINKED ISSUE #3267: Trivy is not generating compliant SPDX JSON
## Description

The generated SPDX JSON file is not compliant with SPDX format. There are two issues why the output file does not pass the [SPDX validator tool](https://tools.spdx.org/app/validate/):
- The `licenseConcluded` and `licenseDeclared` is a comma separated list of licenses instead of supporting the [official operators](https://github.com/spdx/Spdx-Java-Library/blob/cd1b91df7087c7167edafbf3413ead8ff88f552c/src/main/java/org/spdx/library/model/license/LicenseExpressionParser.java#L57).
- There are licenses that are not part of the [SPDX identifiers](https://spdx.org/licenses/). E.g. `GPL-3+ with Autoconf exception` that it should be `GPL-3.0-with-autoconf-exception`.

## What did you expect to happen?

The output of a SBOM in SPDX JSON format should be compliant with the format and pass the [SPDX validator tool](https://tools.spdx.org/app/validate/). The same also happen with SPDX key-value format.

## What happened instead?

The SPDX Json format is not compliant with SPDX. Other tools like `syft` report the same licenses but in a compliant format, using `AND` for concatenating the licenses.

## Output of `trivy -v`:

```
Version: 0.35.0
Vulnerability DB:
  Version: 2
  UpdatedAt: 2022-12-05 06:07:28.002545547 +0000 UTC
  NextUpdate: 2022-12-05 12:07:28.002545147 +0000 UTC
  DownloadedAt: 2022-12-05 10:38:15.116911974 +0000 UTC
```

## Additional details (base image name, container registry info...):

Tested with Dockerhub Debian image E.g. `./trivy -q i --format spdx-json debian:latest`

### PR DESCRIPTION
**Pull request by masahiro331**
## Description

A licence parser has been added to support the SPDX licence format.
It is only used within the SPDX package so as not to affect the normalisation of existing licences.

SPDX license specification.
https://spdx.github.io/spdx-spec/v2.3/SPDX-license-expressions/

## Related issues
- Close #3267 
- Close https://github.com/aquasecurity/trivy/issues/2249

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by sentenz** [comment]
When will this merger be completed?

**Comment by beltran-rubo** [comment]
Any estimated date when this would be merged?

**Comment by masahiro331** [comment]
> Any estimated date when this would be merged?

Refactoring. Please wait a little longer.

**Comment by tokcum** [comment]
I'm also looking forward to get this merged and released.

**Comment by namandf** [comment]
Looking forward to this change. The spdx report currently seems to be invalid according to https://tools.spdx.org/app/validate/

**Comment by itaysk** [comment]
added to the description that this will also close https://github.com/aquasecurity/trivy/issues/2249

**Comment by MarioSMC** [comment]
Thanks for the great fix. When will the review be completed?

**Review by knqyf263 — APPROVED** [review]

**Pull request merged**
