### PR TITLE
fix(terraform): add aws_region name to presets

### PR DESCRIPTION
**Pull request by albertodonato**

### CODE REVIEW

**Review by nikpivkin — APPROVED** [review]

**Comment by nikpivkin** [comment]
@simar7 There are many resources for which values are predefined. How about adding support for a file where users can specify values for such resources/data blocks?

**Comment by nikpivkin** [comment]
@albertodonato Can you fix the linter's issues?

**Comment by albertodonato** [comment]
@nikpivkin should be good now

**Review by simar7 — APPROVED** [review]

**Comment by simar7** [comment]
> @simar7 There are many resources for which values are predefined. How about adding support for a file where users can specify values for such resources/data blocks?

Let's start by documenting this behavior first as I think it also doesn't exist. After that let's see if adding support for users to provide such values makes sense.

**Pull request merged**
