### PR TITLE
fix(java): Return error when trying to find a remote pom to avoid segfault

### PR DESCRIPTION
**Pull request by coheigea**
On updating from 0.52.x to 0.54.0, Trivy is segfaulting when scanning a maven filesystem due to the changes in https://github.com/aquasecurity/trivy/commit/1f8fca1fc77b989bb4e3ba820b297464dbdd825f

"Nil" is returned for the error in remoteRepoRequest, and so in fetchPOMFromRemoteRepository it proceeds to client.Do with a null "req".

The fix just returns the error in remoteRepoRequest and so it's handled properly by the calling functions.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x69868fb]

goroutine 41 [running]:
net/http.(*Client).do(0xc000c76580?, 0x0)
	/opt/hostedtoolcache/go/1.22.5/x64/src/net/http/client.go:599 +0xbb
net/http.(*Client).Do(...)
	/opt/hostedtoolcache/go/1.22.5/x64/src/net/http/client.go:590
github.com/aquasecurity/trivy/pkg/dependency/parser/java/pom.(*Parser).fetchPOMFromRemoteRepository(0xc000c76580, {0xc002fc00e0?, 0xc002e7bd18?}, {0xc0010099e0?, 0xaff9300?, 0xc001e52070?})
	/home/runner/work/trivy/trivy/pkg/dependency/parser/java/pom/parse.go:746 +0x85
github.com/aquasecurity/trivy/pkg/dependency/parser/java/pom.(*Parser).fetchPOMFromRemoteRepositories(0xc000c76580, {0xc0010098c0, 0x6, 0x2?}, 0x0)
	/home/runner/work/trivy/trivy/pkg/dependency/parser/java/pom/parse.go:669 +0x291
```

### CODE REVIEW

**Comment by coheigea** [comment]
FAO @DmitriyLewen

**Review by DmitriyLewen — COMMENTED** [review]
Hello @coheigea 
Thanks for fast fix.

I'm worried that we'll stop checking out repos instead of moving on to checking out the next repo.

I refactor a bit. Can you take a look?

**Review by knqyf263 — APPROVED** [review]

**Comment by DmitriyLewen** [comment]
@aqua-bot backport release/v0.54

**Comment by coheigea** [comment]
LGTM thanks! Any change of a fix in 0.54.1 as it's a regression?

**Comment by DmitriyLewen** [comment]
We are preparing `v0.54.1` with this change.

**Comment by knqyf263** [comment]
It's out.
https://github.com/aquasecurity/trivy/releases/tag/v0.54.1

**Pull request merged**
