### PR TITLE
Add CSV template

### PR DESCRIPTION
**Pull request by macedogm**
This is a proposal for https://github.com/aquasecurity/trivy/issues/1201 and follow ideas from https://github.com/aquasecurity/trivy/pull/919.
Please let me know if I should write a test for this template. Any feedback is appreciated.

### CODE REVIEW

**Review by knqyf263 — COMMENTED** [review]
Can we have a test here? The golden file can be under `testdata`.
https://github.com/aquasecurity/trivy/blob/main/pkg/report/template_test.go

**Comment by macedogm** [comment]
@knqyf263 I added the test case. Can you please have another look in this PR?

**Comment by knqyf263** [comment]
@afdesk Could you review this PR?

**Comment by macedogm** [comment]
After some tests that I did, I realised that I was not properly double-quoting strings according to [RFC4180](https://www.rfc-editor.org/rfc/rfc4180.html).
The template is more robust now, but it might also be a bit too complex. I appreciate any feedback about its usefulness and complexity.

**Comment by afdesk** [comment]
@macedogm thanks for your work and your time!
I've tested this PR, and it looks good!

I did next steps:
1. build `trivy` for this PR and run: 
```
./trivy i --format template --template "@contrib/csv.tpl" -o r.csv nginx:latest
```
2. check the csv result file (`r.csv`) on two validators: [csvlint.io](https://csvlint.io) and [www.toolkitbay.com](https://www.toolkitbay.com/): the both checks told that the result is valid.
[validation results on csvlint](https://csvlint.io/validation/61449a5862393a0004000032)

**Comment by macedogm** [comment]
Hi @afdesk 👋🏻 
Is there anything else that I need to do in this PR or does it looks good?

**Review by afdesk — APPROVED** [review]

**Comment by afdesk** [comment]
@macedogm I'm so sorry for waiting.
I retested this PR, and it looks good.

@knqyf263 what do you think?

**Comment by afdesk** [comment]
there is one my personal moment. 
if I want to open `.csv` file in Microsoft Excel 2010, the separator should be a semicolon.
but I'm not sure that it matters in this case

**Comment by afdesk** [comment]
@macedogm could you pull the `main` branch here?

**Comment by macedogm** [comment]
@afdesk thanks for you reply. Sure, I'll rebase and switch the separator from comma to semicolon. Semicolon is a valid separator and should work with all editors/parsers. 👍🏻

As a side note, I also opened this PR https://github.com/aquasecurity/fanal/pull/253 quite some time ago. Not sure if you can also review it or not. I believe that it's an interesting feature to add.

**Comment by afdesk** [comment]
@macedogm I'm not sure that we need to change the separator from comma to semicolon.

**Comment by macedogm** [comment]
@afdesk okay, then in this case I believe that we are good to go (I just pulled the `main`).

**Comment by macedogm** [comment]
@knqyf263 Can you please have a look in this PR and let me know your thoughts?

**Comment by sc-sd** [comment]
Looks like CLA bot has errored. Seems to think "Macedogm" & "Guilherme Macedo" are two different contributors when in fact they are the same user.

**Comment by aasyria** [comment]
Anything new on this Branch ?

**Comment by macedogm** [comment]
If there is still interest in adding this PR with CSV template support, then I can update it.

**Comment by macedogm** [comment]
@knqyf263 

> We're sorry to be late.

No worries.

> Looks like it is hard for us to maintain the template. Can we rewrite it in Go?

Yes. Is there any guidance that you would like to provide in advance, please?
Otherwise, I'll update the PR when I'm done.

**Comment by knqyf263** [comment]
I just want you to use `encoding/csv`.
https://pkg.go.dev/encoding/csv

You can just add a new writer in `pkg/report` like sarif.
https://github.com/aquasecurity/trivy/blob/main/pkg/report/sarif.go

**Comment by aasyria** [comment]
anythin new hier ?

**Comment by macedogm** [comment]
@xikunyu and @aasyria let me work on this during the weekend and submit a new PR.

**Comment by xikunyu** [comment]
@macedogm Thank you for your reply. I'm very looking forward to it.

**Comment by xikunyu** [comment]
@macedogm Hi, are there any updates?

**Pull request closed without merging**
