### PR TITLE
fix: Updated twitter icon

### PR DESCRIPTION
**Pull request by sarthak-kumar-shailendra**
## Description
The Twitter logo has been changed and hasn't been updated on the site. [Fixes #7771] 
After changes
Screenshot 2024-10-20 at 10 26 35 PM

## Related issues
- Close #7771 

## Related PRs
- [ ] #XXX
- [ ] #YYY

Remove this section if you don't have related PRs.

## Checklist
- [ ] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [ ] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by sarthak-kumar-shailendra** [comment]
@knqyf263 Please review

**Comment by knqyf263** [comment]
The document is broken.
https://github.com/aquasecurity/trivy/actions/runs/11428059837/job/31805397696?pr=7772

**Comment by sarthak-kumar-shailendra** [comment]
It was failing because of the old version of mkdocs-material.

**Comment by sarthak-kumar-shailendra** [comment]
> The document is broken.
> https://github.com/aquasecurity/trivy/actions/runs/11428059837/job/31805397696?pr=7772

It's been fixed now. @knqyf263

**Review by knqyf263 — COMMENTED** [review]
Thanks for fixing.
I think it's better to use the same version as the one in requirements.txt. here. I know there is a discrepancy now, though.
https://github.com/aquasecurity/trivy/blob/e872ec006c0745a5a142728af0096c6d6bb9ddf3/docs/build/Dockerfile#L1

**Comment by itaysk** [comment]
this might conflict with the changes in #7884 so perhaps it's better to wait and rebase

**Review by knqyf263 — APPROVED** [review]

**Pull request merged**
