### PR TITLE
ci: Add code coverage

### PR DESCRIPTION
**Pull request by simar7**
This adds code coverage to each PR we create.

Addresses: https://github.com/aquasecurity/trivy/issues/563

Signed-off-by: Simarpreet Singh <simar@linux.com>

### CODE REVIEW

**Comment by knqyf263** [comment]
Thanks! Does Codedev affect the test result? For example, it fails the test if the coverage is reduced. It's OK If it's not the case. In my experience, the coverage is useful, but it doesn't need to affect the test result.

**Comment by simar7** [comment]
> Thanks! Does Codecov affect the test result? For example, it fails the test if the coverage is reduced. It's OK If it's not the case. In my experience, the coverage is useful, but it doesn't need to affect the test result.

We can run it in informational mode where the PR is not gated (failed) if the coverage is lower than what it was before. See more https://docs.codecov.io/docs/commit-status#branches

I've changed it to behave like that now. Thoughts?

**Comment by lizrice** [comment]
Would it make sense to run codecov over other repos e.g. final?

**Comment by knqyf263** [comment]
Yes, we should add codecov in fanal and trivy-db as well.

**Pull request merged**
