### PR TITLE
feat: add gitlab codequality template

### LINKED ISSUE #894: Add gitlab codequality template
We are using gitlab-ci but do not have the license to support the `container scanning` report.  Initially we explored the `junit` report format but did this shows as a series of failed tests.  For other projects (linting) we are using the codequality report which shows the found items with a severity and can perform a diff showing new and fixed items.

https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html#code-quality-widget
See the speed run around T+3:10 for an example view in a merge request.
Screen shot: https://gitlab.com/gitlab-org/gitlab/-/issues/9014#note_525289446

### PR DESCRIPTION
**Pull request by bmagistro**
Fixes #894 

The PR here adds a template capable of formatting the output in a gitlab codequality compatible report format.

From a documentation perspective, gitlab only supports a single codequality report.  There is an open feature request to support multiple reports: https://gitlab.com/gitlab-org/gitlab/-/issues/9014.  In the interim the suggestion is to merge all of the reports using `jq`.  This is discussed further in the feature request.

The severity mapping to code quality levels has some room for interpretation but this seemed like a reasonable starting point.

The description is meant to be a simple one liner, using the CVE ID combined with the title seemed like a reasonable starting point.

The content field supports markdown and can include links, I thought of trying to include the link to the Mitre CVE DB but wasn't sure of an easy way to pull out just that link.  This was purely to reduce the number of links that would be listed.

The location field was meant to map to a file in the repository and is required but since these are not issues in a file per se, I thought using this to hold the package and version seemed like a reasonable option.

### CODE REVIEW

**Comment by rahul2393** [comment]
looks good to me @bmagistro can you add an integration test for this by adding a golden file https://github.com/aquasecurity/trivy/blob/main/integration/client_server_test.go#L92-L98

**Comment by bmagistro** [comment]
I will see if I can get a test added in the next week or so.

**Comment by bmagistro** [comment]
I'm having issues with the golden file locally but using the diffs I can't find the delta between them so pushing them.  If I had to guess it's a whitespace issue somewhere, any chance you can assist?

**Review by rahul2393 — APPROVED** [review]

**Comment by knqyf263** [comment]
@rahul2393 Could you help @bmagistro with the test?

**Comment by rahul2393** [comment]
Yeah on it

**Comment by rahul2393** [comment]
@knqyf263 Fixed

**Comment by bmagistro** [comment]
So I missed seeing the line endings in the actual/expected output and was focusing on the diff output...

**Comment by knqyf263** [comment]
@bmagistro Looks good! Could you update the documentation?
https://github.com/aquasecurity/trivy/tree/main/docs/integrations

**Review by knqyf263 — APPROVED** [review]

**Comment by knqyf263** [comment]
Thank you for contributing and your patience!

**Pull request merged**
