### PR TITLE
fix: respect GITHUB_TOKEN to download artifacts from GHCR

### PR DESCRIPTION
**Pull request by knqyf263**
## Description
The [troubleshooting documentation](https://aquasecurity.github.io/trivy/v0.55/docs/references/troubleshooting/#github-rate-limiting) currently suggests setting the `GITHUB_TOKEN` to avoid rate limiting. However, this information was outdated, created when the `image` subcommand didn't even exist. We've identified that in the latest version of Trivy, the `GITHUB_TOKEN` is not correctly utilized when downloading the vulnerability database, checks bundles and the Java database. The token helps pull these assets from private repositories. Note that it currently doesn't help with rate limiting.

This PR addresses the issue by implementing the correct usage of `GITHUB_TOKEN` for GHCR.

## Notes
The `docker login ghcr.io` functionality is working as expected and remains unchanged.

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by knqyf263** [comment]
Even GITHUB_TOKEN doesn't seem to help...

```
$ GITHUB_TOKEN=$(gh auth token) mage test:fixtureContainerImages
{unset gho_XXXXXXXXXXXXXXXXXXXXXXXXX}
Error: GET https://ghcr.io/v2/aquasecurity/trivy-test-images/tags/list?n=1000: TOOMANYREQUESTS: retry-after: 71.346µs, allowed: 44000/minute
```

**Comment by schnatterer** [comment]
Does `docker login` work? How is it used within trivy? Does trivy read ` ~/.docker/config.json`? I am asking because I'd like to use it from within the trivy container where there is no `docker`. Can I just mount `~/.docker/config.json:/root/.docker/config.json`?

**Comment by knqyf263** [comment]
First of all, `GITHUB_TOKEN` doesn't seem to help for GHCR at the moment.

If you still want to try a token, you can just mount config.json as you said. If you use an OS-specific credential store, it will probably not work.

e.g.
```
$ jq .credsStore ~/.docker/config.json
"osxkeychain"
```

**Comment by schnatterer** [comment]
I tried to test it, but now I get

```
docker login ...
docker pull ghcr.io/aquasecurity/trivy:0.55.2
Error response from daemon: toomanyrequests: retry-after: 516.474µs, allowed: 44000/minute
```

So maybe it's not the rate limit on the user but a repo-specific limit on the ghcr.io/aquasecurity/trivy repo?
I added this theory to your discussion at https://github.com/orgs/community/discussions/139074.

**Comment by knqyf263** [comment]
@DmitriyLewen We found that this fix does not help with rate limiting, but it does help with downloads from private repositories, so I modified it and made it ready for review.

**Review by DmitriyLewen — APPROVED** [review]
LGTM

**Pull request merged**
