### PR TITLE
fix: revert asff arn and add documentation

### PR DESCRIPTION
**Pull request by AndrewCharlesHay**
## Description

This PR fixes the issues introduced in #2782. My understanding was that it was required to use the default ARN. This turns out not to be true. The PR fixes those issues and adds documentation for said issue as well as the required use of [enable-import-findings-for-product](https://docs.aws.amazon.com/cli/latest/reference/securityhub/enable-import-findings-for-product.html)

## Related PRs
- [X] #2782 

Remove this section if you don't have related PRs.

## Checklist
- [X] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [X] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [X] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by AndrewCharlesHay** [comment]
> @AndrewCharlesHay it's my mistake too. @knqyf263 was right (as usual)... it seems we should use
> 
> ```json
> "Product ARN": "arn:aws:securityhub:<REGION>::product/aquasecurity/aquasecurity"
> ```
> 
> because AWS Security Hub is already integrated with Aqua Cloud Native Security Platform: https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-partner-providers.html

I am guessing that they are using something other than the CLI to upload results. I am still trying to figure it out but when I changed it to that it gives me 
```An error occurred (AccessDeniedException) when calling the BatchImportFindings operation: User: arn:aws:sts::744824939882:assumed-role/gitlab_runner_profile/i-006e1ff0266d6b132 is not authorized to perform: securityhub:BatchImportFindings on resource: arn:aws:securityhub:us-east-2:744824939882:product/aquasecurity/aquasecurity with an explicit deny```

**Comment by AndrewCharlesHay** [comment]
jk I think this is the answer 
https://docs.aws.amazon.com/cli/latest/reference/securityhub/enable-import-findings-for-product.html

**Comment by AndrewCharlesHay** [comment]
Sorry yeah [enable-import-findings-for-product](https://docs.aws.amazon.com/cli/latest/reference/securityhub/enable-import-findings-for-product.html) was my issue 😓

**Comment by AndrewCharlesHay** [comment]
Sorry for the confusion @afdesk and @knqyf263

**Comment by knqyf263** [comment]
>because AWS Security Hub is already integrated with Aqua Cloud Native Security Platform:

Yes, this is what I was concerned 😄  @afdesk Could you review it at last?

**Comment by afdesk** [comment]
@AndrewCharlesHay could you change a description for this PR?
it does'n look relevant
thanks a lot!

**Comment by AndrewCharlesHay** [comment]
> @AndrewCharlesHay could you change a description for this PR? it does'n look relevant thanks a lot!

Updated it. Thanks!

**Review by knqyf263 — APPROVED** [review]

**Pull request merged**
