### PR TITLE
chore: bump Go to 1.22

### PR DESCRIPTION
**Pull request by knqyf263**
## Description
Go now has [forward compatibility](https://go.dev/blog/toolchain#:~:text=Forward%20compatibility%20refers%20to%20what,against%20older%20versions%20of%20M.). A project that needs Go 1.22 can be compiled with Go 1.21 as Go transparently downloads Go 1.22.

```
$ go version
go version go1.21.6 darwin/arm64
$ go mod tidy
go: downloading go1.22.0 (darwin/arm64)
```

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by knqyf263** [comment]
Waiting for TinyGo v0.31.0.
https://github.com/tinygo-org/tinygo/milestone/17

**Comment by simar7** [comment]
> Waiting for TinyGo v0.31.0.
> https://github.com/tinygo-org/tinygo/milestone/17

New version was [released](https://github.com/tinygo-org/tinygo/releases/tag/v0.31.1) so I updated it [here](https://github.com/aquasecurity/trivy/pull/6075/commits/4b28e2d2195eaf4ce997fcc576d17df37e06a74e)

**Comment by simar7** [comment]
Strangely enough the build still fails, although locally it seems to be fine for me.

**Comment by nikpivkin** [comment]
For some reason `net.Buffers` has been removed from tinygo. I created an [issue](https://github.com/tinygo-org/tinygo/issues/4166).

**Comment by rogercoll** [comment]
Related to this issue, Trivy modules cannot be compiled with latest TinyGo(0.31.1) version:

```bash
$ tinygo build -o spring4shell.wasm -scheduler=none -target=wasi --no-debug spring4shell.go
# github.com/mailru/easyjson/buffer
../../../.go/pkg/mod/github.com/mailru/easyjson@v0.7.7/buffer/pool.go:171:14: undefined: net.Buffers
```

**Comment by knqyf263** [comment]
I removed the easyjson dependency here. After it gets merged, it will be fixed.
https://github.com/aquasecurity/trivy/pull/6240

**Comment by evacchi** [comment]
fyi you might not need this after all https://github.com/tinygo-org/net/pull/22

**Comment by knqyf263** [comment]
>fyi you might not need to remove the easyjson dep after all https://github.com/tinygo-org/net/pull/22 :)

Thanks for sharing! But I wanted to remove the dependency anyway. It's a good opportunity🙃

**Review by chen-keinan — APPROVED** [review]

**Pull request merged**
