### PR TITLE
fix(db): change argument order in Exists query for JavaDB

### LINKED ISSUE #4620: Failure in exists query for JavaDB
### Discussed in https://github.com/aquasecurity/trivy/discussions/4594

<div type='discussions-op-text'>

<sup>Originally posted by **DaspawnW** June  8, 2023</sup>
### Description

During a trial to implement a hack to get the Java DB as a dedicated server #3560 I detected that the signature of the Exists method doesn't match with the SQL Query that is performed. I'm not a golang developer so maybe my bug report is wrong, but I also so far found no description that proofs that I'm wrong.

### Desired Behavior

The Exists function in the [javadb/client.go](https://github.com/aquasecurity/trivy/blob/main/pkg/javadb/client.go#L119) file calls the `SelectIndexByArtifactIDAndGroupID(artifactID, groupID)` out of the [trivy-java-db](https://github.com/aquasecurity/trivy-java-db/blob/main/pkg/db/db.go#L162) in the argument order artifactID, groupID.

### Actual Behavior

The current behavior is that the function gets called by [javadb/client.go](https://github.com/aquasecurity/trivy/blob/main/pkg/javadb/client.go#L119) in the opposite order with groupID, artifactID.

### Reproduction Steps

```bash
1. Compare https://github.com/aquasecurity/trivy/blob/main/pkg/javadb/client.go#L119 with https://github.com/aquasecurity/trivy-java-db/blob/main/pkg/db/db.go#L162
```

### Target

None

### Scanner

None

### Output Format

None

### Mode

None

### Debug Output

```bash
nn
```

### Operating System

nn

### Version

```bash
latest main branch
```

### Checklist

- [ ] Run `trivy --reset`
- [ ] Read [the troubleshooting](https://aquasecurity.github.io/trivy/latest/docs/references/troubleshooting/)</div>

### PR DESCRIPTION
**Pull request by DaspawnW**
## Related issues
- Close #4620

## Checklist
- [ x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x ] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by afdesk** [comment]
@DaspawnW thanks for your PR!

it looks like a curious mistake.
how did it work before? )

**Comment by afdesk** [comment]
but I can't find a case where this mistake matters.

**Comment by DaspawnW** [comment]
Hi @afdesk,

I guess it's more a matter of performance. The Exists query gets called within the aquasecurity/go-dep-parser
https://github.com/aquasecurity/go-dep-parser/blob/main/pkg/java/jar/parse.go#L144 . In this particular case it will always fail and continue then with the SHA1 based query https://github.com/aquasecurity/go-dep-parser/blob/main/pkg/java/jar/parse.go#L151

So it will work but has to perform for each dependency a second query even though it's available.

**Comment by afdesk** [comment]
it seems i understood what happens:
this block never runs 
https://github.com/aquasecurity/go-dep-parser/blob/main/pkg/java/jar/parse.go#L146

**Comment by afdesk** [comment]
Hi @DaspawnW 
thanks! you're right!

**Comment by afdesk** [comment]
@DaspawnW I've created an issue from your discussion - it's our workflow.
and updated your comment, i hope it's ok.

**Review by afdesk — APPROVED** [review]
thanks for good catch!

**Pull request merged**
