### PR TITLE
feat: add special IDs for filtering secrets

### PR DESCRIPTION
**Pull request by knqyf263**
## Description
Same as https://github.com/aquasecurity/trivy/pull/3651, but for secrets.

It fills 4.10 in Docker CIS Benchmark.

### Before

image

### After

image

## Related issues
- Close https://github.com/aquasecurity/trivy/issues/3563

## Related PRs
- [x] https://github.com/aquasecurity/defsec/pull/1210
- [x] https://github.com/aquasecurity/trivy/pull/3651

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [x] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by knqyf263** [comment]
This PR is blocked by https://github.com/aquasecurity/trivy/pull/3704, but it is ready for review.

**Comment by chen-keinan** [comment]
@knqyf263 @itaysk need to update `go.mod` with latest defsec and also new `desec` package should be published

**Comment by simar7** [comment]
> This PR is blocked by #3704, but it is ready for review. I'll bump defsec after #3704 gets merged.

new version of defsec is now released https://github.com/aquasecurity/defsec/releases/tag/v0.84.0

**Comment by knqyf263** [comment]
@chen-keinan Bumped defsec. Can you review it?

**Review by chen-keinan — APPROVED** [review]

**Pull request merged**
