### PR TITLE
Docker multi-platform image build with `buildx`, using Goreleaser

### PR DESCRIPTION
**Pull request by ocean**
As discussed in #496 I've taken inspiration from the Goreleaser example file and set up Docker multi-platform image building with the `buildx` command.

I set this up and got it working publishing images to my own Docker Hub repo, you can see [the built images here](https://hub.docker.com/r/oceanic/trivy/tags).

### CODE REVIEW

**Comment by ocean** [comment]
Note: the automated build test has failed because one of the changes is to the `release.yml` GitHub workflow file, which isn't picked up and used in the testing of the PR, I guess understandably, but still and odd thing to work around.

For the build test to complete, it will need [lines 13-26 of the `release.yml`](https://github.com/aquasecurity/trivy/pull/915/files#diff-e426ed45842837026e10e66af23d9c7077e89eacbe6958ce7cb991130ad05adaR13-R26) in the PR, which enable and set up the Docker Buildx command.

**Comment by knqyf263** [comment]
Great contribution! Looks good to me. @krol3 Could you also review it? We need to make sure it works with GHCR and ECR as well as Docker Hub.

**Comment by ocean** [comment]
Oh, sorry @knqyf263 , I should have got my branch version to push to my GHCR, I forgot because I haven't used it. I'll set it to do that now so you can see it works 👍

**Comment by ocean** [comment]
Ok, I changed the config so Goreleaser would publish to my GHCR repo, and here's the [tagged multi-arch container](https://github.com/users/ocean/packages/container/package/trivy).

Here's the GH Actions run that published it https://github.com/ocean/trivy/runs/2191403662?check_suite_focus=true

**Comment by krol3** [comment]
@ocean Nice contribution. Could you update setup-go to in test.yaml with the same version `actions/setup-go@v2` that you are using in release.yml

**Comment by ocean** [comment]
Ok @krol3 , done, sorry I missed those ones. I also realised the `test.yml` workflow won't complete unless the Docker Buildx support is added in there as well, so I've added that.

**Review by krol3 — APPROVED** [review]
LGTM

**Comment by knqyf263** [comment]
Thanks a lot!

**Pull request merged**
