### PR TITLE
docs(cli): update CLI docs with cobra

### LINKED ISSUE #3734: CLI reference docs are out of date
Docs under: https://aquasecurity.github.io/trivy/v0.38/docs/references/cli/ are out of date.
I suppose we can generate docs automatically as part of the workflow using https://github.com/spf13/cobra/blob/main/doc/md_docs.md

### PR DESCRIPTION
**Pull request by ShubhamPalriwala**
## Description
Generates docs for the CLI which are auto-generated using cobra's doc package.

These are the auto-generated docs for our current `rootCmd`.

The only change I have made manually is that all the files were auto generated as `trivy_subcommand.md` which I renamed to `subcommand.md`

Also I am not sure if we need the `plugin` documentation here.

## Related issues
- Close #3734 

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [x] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by itaysk** [comment]
Thanks! this is great. can we automate this process so that we don't need to regenerate manually every time there a change?

**Comment by ShubhamPalriwala** [comment]
Hey @itaysk, sorry for the delayed response. I looked up for any automated/CI runnable tasks for the same but did not find any.

However, I can ideate on a couple of potential ideas on how we can build something of our own and then prolly make it generic for others to also use it. Let me know if that is something you are open to and I'll get back with some concrete approach!

**Comment by itaysk** [comment]
ok maybe automating it is too much for this PR. But the problem is that you made some manual changes to the generated output which will be hard to reproduce next time there's a change. We need a quick way to regenerate the cli docs consistently, even if manually run. Can you perhaps add this to the Makefile?

**Comment by ShubhamPalriwala** [comment]
Okay. Reiterating the manual changes I made, let me know what all do you want me to include in the Makefile:
1. Rename all `trivy_*.md` to `*.md`
2. Rename `trivy.md` to `inex.md`
3. Updated all references inside the files of 1st point

The 3rd had to be done to make sure the links to the parent/subcommands are valid. I am not sure how I can replicated the 3rd one in a make file.

If we are fine with the `trivy_*.md` naming convention then we might not need any manual changes.

**Comment by itaysk** [comment]
I suppose we can just use the default names that the tool generates, right? and then we don't need any customization.

**Comment by itaysk** [comment]
yes please. and if you do that can you include a command to regenerate the docs in the makefile?

**Comment by ShubhamPalriwala** [comment]
I will have to see how I can add it to the Makfile because (as per how I understood the docs), I took the following approach:
- Opened the trivy codebase and located the where our `roomCmd` is defined in pkg/commands/app.go
- Added the following piece of code:
```go
	err := doc.GenMarkdownTree(rootCmd, "./docs/docs/references/cli")
	if err != nil {
		log.Fatal(err)
	}
```
- Did a go run to generate the docs
- Now did a git add for all the docs and reverted the changes in app.go

In my opinion, we can merge the changes once I update it and then I will work on automating this separately if that sounds good to you?

**Comment by ShubhamPalriwala** [comment]
@itaysk Updated the PR with only the automated changes in place!

**Comment by itaysk** [comment]
I'm fine with merging this and adding automation in another PR. To answer your question I think the best approach would be to create a simple go file which will be `go run` from the Makefile.

**Comment by ShubhamPalriwala** [comment]
Done, sorry for missing that! PTAL @itaysk

**Review by AnaisUrlichs — APPROVED** [review]

**Comment by AnaisUrlichs** [comment]
Oh this is great! Thank you @ShubhamPalriwala!

**Pull request merged**
