### PR TITLE
feat: add a flag for selectively enabling config types

### PR DESCRIPTION
**Pull request by nikpivkin**
## Description

- [ ] add tests
- [ ] update doc

## Related issues
- Close https://github.com/aquasecurity/trivy/issues/4901

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by simar7** [comment]
hi @nikpivkin please hold off on this as we have not planned it for this milestone.

**Comment by knqyf263** [comment]
This enhancement is similar to [this proposal](https://github.com/aquasecurity/trivy/issues/3987). Do we want to provide a consolidated flag across all scanners, like `--sub-scanners ruby,terraform`? Or we can expand the existing flag `--scanners vuln:ruby config:terraform`. Also, we need to think about enabling or disabling. What if people just want to disable Azure ARM scanning with `--config-type`?

**Comment by simar7** [comment]
> This enhancement is similar to [this proposal](https://github.com/aquasecurity/trivy/issues/3987). Do we want to provide a consolidated flag across all scanners, like `--sub-scanners ruby,terraform`? Or we can expand the existing flag `--scanners vuln:ruby config:terraform`. Also, we need to think about enabling or disabling. What if people just want to disable Azure ARM scanning with `--config-type`?

This [issue](https://github.com/aquasecurity/trivy/issues/4901) only focuses only misconfiguration scanning. Today it's a single target with no way to disable/enable different kinds of IaC.

**Comment by knqyf263** [comment]
@itaysk Do you have any thoughts? We renamed `--security-checks` to `--scanners` according to your suggestion. Do you prefer `--config-scanners` rather than `--config-type`?

If we also want to provide a capability of disabling config types, we may need `--enable-config-type` and `--disable-config-type`.

**Comment by itaysk** [comment]
> Do you prefer --config-scanners rather than --config-type

Between these I'd go with `--scanner-config`
But I'm not sure we have to make it generic like that, as opposed to every scanner can have scanner-specific flags. I'm afraid in the future it would evolve to more than a list of scanner "components" to enable/disable, but how to configure them, and then we end up with crazy syntaxes like `--scanner-config vulnerability:ruby:some-ruby-thing=something`. If we are not sure, it's better to start with specific flags and later consolidate.

**Comment by knqyf263** [comment]
Hmm, the name is probably confusing. I think `--config-scanners` and `--config-type` means misconfiguration scanners/types like `terraform`. @simar7 Am I correct?

@itaysk You suggested `--scanner-config` because you thought the flag was for all scanners, right? We can forget about it. Another flag looks better now.

We might want to replace `--scanner config` with `--scanner misconfig` so that we will not be confused with the word `config`. Then, the new flag should be `--misconfig-scanners` or `--misconfig-types`. What do you think?

**Comment by simar7** [comment]
> Hmm, the name is probably confusing. I think `--config-scanners` and `--config-type` means misconfiguration scanners/types like `terraform`. @simar7 Am I correct?

That's right. I had proposed `trivy config --config-type=dockerfile,helm`.

> We might want to replace `--scanner config` with `--scanner misconfig` so that we will not be confused with the word `config`. Then, the new flag should be `--misconfig-scanners` or `--misconfig-types`. What do you think?

Yeah this is good, I think it will reduce confusion as we call reference `misconfig` mostly everywhere.

**Comment by itaysk** [comment]
yes. sorry I read this too fast. SGTM

**Comment by knqyf263** [comment]
@simar7 I opened a PR.
https://github.com/aquasecurity/trivy/pull/5558

**Comment by knqyf263** [comment]
https://github.com/aquasecurity/trivy/pull/5558 got merged. We can now use something like `--misconfig-type`. I'd vote for `--misconfig-scanner terraform,dockerfile` as `--vuln-type os` is more higher-level. We will probably add `--vuln-scanners php,python`, so `--misconfig-scanners` is more aligned with that. What do you think?

**Comment by simar7** [comment]
> #5558 got merged. We can now use something like `--misconfig-type`. I'd vote for `--misconfig-scanner terraform,dockerfile` as `--vuln-type os` is more higher-level. We will probably add `--vuln-scanners php,python`, so `--misconfig-scanners` is more aligned with that. What do you think?

Yeah `--misconfig-scanners=dockerfile,terraform` makes sense to me. We can close this PR for now and start afresh.

**Pull request closed without merging**
