### PR TITLE
feat(cli): add --webhook option

### PR DESCRIPTION
**Pull request by cho0o0**
The reason to add this option is described here: https://github.com/aquasecurity/trivy/issues/632
I tried to follow the design of Trivy's codebase, make minimal changes and avoid breaking current APIs.
Feel free to adjust this PR and ask for changes.
Thank you.

### CODE REVIEW

**Comment by dbrennand** [comment]
Hi @cho0o0 

This PR is awesome. I am looking for this exact functionality. 👍

**Comment by knqyf263** [comment]
Hi @cho0o0, thank you for the great PR! I want to make report functions pluggable because it is better to keep Trivy small. If we achieve it, a user can develop a report plugin themself such as Slack and Teams integrations. Could you give me some more time?

**Comment by cho0o0** [comment]
@knqyf263 
Thanks for your response. No problem! Feel free to inform me if you need any help or I could be involved.

**Comment by knqyf263** [comment]
Trivy has plugins now. If you need to send it somewhere, you can save a result JSON at first and then send it in your plugin.
https://aquasecurity.github.io/trivy/v0.18.3/plugins/

We really appreciate your contribution. We were inspired by your PR. Thanks.

**Comment by cho0o0** [comment]
@knqyf263 No worries. Thanks for the update!

**Pull request closed without merging**
