### PR TITLE
Added EOL for Ubuntu 21.10

### PR DESCRIPTION
**Pull request by designanderror**
As per (https://wiki.ubuntu.com/Releases) and (https://ubuntu.com/about/release-cycle), Ubuntu 21.10 is supported until July 2022

### CODE REVIEW

**Comment by knqyf263** [comment]
Is there any reason to close https://github.com/aquasecurity/trivy/pull/1100?

**Comment by designanderror** [comment]
> Is there any reason to close #1100?

Messed up while reverting PR.

**Review by knqyf263 — APPROVED** [review]

**Comment by fawind** [comment]
I don't think 21.10 is supported by the backing vuln DBs yet? At least I'm not getting any vulns reported when scanning this version but afaik there should be some vulns present ([ref](https://ubuntu.com/security/cve?q=&package=&priority=&version=impish&status=needed)):

```
$ trivy --debug image --format json ubuntu:21.10
2021-10-12t11:38:50.451+0100    debug   db schema: 1, type: 1, updatedat: 2021-10-12 06:05:43.152287503 +0000 utc, nextupdate: 2021-10-12 12:05:43.152287103 +0000 utc, downloadedat: 2021-10-12 09:56:03.611686 +0000 utc
2021-10-12t11:38:51.717+0100    info    detected os: ubuntu
2021-10-12t11:38:51.717+0100    info    detecting ubuntu vulnerabilities...
2021-10-12t11:38:51.717+0100    debug   ubuntu: os version: 21.10
2021-10-12t11:38:51.717+0100    debug   ubuntu: the number of packages: 101
2021-10-12t11:38:51.717+0100    info    number of language-specific files: 0
{
  "schemaversion": 2,
  "artifactname": "ubuntu:21.10",
  "artifacttype": "container_image",
  "metadata": {
    "os": {
      "family": "ubuntu",
      "name": "21.10"
    },
    // ...
  },
  "results": [
    {
      "target": "ubuntu:21.10 (ubuntu 21.10)",
      "class": "os-pkgs",
      "type": "ubuntu"
    }
  ]
}
```

Before this PR, trivy would flag this case with logging `This OS version is not on the EOL list: ...` but right now there is no way to distinguish between a passing scan and the OS not having vulns listed.

**Comment by knqyf263** [comment]
I hope it is supported now.

```
$ trivy image ubuntu:21.10
2021-11-09T16:52:23.811+0200    INFO    Need to update DB
2021-11-09T16:52:23.811+0200    INFO    Downloading DB...
24.61 MiB / 24.61 MiB [--------------------------------------------------------------------------------------------------------------------------------------] 100.00% 8.57 MiB p/s 3s
2021-11-09T16:52:36.303+0200    INFO    Detected OS: ubuntu
2021-11-09T16:52:36.303+0200    INFO    Detecting Ubuntu vulnerabilities...
2021-11-09T16:52:36.325+0200    INFO    Number of language-specific files: 0

ubuntu:21.10 (ubuntu 21.10)
===========================
Total: 19 (UNKNOWN: 0, LOW: 17, MEDIUM: 2, HIGH: 0, CRITICAL: 0)
```

**Pull request merged**
