### PR TITLE
docs:  follow Debian's "instructions to connect to a third-party repository"

### LINKED ISSUE #2180: docs: Installation on Debian/Ubuntu: follow Debian's "instructions to connect to a third-party repository"
According to the Debain wiki keys “MUST NOT be placed in /etc/apt/trusted.gpg.d or loaded by apt-key add.”: <https://wiki.debian.org/DebianRepository/UseThirdParty>

So instead of this:

```bash
wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
```

the [Debian/Ubuntu installation instructions](https://github.com/aquasecurity/trivy/blob/v0.28.0/docs/getting-started/installation.md#debianubuntu) could look like this:

```bash
wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
```

### PR DESCRIPTION
**Pull request by Akshit42-hue**
## Description
( Update docs)Instructions to connect to a third-party repository
## Related issues
- Close #2180

### CODE REVIEW

**Comment by Akshit42-hue** [comment]
Please do have a look @knqyf263

**Comment by knqyf263** [comment]
@DmitriyLewen Could you test this change?

**Comment by DmitriyLewen** [comment]
@knqyf263 i checked all actual `Ubuntu` and `Debian` releases. 
Script works correctly.

**Review by DmitriyLewen — APPROVED** [review]

**Review by knqyf263 — APPROVED** [review]

**Comment by knqyf263** [comment]
Thank you guys

**Pull request merged**
