### PR TITLE
fix(misconf): update a build-in rule for AWS Access Key ID and Secret Access Key

### PR DESCRIPTION
**Pull request by afdesk**
## Description
Now Trivy build-in rule for AWS Secret Access Key supports only a key with fixed length (40 symbols).
If `AWS_SECRET_ACCESS_KEY` has length more or less 40, Trivy will skip it.

[AWS documentation](https://docs.aws.amazon.com/STS/latest/APIReference/API_Credentials.html) describes next constraints (maybe I missed something) for `AccessKeyId`: Minimum length of 16. Maximum length of 128.

Unfortunately I couldn't find constraints for `AWS_SECRET_ACCESS_KEY`.

I expanded the ranges a bit, that allows to detect almost correct keys.
is it ok?

before:
```sh
Dockerfile (secrets)

Total: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 1)

CRITICAL: AWS (aws-access-key-id)
════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
AWS Access Key ID
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 Dockerfile:6
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   4   
   5   ENV AWS_SECRET_ACCESS_KEY="xXxxxXXXXXEMI/K7ZZZXX/bXxXxxXXXXAMPYYYY"
   6 [ ENV AWS_ACCESS_KEY_ID="********************"
   7   
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```
after:
```sh
Dockerfile (secrets)

Total: 2 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 2)

CRITICAL: AWS (aws-access-key-id)
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
AWS Access Key ID
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 Dockerfile:6
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   4   
   5   ENV AWS_SECRET_ACCESS_KEY="***************************************"
   6 [ ENV AWS_ACCESS_KEY_ID="********************"
   7   
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


CRITICAL: AWS (aws-secret-access-key)
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
AWS Secret Access Key
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 Dockerfile:5
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   3   COPY test.txt /test.txt
   4   
   5 [ ENV AWS_SECRET_ACCESS_KEY="***************************************"
   6   ENV AWS_ACCESS_KEY_ID="********************"
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


```

## Related issues
- Close a part of #3778 

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by knqyf263** [comment]
AFAIR, We referred to the tool from AWS. Do you think they are wrong?
https://github.com/awslabs/git-secrets/blob/99d01d58ebcc06e237c0e3f3ff5ae628aeef6aa6/git-secrets#L238-L240

**Comment by afdesk** [comment]
> AFAIR, We referred to the tool from AWS. Do you think they are wrong? https://github.com/awslabs/git-secrets/blob/99d01d58ebcc06e237c0e3f3ff5ae628aeef6aa6/git-secrets#L238-L240

no, it's just an idea.

the customer's key can be less (or more) 40 symbols (eg 39), and Trivy skips it. 
I thought that it's not a big deal to recover a correct key if you know 39 symbols from 40.

but it's up to you )

**Comment by knqyf263** [comment]
Would you search their repository and see if there is a similar issue?

**Comment by knqyf263** [comment]
>yes, git-secrets has the same issue:

Ah, sorry I meant the GitHub issue. Does anyone raise the same issue on GitHub?

**Comment by knqyf263** [comment]
Interesting. I have looked around at several tools and they assume 16 characters for AWS access key id. Is this causing any issues in real? I saw the original issue, but the strings seem to be for example like `wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKE`. I'm wondering if it is just a mistake.

**Comment by afdesk** [comment]
> Interesting. I have looked around at several tools and they assume 16 characters for AWS access key id. Is this causing any issues in real? I saw the original issue, but the strings seem to be for example like `wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKE`. I'm wondering if it is just a mistake.

Formally `wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKE` isn't a correct AWS secret access key, because this string contains only 39 characters instead of 40. 
so the config with private data won't work correctly.

it looks like a typo.

**Comment by knqyf263** [comment]
OK. Let me close this PR. If we see any issues, we can reopen this.

**Pull request closed without merging**
