### PR TITLE
Disable library analyzer for OS only scan type

### PR DESCRIPTION
**Pull request by fawind**
We are running into the issue that with the addition of JAR scanning in [v0.17.0](https://github.com/aquasecurity/trivy/discussions/966), Trivy tries to reach out to "maven.org" in order to resolve maven artifacts. This breaks running the scanner in an air-gapped environment where these requests time out (https://github.com/aquasecurity/trivy/issues/1185, https://github.com/aquasecurity/trivy/issues/982).

The proper solution in my opinion would be to mark analyzers that don't require network access as offline capable and add a separate offline flag that only runs those analyzers (we could start with just excluding the jar analyzer). Happy to contribute this if you agree with this approach!

As a more workaround solution, we should also exclude programming language analyzers when only running with `--vulnType os` (and maybe vice-versa exclude OS analyzers when running with `--vulnType library`?) ([list of all analyzers](https://github.com/aquasecurity/fanal/blob/ca0b4644ad874ba4811a53a89c6da74c3da95bf3/analyzer/const.go)).

This is a draft PR to start the discussion for the latter one. If you're happy with this approach I would clean this up and add some tests.

### CODE REVIEW

**Comment by schdief** [comment]
@knqyf263 any chance that you can have a look at this soon, seems like an easy fix, but is quite troubling for us

thanks a lot for providing trivy!

**Comment by schdief** [comment]
@fawind could you please sign the CLA to get this merged?

**Comment by fawind** [comment]
I think the CLA expires after a while. Re-signed it.

**Comment by knqyf263** [comment]
@fawind I'm sorry for the inconvenience. We recently updated our CLA. All contributors need to resign and that's why you needed to sign it again.
https://blog.aquasec.com/open-source-contributor-license

**Review by knqyf263 — APPROVED** [review]

**Comment by knqyf263** [comment]
Thanks!

**Comment by fawind** [comment]
Thanks for taking the time and bringing this over the line @knqyf263!

Do you know if there is a timeline for the next release that will include this fix?

**Comment by knqyf263** [comment]
We plan to release it by next week.

**Pull request merged**
