### PR TITLE
feat(conversion): from a json report generate other repo

### LINKED ISSUE #720: Multiple report options
Is there a way to save the JSON output then run Trivy with that as input to get the output in a second format? Without having to perform the scan twice? 

I need one format (XML) for feedback to the pipeline system, and another (JSON) for our security team.

I'm currently running the scan twice. Luckily it is fast enough, but seems a waste. 

Thanks

### PR DESCRIPTION
**Pull request by utix**
## Related issues
- Close #720

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [x] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by knqyf263** [comment]
Thanks for your PR, but we don't have a plan to add the `convert` command at the moment. It would be great if you create a plugin.
https://aquasecurity.github.io/trivy/v0.32/docs/advanced/plugins/

**Comment by utix** [comment]
Have you some tips about how to make it a plugin, report filtering and generation are needed for convert but are deeply in the scan part. It seems to be hard to not factorize those parts.

**Comment by utix** [comment]
@knqyf263 any way to reconsider this position ? The filtering and the report generation are hard to extract, the feature is not a big change, basically read a json (new stuff) and dump in other format (already existing)

**Comment by knqyf263** [comment]
Eventually, we decided to accept your proposal. I took your commits and opened a new PR so that your contribution can remain.

**Pull request closed without merging**
