### PR TITLE
refactor: export useful APIs

### PR DESCRIPTION
**Pull request by knqyf263**
## Description
Simplify APIs and export them mainly for `trivy k8s`.

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.

### CODE REVIEW

**Review by oranmoshai — APPROVED** [review]

**Review by josedonizetti — COMMENTED** [review]
@knqyf263 This is a good start, the runner idea helps simplify the code, but we would have to change more things to make it work. 

For example, if I instantiate a runner, and call [`ScanImage`](https://github.com/aquasecurity/trivy/blob/81ad83d0ada872cd4bc8f2a713f1b1344433d6a6/pkg/commands/artifact/run.go#L119) I have to pass the target on `opt.Input=`, but if I pass a non empty input, the `ScanImage` function picks the [archive scanner instead of the container image scanner](https://github.com/aquasecurity/trivy/blob/81ad83d0ada872cd4bc8f2a713f1b1344433d6a6/pkg/commands/artifact/run.go#L125). 

And I can use the `Scan` generic functions because the scanners are not exported.

**Comment by knqyf263** [comment]
What if pass `opt.Target`? `Input` is for image archive.

**Review by josedonizetti — APPROVED** [review]
Nice, it works.

**Comment by knqyf263** [comment]
@josedonizetti Can we merge it now?

**Pull request merged**
