### PR TITLE
feat(dockerfile): support 'Containerfile' as config filename

### LINKED ISSUE #1980: Support 'Containerfile' as config filename
## Description

Podman uses Dockerfile as well as Containerfile as filenames for the container build ([ref](https://docs.podman.io/en/latest/markdown/podman-build.1.html)), but at the moment, trivy does not detect `Containerfile` as a valid config file to be analyzed.

Since the same syntax is used for the image building, it would be interesting to add `Containerfile` as a "synonym" of `Dockerfile`.

## What did you expect to happen?

Detect `Containerfile` as a configuration file.

## What happened instead?

`Containerfile` is not detected.

## Output of run with `-debug`:

```
user:/app/build# ls
Containerfile  bin
user::/app/build# trivy -debug config .
2022-04-12T11:14:40.995Z	DEBUG	Severities: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
2022-04-12T11:14:40.996Z	DEBUG	cache dir:  /root/.cache/trivy
2022-04-12T11:14:40.996Z	DEBUG	Vulnerability type:  []
2022-04-12T11:14:41.093Z	DEBUG	OS is not detected and vulnerabilities in OS packages are not detected.
2022-04-12T11:14:41.093Z	INFO	Detected config files: 0
```

## Output of `trivy -v`:

```
user:/app/build# trivy -v
Version: 0.25.4
```

## Additional details (base image name, container registry info...):

N/A

### PR DESCRIPTION
**Pull request by nishipy**
## Description
We added 'Containerfile' support as a config file in aquasecurity/fanal/pull/475.
This PR will apply this update as follows.

### Before
```
$ ls ../test/
Containerfile   Dockerfile
$ ./trivy config ../test/
2022-04-23T08:28:13.332+0900    INFO    Detected config files: 1

Dockerfile (dockerfile)
=======================
Tests: 23 (SUCCESSES: 22, FAILURES: 1, EXCEPTIONS: 0)
Failures: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 1, CRITICAL: 0)

+---------------------------+------------+-----------+----------+------------------------------------------+
|           TYPE            | MISCONF ID |   CHECK   | SEVERITY |                 MESSAGE                  |
+---------------------------+------------+-----------+----------+------------------------------------------+
| Dockerfile Security Check |   DS002    | root user |   HIGH   | Specify at least 1 USER                  |
|                           |            |           |          | command in Dockerfile with               |
|                           |            |           |          | non-root user as argument                |
|                           |            |           |          | -->avd.aquasec.com/appshield/ds002       |
+---------------------------+------------+-----------+----------+------------------------------------------+
```

### After
```
$ ./trivy config ../test/
2022-04-23T08:30:00.632+0900    INFO    Detected config files: 2

Containerfile (dockerfile)
==========================
Tests: 23 (SUCCESSES: 22, FAILURES: 1, EXCEPTIONS: 0)
Failures: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 1, CRITICAL: 0)

+---------------------------+------------+-----------+----------+------------------------------------------+
|           TYPE            | MISCONF ID |   CHECK   | SEVERITY |                 MESSAGE                  |
+---------------------------+------------+-----------+----------+------------------------------------------+
| Dockerfile Security Check |   DS002    | root user |   HIGH   | Specify at least 1 USER                  |
|                           |            |           |          | command in Dockerfile with               |
|                           |            |           |          | non-root user as argument                |
|                           |            |           |          | -->avd.aquasec.com/appshield/ds002       |
+---------------------------+------------+-----------+----------+------------------------------------------+

Dockerfile (dockerfile)
=======================
Tests: 23 (SUCCESSES: 22, FAILURES: 1, EXCEPTIONS: 0)
Failures: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 1, CRITICAL: 0)

+---------------------------+------------+-----------+----------+------------------------------------------+
|           TYPE            | MISCONF ID |   CHECK   | SEVERITY |                 MESSAGE                  |
+---------------------------+------------+-----------+----------+------------------------------------------+
| Dockerfile Security Check |   DS002    | root user |   HIGH   | Specify at least 1 USER                  |
|                           |            |           |          | command in Dockerfile with               |
|                           |            |           |          | non-root user as argument                |
|                           |            |           |          | -->avd.aquasec.com/appshield/ds002       |
+---------------------------+------------+-----------+----------+------------------------------------------+
```
## Related issues
- Close #1980

## Related PRs
- [x] aquasecurity/fanal/pull/475

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [x] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [x] I've added usage information (if the PR introduces new options)
- [x] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by knqyf263** [comment]
Hi, thanks for your contribution, but we already updated fanal. Could you instead update our docs? You can just add Containerfile in addition to Dockerfile.
https://aquasecurity.github.io/trivy/v0.26.0/docs/misconfiguration/policy/builtin/#policy-sources
https://aquasecurity.github.io/trivy/v0.26.0/docs/misconfiguration/custom/

The directory is here.
https://github.com/aquasecurity/trivy/tree/main/docs/docs/misconfiguration

**Comment by nishipy** [comment]
Hi, 
I see. Let me create a PR to update these docs and get back to you later. Thank you.

**Comment by knqyf263** [comment]
Thanks. You can update this PR.

**Comment by nishipy** [comment]
Oh, understood. Let me do that.

**Comment by nishipy** [comment]
Updated the relevant docs. Could you review it? Thanks.

**Review by knqyf263 — APPROVED** [review]

**Comment by knqyf263** [comment]
Thanks!

**Pull request merged**
