### PR TITLE
feat(report): add secret scanning to ASFF template

### LINKED ISSUE #2855: ASFF doesn't support secrets reporting
## Description

The [gitlab-codequality.tpl](https://github.com/aquasecurity/trivy/blob/main/contrib/gitlab-codequality.tpl) file along with others iterate over [Vulnerabilities](https://github.com/aquasecurity/trivy/blob/main/contrib/gitlab-codequality.tpl#L6), [Misconfigurations](https://github.com/aquasecurity/trivy/blob/main/contrib/gitlab-codequality.tpl#L38), and [Secrets](https://github.com/aquasecurity/trivy/blob/main/contrib/gitlab-codequality.tpl#L70). The [ASFF.tpl](https://github.com/aquasecurity/trivy/blob/main/contrib/asff.tpl) and possibly others only iterate over [Vulnerabilities](https://github.com/aquasecurity/trivy/blob/main/contrib/asff.tpl#L10) and [Misconfigurations](https://github.com/aquasecurity/trivy/blob/main/contrib/asff.tpl#L72)

### PR DESCRIPTION
**Pull request by AndrewCharlesHay**
## Description

The Secrets reporting was left off the [asff.tpl](https://github.com/aquasecurity/trivy/blob/main/contrib/asff.tpl) file.

I'm not sure all of the fields available but I removed all the ones that were available for misconfigurations that aren't for secrets.

## Related issues
- Close #2855

## Checklist
- [X] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [X] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by knqyf263** [comment]
@afdesk Would you review this PR?

**Comment by knqyf263** [comment]
@afdesk How was it?

**Comment by afdesk** [comment]
sorry for waiting. 
it seems the updated asff template builds a correct result, so approved

**Comment by AndrewCharlesHay** [comment]
Thank you @afdesk

**Comment by afdesk** [comment]
oh, i have an idea.
maybe should we write an integration test for it?

**Comment by AndrewCharlesHay** [comment]
@afdesk Is there documentation on writing integration tests? I haven't looked to deep into it but I'm not sure how they work

**Comment by afdesk** [comment]
> @afdesk Is there documentation on writing integration tests? I haven't looked to deep into it but I'm not sure how they work

unfortunately, there is no any docs. but it's not a big deal.

we need to add some item here: https://github.com/aquasecurity/trivy/blob/68f79526bb8cf38cca96ade3bbb1dd92f2e21629/integration/client_server_test.go#L304-L312

and then we need to put test data files there: https://github.com/aquasecurity/trivy/tree/main/integration/testdata

you can update/create data if you set this flag to true: https://github.com/aquasecurity/trivy/blob/main/integration/integration_test.go#L27

if you have any questions please feel free to arise it.

thanks a lot

**Comment by afdesk** [comment]
@AndrewCharlesHay if it's ok for you, i can update the  integration test data

**Comment by AndrewCharlesHay** [comment]
> @AndrewCharlesHay if it's ok for you, i can update the integration test data

That would be great! I honestly didn't really want to 😄

**Comment by afdesk** [comment]
> > @AndrewCharlesHay if it's ok for you, i can update the integration test data
> 
> That would be great! I honestly didn't really want to smile

yes, sure. I'll try to add it.
@AndrewCharlesHay  thanks for your efforts

**Comment by knqyf263** [comment]
@afdesk Did you have a chance to add tests?

**Comment by afdesk** [comment]
> @afdesk Did you have a chance to add tests?

yes, almost done

**Comment by afdesk** [comment]
I've added a test and a golder file for it.
@AndrewCharlesHay @knqyf263  could take a look?

**Review by AndrewCharlesHay — COMMENTED** [review]
LGTM

**Comment by AndrewCharlesHay** [comment]
Thanks @afdesk !

**Comment by afdesk** [comment]
@AndrewCharlesHay thank you for the contribution

**Review by knqyf263 — APPROVED** [review]

**Pull request merged**
