### PR TITLE
fix(misconf): disable DS016 check for image history analyzer

### PR DESCRIPTION
**Pull request by nikpivkin**
## Related issues
- Close https://github.com/aquasecurity/trivy/issues/7368

## Related PRs
- [x] https://github.com/aquasecurity/trivy/pull/7536

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Review by knqyf263 — APPROVED** [review]
:shipit:

**Comment by DmitriyLewen** [comment]
@knqyf263 @nikpivkin 
maybe i missing something, but is it correct just skip `AVD-DS-0011`?

Maybe we can improve our logic `https://github.com/aquasecurity/trivy/blob/5b0bc5823e82c511f6d9f3cce1abbe3d900a51a8/pkg/fanal/image/image.go#L111` or at least write in the documentation that we skip this check for "--image-config-scanners misconfig"

**Comment by knqyf263** [comment]
Since [the logic](https://github.com/aquasecurity/trivy/blob/5b0bc5823e82c511f6d9f3cce1abbe3d900a51a8/pkg/fanal/image/image.go#L106) is based on the assumption that the CMD is set correctly and infers the base layer, it would be difficult to detect cases where the CMD is set incorrectly, as in the AVD-DS-0011 rule.

>or at least write in the documentation that we skip this check for "--image-config-scanners misconfig"

Agreed, we should show a debug message about disabled check IDs. And document maybe.

**Comment by nikpivkin** [comment]
@DmitriyLewen @knqyf263 That's reasonable. I'll create a PR for that.

**Comment by DmitriyLewen** [comment]
>  it would be difficult to detect cases where the CMD is set incorrectly

hmm... you are right. If user has set 2 (or more) CMDs incorrectly - we can't guess the base layer correctly.
But it seems there is no way to solve such problems 😞

**Comment by knqyf263** [comment]
>But it seems there is no way to solve such problems 😞

Yes, I didn't come up with a good idea, then I decided to disable it until we find a good approach.

**Pull request merged**
