### PR TITLE
fix(license): using common way for splitting licenses

### LINKED ISSUE #4772: fix(license): fix splitting licenses
A string like `BSD 3-Clause License or Apache License, Version 2.0` is split into `BSD 3-Clause License or Apache License` and `Version 2.0`, which is incorrect. This issue relates to the second problem of the discussion.

### Discussed in https://github.com/aquasecurity/trivy/discussions/4261

<div type='discussions-op-text'>

<sup>Originally posted by **2020-ks** March 10, 2023</sup>
## Description

I created sbom with CycloneDX by Trivy:
> trivy -v image ## -f cyclonedx --output ##.json --timeout 10m --security-checks vuln --ignore-unfixed

The creation succeeded, but I noticed that license information of several components is missing or incorrect.

## What did you expect to happen?

All detected components have license information.

## What happened instead?

1.Missing

At least, license information of following components is missing.
networkx, zipp, filelock, typer, iniconfig, packaging, tomli, typing_extensions, importlib-metadata, idna

2.Incorrect

In addition, following license information is incorrect.
uritemplate

"licenses": [
    {
        "expression": "BSD 3-Clause License or Apache License"
    },
    {
        **"expression": "Version 2.0"**
    }
]

## Output of run with `-debug`:

```
2023-03-10T11:44:50.440+0900    WARN    '--security-checks' is deprecated. Use '--scanners' instead.
2023-03-10T11:44:50.444+0900    DEBUG   ["cyclonedx" "spdx" "spdx-json" "github"] automatically enables '--list-all-pkgs'.
2023-03-10T11:44:50.444+0900    DEBUG   Severities: ["UNKNOWN" "LOW" "MEDIUM" "HIGH" "CRITICAL"]
2023-03-10T11:44:50.448+0900    DEBUG   cache dir:  .../.cache/trivy
2023-03-10T11:44:50.448+0900    DEBUG   There is no valid metadata file: unable to open a file: open .../.cache/trivy/db/metadata.json: no such file or directory
2023-03-10T11:44:50.448+0900    INFO    Need to update DB
2023-03-10T11:44:50.448+0900    INFO    DB Repository: ghcr.io/aquasecurity/trivy-db
2023-03-10T11:44:50.448+0900    INFO    Downloading DB...
2023-03-10T11:44:50.448+0900    DEBUG   no metadata file
35.94 MiB / 35.94 MiB [----------------------------------------------------------------------] 100.00% 7.10 MiB p/s 5.3s
2023-03-10T11:44:57.158+0900    DEBUG   Updating database metadata...
2023-03-10T11:44:57.158+0900    DEBUG   DB Schema: 2, UpdatedAt: 2023-03-10 00:13:33.078790601 +0000 UTC, NextUpdate: 2023-03-10 06:13:33.078790101 +0000 UTC, DownloadedAt: 2023-03-10 02:44:57.1583922 +0000 UTC
2023-03-10T11:44:57.158+0900    INFO    Vulnerability scanning is enabled
2023-03-10T11:44:57.158+0900    DEBUG   Vulnerability type:  [os library]
2023-03-10T11:44:57.278+0900    DEBUG   Saving the container image to a local file to obtain the image config...
2023-03-10T11:50:11.421+0900    DEBUG   Image ID: ...
2023-03-10T11:50:11.424+0900    DEBUG   Diff IDs: [...]
2023-03-10T11:50:11.425+0900    DEBUG   Base Layers: [....]
2023-03-10T11:50:11.601+0900    INFO    Detected OS: debian
2023-03-10T11:50:11.601+0900    INFO    Detecting Debian vulnerabilities...
2023-03-10T11:50:11.601+0900    DEBUG   debian: os version: 10
2023-03-10T11:50:11.601+0900    DEBUG   debian: the number of packages: 463
2023-03-10T11:50:11.868+0900    INFO    Number of language-specific files: 1
2023-03-10T11:50:11.869+0900    INFO    Detecting python-pkg vulnerabilities...
2023-03-10T11:50:11.870+0900    DEBUG   Detecting library vulnerabilities, type: python-pkg, path:
```

## Output of `trivy -v`:

```
2023-03-10T11:52:10.011+0900    WARN    '--security-checks' is deprecated. Use '--scanners' instead.
2023-03-10T11:52:10.021+0900    INFO    Vulnerability scanning is enabled
2023-03-10T11:57:16.014+0900    INFO    Detected OS: debian
2023-03-10T11:57:16.016+0900    INFO    Detecting Debian vulnerabilities...
2023-03-10T11:57:16.250+0900    INFO    Number of language-specific files: 1
2023-03-10T11:57:16.251+0900    INFO    Detecting python-pkg vulnerabilities...
```

## Additional details (base image name, container registry info...):
I attach sbom of components with problems
[pip_sboms_with_problem.txt](https://github.com/aquasecurity/trivy/files/10938125/pip_sboms_with_problem.txt)
</div>

### PR DESCRIPTION
**Pull request by afdesk**
## Description

The command for tests:
```sh
$ trivy -d i 2020ksdocker/ks-repository:ForInvestigation --scanners license --license-full
```

Before:
```
Total: 4 (UNKNOWN: 2, LOW: 2, MEDIUM: 0, HIGH: 0, CRITICAL: 0)

┌─────────────┬────────────────────────────────────────┬────────────────┬──────────┐
│   Package   │                License                 │ Classification │ Severity │
├─────────────┼────────────────────────────────────────┼────────────────┼──────────┤
│ pip         │ MIT                                    │ Notice         │ LOW      │
├─────────────┼────────────────────────────────────────┼────────────────┼──────────┤
│ uritemplate │ BSD 3-Clause License or Apache License │ Non Standard   │ UNKNOWN  │
│             ├────────────────────────────────────────┤                │          │
│             │ Version 2.0                            │                │          │
├─────────────┼────────────────────────────────────────┼────────────────┼──────────┤
│ click       │ BSD-3-Clause                           │ Notice         │ LOW      │
└─────────────┴────────────────────────────────────────┴────────────────┴──────────┘
```
after:
```
Python (license)

Total: 4 (UNKNOWN: 2, LOW: 2, MEDIUM: 0, HIGH: 0, CRITICAL: 0)

┌─────────────┬─────────────────────────────┬────────────────┬──────────┐
│   Package   │           License           │ Classification │ Severity │
├─────────────┼─────────────────────────────┼────────────────┼──────────┤
│ uritemplate │ BSD 3-Clause License        │ Non Standard   │ UNKNOWN  │
│             ├─────────────────────────────┤                │          │
│             │ Apache License, Version 2.0 │                │          │
├─────────────┼─────────────────────────────┼────────────────┼──────────┤
│ click       │ BSD-3-Clause                │ Notice         │ LOW      │
├─────────────┼─────────────────────────────┤                │          │
│ pip         │ MIT                         │                │          │
└─────────────┴─────────────────────────────┴────────────────┴──────────┘
```

## Related issues
- Close #4772

## Related PRs
- #4722 

## Checklist
- [ ] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [ ] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by nikpivkin** [comment]
after:
```
Python (license)

Total: 4 (UNKNOWN: 2, LOW: 2, MEDIUM: 0, HIGH: 0, CRITICAL: 0)

┌─────────────┬─────────────────────────────┬────────────────┬──────────┐
│   Package   │           License           │ Classification │ Severity │
├─────────────┼─────────────────────────────┼────────────────┼──────────┤
│ uritemplate │ BSD 3-Clause License        │ Non Standard   │ UNKNOWN  │
│             ├─────────────────────────────┤                │          │
│             │ Apache License, Version 2.0 │                │          │
├─────────────┼─────────────────────────────┼────────────────┼──────────┤
│ click       │ BSD-3-Clause                │ Notice         │ LOW      │
├─────────────┼─────────────────────────────┤                │          │
│ pip         │ MIT                         │                │          │
└─────────────┴─────────────────────────────┴────────────────┴──────────┘
```

**Comment by itaysk** [comment]
@afdesk is there an issue?

**Comment by afdesk** [comment]
> @afdesk is there an issue?

there is no issue yet. but there is a discussion https://github.com/aquasecurity/trivy/discussions/4261#discussioncomment-5895090, that brings two questions. This PR should fix one of them.

**Comment by itaysk** [comment]
if a discussion leads to work, we need to create an issue to track that work item, and the pr needs to refer to the issue. otherwise we just replaced issues with discussions

**Comment by knqyf263** [comment]
@nikpivkin Can you please sort our the problem and open an issue?

**Comment by nikpivkin** [comment]
@afdesk I created an [issue](https://github.com/aquasecurity/trivy/issues/4772), can you update the description?

**Comment by afdesk** [comment]
> @afdesk I created an [issue](https://github.com/aquasecurity/trivy/issues/4772), can you update the description?

done

**Review by knqyf263 — APPROVED** [review]

**Pull request merged**
