### PR TITLE
fix(kubernetes): Support floats in manifest yaml

### LINKED ISSUE #2284: misconfig: kubernetes resource not indetified
When passing cpu limits or requests with floating points, the file is not identified:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: ubuntu:latest
        resources:
          limits:
            cpu: 0.5
        command: ["tail", "-f", "/dev/null"]
        ports:
        - containerPort: 80
```

But if we wrap the number in a string, it works:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: ubuntu:latest
        resources:
          limits:
            cpu: "0.5"
        command: ["tail", "-f", "/dev/null"]
        ports:
        - containerPort: 80
```

### PR DESCRIPTION
**Pull request by owenrumney**
## Description
Support floats in Kubernetes yaml parser.

For example, CPU request and limits provided as decimals
```yaml
...
resources:
  limits:
    cpu: 0.5
```
Fixed in defsec

## Related issues
- Close #2284

## Checklist
- [X] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [X] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.

### CODE REVIEW

**Comment by josedonizetti** [comment]
@owenrumney Testing this change on the sample file I posted on the issue, still didn't work. 

```
./trivy version
Version: v0.28.1-49-g261a0ee0

./trivy config ../cputest
2022-06-10T15:47:57.023-0300	INFO	Detected config files: 0
```

**Comment by owenrumney** [comment]
> @owenrumney Testing this change on the sample file I posted on the issue, still didn't work. Not sure if I'm missing something.
> 
> 
> 
> ```
> 
> ./trivy version
> 
> Version: v0.28.1-49-g261a0ee0
> 
> 
> 
> ./trivy config ../cputest
> 
> 2022-06-10T15:47:57.023-0300	INFO	Detected config files: 0
> 
> ```

I'll take another look. I had tested it against your snippet so I will look again

**Comment by owenrumney** [comment]
```~/tmp/2248 bat cpu.yaml 
───────┬─────────────────────────────────────────────────────────────────────────────────────
       │ File: cpu.yaml
───────┼─────────────────────────────────────────────────────────────────────────────────────
   1   │ apiVersion: apps/v1
   2   │ kind: Deployment
   3   │ metadata:
   4   │   name: app
   5   │   labels:
   6   │     app: app
   7   │ spec:
   8   │   replicas: 1
   9   │   selector:
  10   │     matchLabels:
  11   │       app: app
  12   │   template:
  13   │     metadata:
  14   │       labels:
  15   │         app: app
  16   │     spec:
  17   │       containers:
  18   │       - name: app
  19   │         image: ubuntu:latest
  20   │         resources:
  21   │           limits:
  22   │             cpu: 0.5
  23   │         command: ["tail", "-f", "/dev/null"]
  24   │         ports:
  25   │         - containerPort: 80
───────┴─────────────────────────────────────────────────────────────────────────────────────

```


It's better now

```

LOW: Container 'app' of Deployment 'app' should set 'resources.requests.cpu'
═════════════════════════════════════════════════════════════════════════════════════════════
When containers have resource requests specified, the scheduler can make better decisions about which nodes to place pods on, and how to deal with resource contention.

See https://avd.aquasec.com/misconfig/ksv015
─────────────────────────────────────────────────────────────────────────────────────────────
 cpu.yaml:18-25
─────────────────────────────────────────────────────────────────────────────────────────────
  18 ┌       - name: app
  19 │         image: ubuntu:latest
  20 │         resources:
  21 │           limits:
  22 │             cpu: 0.5
  23 │         command: ["tail", "-f", "/dev/null"]
  24 │         ports:
  25 └         - containerPort: 80
─────────────────────────────────────────────────────────────────────────────────────────────
```

I think this PR had the branch commit it it maybe - but I've updated it with the correct master one and it looks okay

**Comment by owenrumney** [comment]
Seems the integration tests are finding Docker issues now with this fix. Need to work out how to resolve the tests

**Comment by knqyf263** [comment]
I'm sorry I forgot to tell you. We've updated the testing images. You need to run `make clean` in local. I fixed the tests.

**Review by knqyf263 — APPROVED** [review]

**Pull request merged**
