### PR TITLE
fix(misconf): skip Rego errors with a nil location

### PR DESCRIPTION
**Pull request by nikpivkin**
## Description

We have to skip errors without locations.

https://github.com/aquasecurity/trivy/pull/6502#discussion_r1591042149

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Review by simar7 — APPROVED** [review]

**Comment by chen-keinan** [comment]
@nikpivkin @simar7 it still failing at L187 : `return !lo.Contains(excludedFiles, e.Location.File)`
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x1032e5134]

goroutine 932 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/Users/chen.keinan/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.0/pkg/internal/controller/controller.go:111 +0x1a4
panic({0x10522fbe0?, 0x107a92230?})
	/opt/homebrew/Cellar/go/1.22.2/libexec/src/runtime/panic.go:770 +0x124
github.com/aquasecurity/trivy/pkg/iac/rego.(*Scanner).fallbackChecks.func1(0x1400213bb38?, 0x1032e4f70?)
	/Users/chen.keinan/go/pkg/mod/github.com/aquasecurity/trivy@v0.51.2-0.20240508034152-fe5d40e8ab13/pkg/iac/rego/load.go:187 +0x24
github.com/samber/lo.Filter[...]({0x14002708380, 0xb, 0x3d}, 0x1400213bc08?)
	/Users/chen.keinan/go/pkg/mod/github.com/samber/lo@v1.39.0/slice.go:15 +0x8c
github.com/aquasecurity/trivy/pkg/iac/rego.(*Scanner).fallbackChecks(0x14002e26360, 0x140019ec160)
	/Users/chen.keinan/go/pkg/mod/github.com/aquasecurity/trivy@v0.51.2-0.20240508034152-fe5d40e8ab13/pkg/iac/rego/load.go:186 +0xd4
github.com/aquasecurity/trivy/pkg/iac/rego.(*Scanner).compilePolicies(0x14002e26360, {0x10588a040, 0x1400498a720}, {0x140018a2b20, 0x1, 0x1})
	/Users/chen.keinan/go/pkg/mod/github.com/aquasecurity/trivy@v0.51.2-0.20240508034152-fe5d40e8ab13/pkg/iac/rego/load.go:245 +0x120
github.com/aquasecurity/trivy/pkg/iac/rego.(*Scanner).compilePolicies(0x14002e26360, {0x10588a040, 0x1400498a720}, {0x140018a2b20, 0x1, 0x1})
	/Users/chen.keinan/go/pkg/mod/github.com/aquasecurity/trivy@v0.51.2-0.20240508034152-fe5d40e8ab13/pkg/iac/rego/load.go:249 +0x158
github.com/aquasecurity/trivy/pkg/iac/rego.(*Scanner).LoadPolicies(0x14002e26360, 0x0, 0x0, {0x10588a040?, 0x1400498a720?}, {0x140018a2b20, 0x1, 0x1}, {0x0, 0x0, ...})
	/Users/chen.keinan/go/pkg/mod/github.com/aquasecurity/trivy@v0.51.2-0.20240508034152-fe5d40e8ab13/pkg/iac/rego/load.go:144 +0x7f8
github.com/aquasecurity/trivy/pkg/iac/scanners/kubernetes.(*Scanner).initRegoScanner(0x14000363980, {0x10588a040, 0x1400498a720})
```

**Comment by nikpivkin** [comment]
@chen-keinan Do you have an example of a policy that is causing this problem that I could add a test?

**Comment by chen-keinan** [comment]
> @chen-keinan Do you have an example of a policy that is causing this problem that I could add a test?

sure , here are the policies used in the tests:
https://github.com/aquasecurity/trivy-operator/tree/main/tests/envtest/testdata/content/policies/kubernetes/policies

**Comment by chen-keinan** [comment]
@nikpivkin  I have adde and example of policies

**Pull request merged**
