### PR TITLE
chore(deps): updates wazero to 1.0.0-rc.2

### PR DESCRIPTION
**Pull request by codefromthecrypt**
## Description

This updates [wazero](https://wazero.io/) to [1.0.0-rc.2](https://github.com/tetratelabs/wazero/releases/tag/v1.0.0-rc.2) which notably
* is the final release candidate before 1.0 next Friday.
* improves instantiation performance (startup time)
* passes `os` package tests defined by Go.
* no longer supports importing unnamed modules.

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [n/a] I've added tests that prove my fix is effective or that my feature works.
- [n/a] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [n/a] I've added usage information (if the PR introduces new options)
- [n/a] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by mathetake** [comment]
turns out that trivy test has started failing since this commit https://github.com/tetratelabs/wazero/commit/1e7660fc4f77af3727ec5a5729b1e89948ee7a2d

**Comment by mathetake** [comment]
this seems a bug in aquasecurity/memoryfs on `Mode()` function's return value, but I haven't gotten around to identify yet.

**Comment by mathetake** [comment]
basically dir entry of the memfs deosn't set `fs.ModeDir`  in the Mod() bits

**Comment by mathetake** [comment]
ok here you go https://github.com/aquasecurity/memoryfs/pull/1 @knqyf263

**Comment by knqyf263** [comment]
Thank you for figuring out our bug! We're replacing memoryfs with mapfs, then this error will be addressed. I'll update this branch after #3867 gets merged.

**Review by knqyf263 — APPROVED** [review]

**Comment by knqyf263** [comment]
Thanks a lot!

**Comment by mathetake** [comment]
cool passing! thanks you!

**Pull request merged**
