### PR TITLE
feat: log ignored vulnerabilities on debug

### PR DESCRIPTION
**Pull request by rethab**
this change makes trivy show when it finds a `ignorefile` file and how many IDs it finds in there. Furthermore, it logs each ignored vulnerability on debug.

this is a low-key version of https://github.com/aquasecurity/trivy/issues/674 and understandably not really machine consumable, but helps with analysing issues around ignored vulnerabilities.

if you feel like this is totally useless, please feel free to close the PR again :)

### CODE REVIEW

**Comment by knqyf263** [comment]
I'm concerned that it shows too many messages.

**Comment by rethab** [comment]
Thanks for your feedback @knqyf263 . This should only be run on startup, only when the user has enabled debugging and then one line per ignored vulnerability. 

Would you prefer it if we just logged the number of ignored vulnerabilities? Or do you think this is too verbose in general and not worth doing?

**Review by knqyf263 — APPROVED** [review]

**Comment by knqyf263** [comment]
I'm sorry for the late reply.

>one line per ignored vulnerability.

I'm still feeling like one line per an ignored vulnerability is too verbose.

>Would you prefer it if we just logged the number of ignored vulnerabilities?

On the other hand, only showing a number of ignored vulnerabilities may not be helpful enough for debugging. Therefore, I changed it to show ignored IDs on startup to take the middle.

If you still want to have one line message per each ignored vulnerability, you can open a new PR and continue to discuss it there. Thanks for the contribution!

**Comment by rethab** [comment]
Thanks for improving my changes and merging them, @knqyf263 . This is already a big improvement as far as I'm concerned, so I think this is fine for now.

Thanks again :)

**Pull request merged**
