### PR TITLE
fix(terraform): pass module outputs to other modules

### PR DESCRIPTION
**Pull request by nikpivkin**
## Related issues
- Close https://github.com/aquasecurity/trivy/issues/6274

## Checklist
- [ ] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [ ] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by fwereade** [comment]
FWIW: I think I've had good results from re-evaluating submodules when their inputs change. You can see the approach [here](https://github.com/aquasecurity/defsec/compare/v0.93.1...fwereade:defsec:submodule-re-eval-on-input-change) (against an old defsec which I currently depend on) – I think it currently evaluates modules-with-outputs one more time than it needs to, but the performance cost doesn't seem excessive and the strategy seems to align well with how the rest of the package works.

The specific test case I've been working against is [here](https://github.com/cloud-custodian/tfparse/pull/187/files#diff-b0e06ca99579a887b658dfcf76c55c3ebe17eec0fd3870b4d00f38bbd8d5cf5a); backporting the approach in this PR doesn't _appear_ to address that scenario, but that may be due to other changes since v0.93.1.

(I don't claim any particular expertise here, but I hope this is relevant/helpful. And I'd like to update the tfparse dependency to point at current code, but I can't commit to a timeframe for that.)

**Comment by nikpivkin** [comment]
Hi @fwereade !

**Comment by nikpivkin** [comment]
@fwereade Looks great! Do you mind if I open a PM with your changes or maybe you want to do it yourself?

**Comment by fwereade** [comment]
@nikpivkin thanks! please go ahead and open a PR, I can't promise when I'd get to it myself

FWIW, I think it _could_ use a little improvement: I'm pretty `lastInputs`/`lastOutputs` should be replaced with a `lastState` from `ctx.Get("module", name)` after setting the outputs (and the DeepEqual check against the same), so that a module with outputs doesn't misinterpret them as new inputs and re-eval; this would also render the extracted `GetInputVars` redundant

…but I'll leave it to your judgment :)

**Comment by nikpivkin** [comment]
Closed in favor of https://github.com/aquasecurity/trivy/pull/6411

**Pull request closed without merging**
