### PR TITLE
feat(db): append errors

### PR DESCRIPTION
**Pull request by knqyf263**
## Description
We should show the rate limit detail in the fatal error. Some users don't read log messages, and `--quiet` shows only a fatal log.

### Before

```
$ trivy image debian:12 --quiet
2024-10-31T14:09:06+04:00       FATAL   Fatal error     init error: DB error: failed to download vulnerability DB: OCI artifact error: failed to download vulnerability DB: failed to download artifact from any source
```

### After

```
$ trivy image debian:12 --quiet
2024-10-31T14:08:14+04:00       FATAL   Fatal error     init error: DB error: failed to download vulnerability DB: OCI artifact error: failed to download vulnerability DB: failed to download artifact from any source: 1 error occurred:
        * oci download error: failed to fetch the layer: GET https://ghcr.io/v2/aquasecurity/trivy-db/blobs/sha256:ba0d01953a8c28331552412292b72f3639b3962fe27f3359a51553a52d3f7b29: TOOMANYREQUESTS: retry-after: 947.147µs, allowed: 44000/minute
```

## Related discussions
- https://github.com/aquasecurity/trivy/discussions/7841

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [x] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by nikpivkin** [comment]
BTW,  errors can be joined together using the built-in function https://pkg.go.dev/errors@master#Join

**Review by DmitriyLewen — APPROVED** [review]
LGTM

**Comment by knqyf263** [comment]
>BTW, errors can be joined together using the built-in function https://pkg.go.dev/errors@master#Join

Yes, I prefer stdlib, and tried it in [several places](https://github.com/aquasecurity/trivy/blob/dc44946881a9d1c1ef4e655114e9691e828b810d/pkg/vex/repo/repo.go#L259). However, the formatted output is very unclear.
https://go.dev/play/p/AYls8a96t-j

Since this rate limit error is really important now, I'd go for go-multierror. We can probably add a new error package wrapping `errors.Join` to eliminate the go-multierror dependency, but i didn't have a chance to do that.

**Comment by knqyf263** [comment]
`joinError` is not exported. I have no idea how we can customize the output format.
https://github.com/golang/go/blob/6d39245514c675cdea5c7fd7f778e97bf0728dd5/src/errors/join.go#L40

**Pull request merged**
