### PR TITLE
docs: extend known plugins list

### PR DESCRIPTION
**Pull request by umax**
## Description

I have created Trivy plugin to convert JSON report into SonarQube [external issues format](https://docs.sonarqube.org/9.6/analyzing-source-code/importing-external-issues/generic-issue-import-format/). I believe it would be helpful for others. The more plugins included into the documentation, the more popular the tool and approach will be.

Thanks.

### CODE REVIEW

**Comment by knqyf263** [comment]
What if adding `Plugins` under `Ecosystem` and adding third-party plugins there? @itaysk @AnaisUrlichs 
https://aquasecurity.github.io/trivy/v0.35/ecosystem/

**Comment by itaysk** [comment]
agree. but I'm not sure under which category. maybe need to create a new one for integrations like this

**Comment by knqyf263** [comment]
>maybe need to create a new one for integrations like this

Like `Reporting`?

**Comment by itaysk** [comment]
I thought of a category like "security tools" or something like that, and we can add many other security tools like security automation tools, incident response tools, vulnerability management tools, etc. WDYT?

**Comment by knqyf263** [comment]
This plugin just converts JSON reports into the SonarQube external issues format. It is sort of a converter. Do you think it should be located in `Security Tools`? I don't have an opinion about that. You can decide it.

**Comment by itaysk** [comment]
@umax can you please add it to the Ecosystem section under a new `Security Management` category

**Comment by umax** [comment]
@itaysk sure, I will add.

**Comment by umax** [comment]
I will create new pull request with only my changes.

**Pull request closed without merging**
