### PR TITLE
Replace deprecated option in goreleaser

### PR DESCRIPTION
**Pull request by nilushancosta**
fixes https://github.com/aquasecurity/trivy/issues/1404

### CODE REVIEW

**Comment by nilushancosta** [comment]
Before the change
```
$ goreleaser release --rm-dist --skip-publish --skip-validate
   • releasing...
   • loading config file       file=goreleaser.yml
   • loading environment variables
   • getting and validating git state
      • building...               commit=07c9200eb7bc20b8f8b1d7ce44674060ca241358 latest tag=v0.21.0
      • pipe skipped              error=validation is disabled
   • parsing tag
   • setting defaults
      • snapshotting
      • scm releases
      • project name
      • loading go mod information
      • building binaries
      • universal binaries
      • creating source archive
      • archives
      • linux packages
      • snapcraft packages
      • calculating checksums
      • signing artifacts
      • signing docker images
      • docker images
            • DEPRECATED: `docker.use_buildx` should not be used anymore, check https://goreleaser.com/deprecations#dockerusebuildx for more info
            • DEPRECATED: `docker.use_buildx` should not be used anymore, check https://goreleaser.com/deprecations#dockerusebuildx for more info
      • docker manifests
      • artifactory
      • blobs
```

After the change
```
$ goreleaser release --rm-dist --skip-publish --skip-validate
   • releasing...
   • loading config file       file=goreleaser.yml
   • loading environment variables
   • getting and validating git state
      • building...               commit=79c171eeecfaccd5bb2b688319943ae896831d24 latest tag=v0.21.0
      • pipe skipped              error=validation is disabled
   • parsing tag
   • setting defaults
      • snapshotting
      • scm releases
      • project name
      • loading go mod information
      • building binaries
      • universal binaries
      • creating source archive
      • archives
      • linux packages
      • snapcraft packages
      • calculating checksums
      • signing artifacts
      • signing docker images
      • docker images
      • docker manifests
      • artifactory
      • blobs
```

**Comment by knqyf263** [comment]
We might need to bump up the version here.
https://github.com/aquasecurity/trivy/blob/07c9200eb7bc20b8f8b1d7ce44674060ca241358/.github/workflows/test.yaml#L78

The above version should  be the same here.
https://github.com/aquasecurity/trivy/blob/07c9200eb7bc20b8f8b1d7ce44674060ca241358/.github/workflows/release.yaml#L67

**Comment by krol3** [comment]
@nilushancosta We could use the commits instead of version for security reason about supply chain attack.

**Review by knqyf263 — APPROVED** [review]

**Comment by knqyf263** [comment]
Thanks!

**Pull request merged**
