### PR TITLE
docs(go): add stdlib

### PR DESCRIPTION
**Pull request by knqyf263**
## Description
Mention the stdlib support in Go binaries

## Related issues
- Close https://github.com/aquasecurity/trivy/issues/4133

## Related PRs
- [x] https://github.com/aquasecurity/trivy-db/pull/398
- [x] https://github.com/aquasecurity/trivy/pull/6277

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [x] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by DmitriyLewen** [comment]
@knqyf263 Can you add info about govuln-db in [data sources](https://aquasecurity.github.io/trivy/v0.50/docs/scanner/vulnerability/#data-sources_1)?

**Comment by knqyf263** [comment]
Nice catch. Added https://github.com/aquasecurity/trivy/pull/6580/commits/78104aecf2fa09253ff906f6c6e5c25649cc0d44

**Comment by DmitriyLewen** [comment]
I one more idea - what if we will add note that ghsa - for dependency vulns,  govuln-db for runtime?

**Comment by knqyf263** [comment]
Since it's a detail, I added it to the golang page.
https://github.com/aquasecurity/trivy/pull/6580/commits/ebf85ee67c7c2575d3e47437955dbb3378b5b42b

**Review by DmitriyLewen — APPROVED** [review]

**Pull request merged**
