### PR TITLE
Resolves #491 - Added capability to filter data sources.

### LINKED ISSUE #491: Non-commercial vs commercial usage: which data sources?
The README says some of the data sources are only licensed for non-commercial usage. It's difficult for me as a potential user to tell whether I can or cannot use trivy in a particular scenario.

It would be useful to have:

1. A flag that disables sources that are non-commercial-use-only.
2. Documentation of which sources are non-commercial-use-only, and the impact of the flag if it's implemented.

Thank you!

### PR DESCRIPTION
**Pull request by liorkesten**
Fix [ISSUE 491](https://github.com/aquasecurity/trivy/issues/491)
Add capabillity to filter data sources.
Data sources should be mentiond in the .trivyignore file in the following format:

SeveritySource: python-safety-db

### CODE REVIEW

**Comment by liorkesten** [comment]
Hey @knqyf263,
Did I miss anything in the PR?

Since this is my first PR, the workflow won't run until it has been reviewed

**Comment by knqyf263** [comment]
Hi @liorkesten, thanks for your contribution, but we plan to remove python-safety-db shortly.

**Comment by liorkesten** [comment]
@knqyf263  thank you for your quick response.
I still think that it might be a useful enhancement for future non-commercial feeds.
What do you think?

**Comment by knqyf263** [comment]
We will not have any non-commercial feeds.

**Comment by liorkesten** [comment]
Thank you @knqyf263 for the update.
I will close the PR.

**Comment by knqyf263** [comment]
I'm sorry we cannot merge your PR, but thanks again!

**Comment by liorkesten-msft** [comment]
It's okay!
When is the timeline for the removal of the non commercial feeds (safety python)?

**Comment by knqyf263** [comment]
I hope it will happen in a few months.

**Comment by liorkesten** [comment]
So is it possible to merge this PR and then deprecate this filter after you remove those feeds?

It seems that we can use the TrivyIgnore file to filter more records other than misconfigurations and vulnerabilities, and this feature would make this possible.

Further, if I want to use Trivy for commercial purposes, I will need to filter the results on my end.

**Comment by knqyf263** [comment]
I'm sorry, but we don't want to make Trivy bigger for commercial purposes. Please be patient for a few months.

**Comment by liorkesten** [comment]
Okay, thank you for the quick response.

**Pull request closed without merging**
