### PR TITLE
fix: Omit Remediation if PrimaryURL is empty

### LINKED ISSUE #1999: `asff.tpl`: empty `.PrimaryURL` breaks import to Security Hub
The ASFF spec states that the `Remediation` field [is optional](https://docs.aws.amazon.com/securityhub/latest/userguide/asff-top-level-attributes.html#:~:text=AcmeNerfHerder%2D111111111111%2Dx189dx7824%22%20%7D%0A%5D-,Remediation,-Optional).  However if the field is included, even though `Remediation.Recommendation`, `Remediation.Recommendation.Text`, and `Remediation.Recommendation.Url` are [all optional](https://docs.aws.amazon.com/securityhub/latest/userguide/asff-remediation.html#asff-remediation-recommendation), the API will fail to validate a case where `Remediation.Recommendation.Url` is included, but empty, as in: 
```json
    "Remediation": {
      "Recommendation": {
        "Text": "More information on this vulnerability is provided in the hyperlink",
        "Url": ""
      }
    },
```
with the error
```
{
    "Id": "{id}",
    "ErrorCode": "InvalidInput",
    "ErrorMessage": "Finding does not adhere to Amazon Finding Format. data.Remediation.Recommendation.Url should NOT be shorter than 1 characters, data.Remediation.Recommendation.Url should match format \"uri\"."
},
```
This invalid ASFF will be generated by `asff.tpl` when the `.PrimaryURL` is empty. 
https://github.com/aquasecurity/trivy/blob/d786655a18a591bd254c2d11d10ec692943c6a78/contrib/asff.tpl#L38-L43
It makes sense to me to omit the entire `Remediation` field (since it's optional) if there's an empty `.PrimaryURL`, as in:
```tpl
        {{ if not (empty .PrimaryURL) -}}
            "Remediation": {
                "Recommendation": {
                    "Text": "More information on this vulnerability is provided in the hyperlink",
                    "Url": "{{ .PrimaryURL }}"
                }
            },
        {{ end -}}
```
If you agree, I'd be happy to open a PR for the change.

### PR DESCRIPTION
**Pull request by ben-harvey**
## Description
This change omits the `Recommendation` field if the `PrimaryURL` is empty, since the Security Hub API fails import if the `Recommendation.Remediation.Url` field is empty.  Please see the related issue for more context. 

Testing: 
The existing integration test case doesn't exercise this change, and I didn't see a simple way to update the `PrimaryURL` of the test image in order to do so (I'm open to feedback on this point).  However, I have tested this change manually by:
- running Trivy and generating ASFF that has an empty `PrimaryURL` (using a local copy of the template)
- encountering the ASFF import error with the Security Hub API
- updating the local copy of the template with this change
- seeing the ASFF import succeed

## Related issues
- [Close #1999](https://github.com/aquasecurity/trivy/issues/1999)

## Checklist
- [x] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy/blob/main/CONTRIBUTING.md) to this repository.
- [x] I've followed the [conventions](https://github.com/aquasecurity/trivy/blob/main/CONTRIBUTING.md#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by knqyf263** [comment]
@afdesk Could you review it?

**Comment by knqyf263** [comment]
@afdesk ping

**Comment by afdesk** [comment]
oh, sorry. missed this PR

**Review by afdesk — APPROVED** [review]
I don't think, that trivy db contains an advisory without such URL, but this PR looks good!
thanks!

**Review by knqyf263 — APPROVED** [review]

**Pull request merged**
