### PR TITLE
Reverting fix for issue #570

### PR DESCRIPTION
**Pull request by rahul2393**
[issue](https://github.com/aquasecurity/trivy/issues/580)

### CODE REVIEW

**Comment by rahul2393** [comment]
@knqyf263 @simar7 please help review

**Comment by knqyf263** [comment]
@NasAmin Does it work in your environment after this change? I'm still trying to replicate the issue...

**Comment by NasAmin** [comment]
@knqyf263 Not sure how to test, has the docker image from this PR been published so I can pull it?

**Comment by rahul2393** [comment]
@NasAmin I have pushed custom image here rahul23/trivy using this commit's dockerfile

**Comment by NasAmin** [comment]
@rahul2393 Just tried and unfortunately it fails with the same error without using `-u 0`
If I use `-u 0` then it works.
I am getting this error without using `-u 0`

```
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $PWD:/tmp/.cache/ rahul23/trivy --light myimage:local
2020-07-30T18:40:37.642Z        INFO    Need to update DB
2020-07-30T18:40:37.642Z        INFO    Downloading DB...
46.94 KiB / 4.44 MiB [>______________________________________________________________] 1.03% ? p/s ?263.94 KiB / 4.44 MiB [--->__________________________________________________________] 5.81% ? p/s ?552.94 KiB / 4.44 MiB [------->_____________________________________________________] 12.17% ? p/s ?552.94 KiB / 4.44 MiB [----->_________________________________________] 12.17% 843.39 KiB p/s ETA 4s1.30 MiB / 4.44 MiB [-------------->__________________________________] 29.39% 843.39 KiB p/s ETA 3s1.48 MiB / 4.44 MiB [---------------->________________________________] 33.40% 843.39 KiB p/s ETA 3s1.90 MiB / 4.44 MiB [--------------------->___________________________] 42.86% 938.64 KiB p/s ETA 2s2.05 MiB / 4.44 MiB [---------------------->__________________________] 46.21% 938.64 KiB p/s ETA 2s2.05 MiB / 4.44 MiB [---------------------->__________________________] 46.21% 938.64 KiB p/s ETA 2s2.22 MiB / 4.44 MiB [------------------------>________________________] 49.97% 912.86 KiB p/s ETA 2s2.48 MiB / 4.44 MiB [--------------------------->_____________________] 55.96% 912.86 KiB p/s ETA 2s2.73 MiB / 4.44 MiB [------------------------------>__________________] 61.57% 912.86 KiB p/s ETA 1s2.96 MiB / 4.44 MiB [-------------------------------->________________] 66.81% 936.21 KiB p/s ETA 1s3.08 MiB / 4.44 MiB [---------------------------------->______________] 69.43% 936.21 KiB p/s ETA 1s3.31 MiB / 4.44 MiB [------------------------------------>____________] 74.67% 936.21 KiB p/s ETA 1s3.56 MiB / 4.44 MiB [--------------------------------------->_________] 80.29% 941.63 KiB p/s ETA 0s3.83 MiB / 4.44 MiB [------------------------------------------>______] 86.27% 941.63 KiB p/s ETA 0s4.11 MiB / 4.44 MiB [--------------------------------------------->___] 92.64% 941.63 KiB p/s ETA 0s4.28 MiB / 4.44 MiB [----------------------------------------------->_] 96.38% 959.50 KiB p/s ETA 0s4.42 MiB / 4.44 MiB [------------------------------------------------>] 99.75% 959.50 KiB p/s ETA 0s4.44 MiB / 4.44 MiB [------------------------------------------------------] 100.00% 1.15 MiB p/s 4s2020-07-30T18:40:48.256Z    FATAL   unable to initialize a scanner: unable to initialize a docker scanner: 2 errors occurred:
        * unable to inspect the image (index.docker.io/library/tenancyadmin:local): Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/index.docker.io/library/tenancyadmin:local/json": dial unix /var/run/docker.sock: connect: permission denied
        * GET https://index.docker.io/v2/library/tenancyadmin/manifests/local: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/tenancyadmin Type:repository]]
```

I am using WSL 2 with Ubuntu 20.04.

**Pull request merged**
