### PR TITLE
docs: add VEX CLI references

### PR DESCRIPTION
**Pull request by nikpivkin**
## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [x] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by nikpivkin** [comment]
Interesting, I saw a warning about the absence of these pages.

**Comment by DmitriyLewen** [comment]
`main` branch contains these pages - https://github.com/aquasecurity/trivy/blob/b3ee6dac269bd7847674f3ce985a5ff7f8f0ba38/mkdocs.yml#L185-L189

**Comment by nikpivkin** [comment]
My fault, forgot to pull the latest changes

**Comment by DmitriyLewen** [comment]
More inI wonder why GitHub didn't show the conflict

**Pull request closed without merging**
