### PR TITLE
refactor for newest fanal

### PR DESCRIPTION
**Pull request by jabielecki**
Changes for compatilibity with refactoring aquasecurity/fanal#47

Signed-off-by: Jakub Bielecki <jakub.bielecki@codilime.com>

### CODE REVIEW

**Comment by jabielecki** [comment]
Summon @simar7

**Comment by jabielecki** [comment]
Summon @knqyf263

**Comment by knqyf263** [comment]
@jabielecki Thanks. Would you fix the conflict? I'm sorry, but I updated master a lot.

**Comment by knqyf263** [comment]
@jabielecki The conflict is my fault. Let me fix it, please.

**Comment by knqyf263** [comment]
@jabielecki Many Thanks😆

**Pull request merged**
