### PR TITLE
fix(go): Do not trim v prefix from versions in Go Mod Analyzer

### LINKED ISSUE #7711: fix(golang): do not trim `v` prefix from versions
## Description
[the go mod analyzer](https://github.com/aquasecurity/trivy/blob/2d80769c34b118851640411fff9dac0b3e353e82/pkg/dependency/parser/golang/mod/parse.go#L103) should not remove the `v` prefix from versions to get aligned with [the go binary analyzer](https://github.com/aquasecurity/trivy/blob/9b31697274c8743d6e5a8f7a1a05daf60cd15910/pkg/dependency/parser/golang/binary/parse.go).

### Discussed in https://github.com/aquasecurity/trivy/discussions/7709

### PR DESCRIPTION
**Pull request by Rutam21**
## Description

This PR modifies the Go Mod Analyzer file so that the prefix "v" is not trimmed from the versions to maintain consistency with the Go Binary Analyzer.

## Related issues
- Close #7711 

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.

### CODE REVIEW

**Review by DmitriyLewen — CHANGES_REQUESTED** [review]
Hello @Rutam21 
Thanks for your work!

can you update tests too?

Regards, Dmitriy

**Comment by Rutam21** [comment]
Hello @DmitriyLewen, I have added the v prefix to the version numbers in the test and test-cases file for the Go Mod Analyzer so that it matches the required versioning format. Please review and suggest changes, if any. Thanks.

**Comment by DmitriyLewen** [comment]
You also need to update [integration](https://github.com/aquasecurity/trivy/actions/runs/11332735389/job/31535485265) and [k8s](https://github.com/aquasecurity/trivy/actions/runs/11332735389/job/31535485582) tests.
` mage test:updateGolden` command should help

**Comment by Rutam21** [comment]
@DmitriyLewen I tried running that command but it always errors out. Any suggestions on this?

```
go: downloading github.com/vmihailenco/msgpack/v5 v5.3.5
go: downloading github.com/dsnet/compress v0.0.1
go: downloading sigs.k8s.io/yaml v1.4.0
go: creating work dir: mkdir /tmp/go-build220524866: no space left on device
Error: running "go test -tags=integration ./integration/... ./pkg/fanal/test/integration/... -update" failed with exit code 1
```

**Comment by knqyf263** [comment]
@Rutam21 You don't have enough disk space.

>go: creating work dir: mkdir /tmp/go-build220524866: no space left on device

If you have more space in another directory, you can specify it like `TMPDIR=/path/to/another-dir`.

**Comment by knqyf263** [comment]
@Rutam21 Do you have time to wrap it up? We want to include this fix in [v0.57.0](https://github.com/aquasecurity/trivy/milestone/39). If you're busy, we can take care of it.

**Comment by DmitriyLewen** [comment]
@Rutam21 don't worry i updated golden files

@knqyf263 when I updated the gold files - I thought - do we need to update the docs/other tests?
e.g. :
-  https://aquasecurity.github.io/trivy/v0.56/docs/supply-chain/vex/file/#applying-vex-to-dependency-trees
- https://github.com/aquasecurity/trivy/blob/4a2f492c6e685ff577fb96a7006cd0c43755baf4/pkg/sbom/io/encode_test.go#L561-L586

**Comment by DmitriyLewen** [comment]
@knqyf263 I updated testcases and docs.
I didn't update [rekor tests](https://github.com/aquasecurity/trivy/blob/db68d106ce9aa7368ae453592ed54c153b29a579/pkg/rekortest/server.go#L219-L231) (it requires regenerating the digest, so I think we can skip the changes since it's not worth the time)

Also we need to update [k8s scanner package](https://github.com/aquasecurity/trivy/blob/010b2138067184114a882d3b5d86e2f556f4355c/pkg/k8s/scanner/scanner.go) to add `v` prefix, but i think that should be done in a separate PR.

> So, I think we want to add the v prefix for consistency.

Done in https://github.com/aquasecurity/trivy/pull/7733/commits/d5a787b632911bc565dc54321deccb825ee5d8c8

**Comment by knqyf263** [comment]
Thanks. GitHub Actions is [down](https://github.com/orgs/community/discussions/143045) now. We'll merge this PR after it's back.

**Review by knqyf263 — APPROVED** [review]

**Comment by DmitriyLewen** [comment]
@knqyf263 We don't add `v` prefix for `stdlib` of `gobinaries`.
I added it in - https://github.com/aquasecurity/trivy/pull/7733/commits/5b5b7f884c3e0d6ebb90a997d4a8b8e90c6f6cff

Take a look, please.


I also created #7822 for `k8s scanner`

**Comment by knqyf263** [comment]
Failing?

**Comment by DmitriyLewen** [comment]
Rebased this PR.
Tests now pass.

**Comment by knqyf263** [comment]
@DmitriyLewen You requested changes before. Your review is blocking this PR.

**Review by DmitriyLewen — APPROVED** [review]

**Comment by DmitriyLewen** [comment]
Approved

**Pull request merged**
