### PR TITLE
Resolves #1472 Add Prisma Cloud/Twistlock output template

### LINKED ISSUE #1472: Add Twistlock output compatibility
Create a template for the contrib/ directory that writes Trivy output using a subset of the Twistlock JSON format documented [here](https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-compute/tools/twistcli_scan_images)

### PR DESCRIPTION
**Pull request by corey-cole**
This template outputs Trivy scan results under the results.vulnerabilities[] and results.vulnerabilityDistribution stanzas output by the Twistlock twistcli command.

Close https://github.com/aquasecurity/trivy/issues/1472

### CODE REVIEW

**Comment by knqyf263** [comment]
Hi, thanks for your contribution. I'm simply curious why you want to support the Twistlock JSON. Looks like Twistlock uses twistcli for scanning.

**Comment by corey-cole** [comment]
The purpose behind contributing this is to enable the use of trivy to simulate twistcli.  Twistcli doesn't work in disconnected mode and my CI/CD system for developing automation doesn't have access to the Prisma instance that I use in application CI/CD.  I thought others might have similar issues and be able to make use of this template.

**Comment by knqyf263** [comment]
I understand. Thanks for your clarification. 

It is hard for us to maintain this template since we don't have Prisma Cloud environment. If you can maintain it, you can publish it in your repository and our documentation can refer to that.
https://aquasecurity.github.io/trivy/v0.21.2/advanced/community/tools/

**Comment by knqyf263** [comment]
We're so sorry, but please let me close this PR. Thanks for the contribution again. Please keep in mind that we can refer to your template in our doc.

**Pull request closed without merging**
