### PR TITLE
GitLab CI integration documentation

### PR DESCRIPTION
**Pull request by thiago-gitlab**
This is a suggestion to use the native integration, which is a lot simpler than the custom configurations currently recommended in the [documentation](https://aquasecurity.github.io/trivy/v0.19.2/advanced/integrations/gitlab-ci/).

I considered removing them altogether but thought it was best to let a maintainer weight-in before doing so.

### CODE REVIEW

**Comment by thiago-gitlab** [comment]
@knqyf263, could you please let me know your thoughts on this?

**Comment by knqyf263** [comment]
@thiago-gitlab Thanks! Is it possible to use the integration for free? I thought the feature was provided only for ultimate users.

**Comment by thiago-gitlab** [comment]
@knqyf263 🤦🏽‍♂️ of course! It *is* an ultimate feature :(. I'm sorry about missing that!

While the feature check is in the template itself (`$GITLAB_FEATURES =~ /\bcontainer_scanning\b/`) and can be easily removed, we might decide to move the check into the analyzer image, so it's definitely not safe to recommend this approach.

I've adjusted my suggestion to account for this. My intent is not to use Trivy's docs to upsell GitLab, so please feel free to close this MR if you think the information is not useful to Trivy users.

**Review by knqyf263 — APPROVED** [review]
Good to know the GitLab Ultimate feature even for OSS users.

**Pull request merged**
