### PR TITLE
fix: add fingerprint option to codequality template

### PR DESCRIPTION
**Pull request by Jasstkn**
Hi.
This PR adds a [required field](https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html#implementing-a-custom-tool) for gitlab codequality template. Without this field in the Gitlab UI it shows no changes while the information is generated correctly.

Connected issue #1540
Signed-off-by: Jasstkn <mariia.kotliarevskaia@gmail.com>

### CODE REVIEW

**Review by krol3 — APPROVED** [review]
LGTM

**Comment by Jasstkn** [comment]
> LGTM

Hi. Could you advice how to fix failed test? 
Looks like I should add the field `fingerprint` and the correspondent result of sha1sum to the file https://github.com/bmagistro/trivy/blob/341f9a8e161fd9015e0865a224cab4e17a262912/integration/testdata/alpine-310.gitlab-codequality.golden?

But I'm not sure what is the right way to do so.

**Comment by afdesk** [comment]
@Jasstkn thanks for your contribution!
it seems you need to update file [integration/testdata/alpine-310.gitlab-codequality.golden](https://github.com/aquasecurity/trivy/blob/main/integration/testdata/alpine-310.gitlab-codequality.golden).

There is a way to set `update` flag for integration tests to **true** here: [integration/integration_test.go](https://github.com/aquasecurity/trivy/blob/2ee074568cb2b3a351f7d38743e33be831a5c2c0/integration/integration_test.go#L24) and run
```sh
$ make test-integration
```
but this action can change something else, I'd not change other files and would retest after setting `update` to **false**

**Comment by Jasstkn** [comment]
> @Jasstkn thanks for your contribution! it seems you need to update file [integration/testdata/alpine-310.gitlab-codequality.golden](https://github.com/aquasecurity/trivy/blob/main/integration/testdata/alpine-310.gitlab-codequality.golden).
> 
> There is a way to set `update` flag for integration tests to **true** here: [integration/integration_test.go](https://github.com/aquasecurity/trivy/blob/2ee074568cb2b3a351f7d38743e33be831a5c2c0/integration/integration_test.go#L24) and run
> 
> ```shell
> $ make test-integration
> ```
> 
> but this action can change something else, I'd not change other files and would retest after setting `update` to **false**

Could you please allow tests to run?

**Comment by Jasstkn** [comment]
@afdesk tests are green now. Thanks for your assistance 🎉

**Comment by knqyf263** [comment]
Thanks for the contribution!

**Pull request merged**
