### PR TITLE
feat(aws): apply filter options to result

### PR DESCRIPTION
**Pull request by nikpivkin**
## Related issues
- Close https://github.com/aquasecurity/trivy/issues/5879

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Review by simar7 — APPROVED** [review]
nice!

**Comment by simar7** [comment]
we'll merge once the patch release is out, so v0.51.0 I believe.

**Comment by itaysk** [comment]
don't we need to update the docs?

**Comment by nikpivkin** [comment]
@itaysk Result filtering is [documented](https://aquasecurity.github.io/trivy/v0.50/docs/configuration/filtering/), but it was not applied to AWS Cloud scan results

**Comment by nikpivkin** [comment]
@itaysk Do you mean we need to add filtering support information for AWS scan results [here](https://aquasecurity.github.io/trivy/v0.50/docs/target/aws/)? AWS scanning refers to finding misconfigurations, and [this ](https://aquasecurity.github.io/trivy/v0.50/docs/configuration/filtering/)page states that misconfigurations are supported.

**Comment by itaysk** [comment]
ok, so if the documentation already indicated that it is supported, then it should be a bug not a feature.

are there any other cases where the availability of a feature is dependent on the target being scanned? if so, perhaps it worth adding the target matrix to the docs, or better to support all targets

**Comment by nikpivkin** [comment]
@itaysk I'll check it out.

**Comment by simar7** [comment]
> ok, so if the documentation already indicated that it is supported, then it should be a bug not a feature.
> 
> are there any other cases where the availability of a feature is dependent on the target being scanned? if so, perhaps it worth adding the target matrix to the docs, or better to support all targets

It's here https://aquasecurity.github.io/trivy/v0.50/docs/configuration/filtering/#by-finding-ids

**Pull request merged**
