### PR TITLE
refactor: use debug message for post-analyze errors

### LINKED ISSUE #3869: Ignore Invalid Zip Files
Would it be possible to add an option that tells trivy to log and ignore any file that looks like a zip file but is not instead of ending the scan with an error?

### LINKED ISSUE #3885: Trivy breaks when it encounters a license file with an invalid extension
## Description

Trivy breaks when it encounters a license file with an invalid extension. The file should have the extension .txt but instead has the extension .jar, although it is still a text file. 

## What did you expect to happen?

I expected Trivy to scan the container image successfully and print a warning instead of failing.

## What happened instead?

Trivy fails and shows the next error:

```
2023-03-22T16:03:43.230+0100    FATAL   image scan error: scan error: scan failed: failed analysis: analyze error: failed to analyze layer (sha256:08000f09d6ffa7f2cdd654e0fc0ce14de861e02bd96c5cb9f4a3bdf6e49d6df4): post analysis error: post analysis error: walk dir error: on file: "opt/bitnami/ksql/share/doc/kafka/licenses/LICENSE-scala-java8-compat_2.12-0.9.0.jar" parse error: zip error: zip: not a valid zip file
```

## Output of run with `-debug`:

```
$ trivy image --format spdx-json ??? -d                                                                                                                                                                                                                                                                                
2023-03-22T15:59:21.803+0100    DEBUG   ["cyclonedx" "spdx" "spdx-json" "github"] automatically enables '--list-all-pkgs'.                                                                                                                                                        
2023-03-22T15:59:21.803+0100    DEBUG   Severities: ["UNKNOWN" "LOW" "MEDIUM" "HIGH" "CRITICAL"]                                                                                                                                                                                  
2023-03-22T15:59:21.804+0100    INFO    "--format spdx" and "--format spdx-json" disable security scanning                                                                                                                                                                        
2023-03-22T15:59:21.805+0100    DEBUG   cache dir:  /home/fjavier/.cache/trivy                                                                                                                                                                                                    
2023-03-22T15:59:21.808+0100    DEBUG   Image ID: sha256:62d97294443370c5de8022338d5ed72e6313026f229eac5e175c0638ffba85b2                                                                                                                                                         
2023-03-22T15:59:21.808+0100    DEBUG   Diff IDs: [sha256:ce348ddc720b9686151c0d149495b9ec9e832740d1e0e6d1b52469461873c913 sha256:98b864ea40aa8d6b4eea0371e26b188cd53ec626c620f7c28972f8472fe97944 sha256:9a9bb5bdfef5299566c13f92c67b10ee5af0ec373c9331be113ded3d2c6bafc6 sha256:
08000f09d6ffa7f2cdd654e0fc0ce14de861e02bd96c5cb9f4a3bdf6e49d6df4 sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef sha256:25ab344a77edfa83f1157bbae4438792227bad6ffb44ae77be1d48f698
cf16c5 sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef sha256:27ab94951f28adf490b60bdfa13fd45f62a18c443e3fef6c9935096f992710bb]                                                                                                                           
2023-03-22T15:59:21.808+0100    DEBUG   Base Layers: []                                                                                                                                                                                                                           
2023-03-22T15:59:21.812+0100    DEBUG   Missing image ID in cache: sha256:62d97294443370c5de8022338d5ed72e6313026f229eac5e175c0638ffba85b2                                                                                                                                        
2023-03-22T15:59:21.812+0100    DEBUG   Missing diff ID in cache: sha256:08000f09d6ffa7f2cdd654e0fc0ce14de861e02bd96c5cb9f4a3bdf6e49d6df4   
2023-03-22T15:59:45.223+0100    INFO    JAR files found                                                                                                                                                                                                                    [27/43]
2023-03-22T15:59:45.224+0100    INFO    Analyzing JAR files takes a while...                                                                                                                                                                                                      
2023-03-22T15:59:45.224+0100    DEBUG   Parsing Java artifacts...       {"file": "opt/bitnami/java/lib/jrt-fs.jar"}                                                                                                                                                               
2023-03-22T15:59:45.224+0100    DEBUG   Parsing Java artifacts...       {"file": "opt/bitnami/ksql/share/java/confluent-common/build-tools-7.2.4.jar"}                                                                                                                            
2023-03-22T15:59:45.224+0100    DEBUG   Parsing Java artifacts...       {"file": "opt/bitnami/ksql/share/java/acl/acl-7.2.4.jar"}                                                                                                                                                 
2023-03-22T15:59:45.224+0100    DEBUG   Parsing Java artifacts...       {"file": "opt/bitnami/ksql/share/filestream-connectors/connect-file-7.2.4-ce.jar"}                                                                                                                        
2023-03-22T15:59:45.224+0100    DEBUG   Parsing Java artifacts...       {"file": "opt/bitnami/ksql/share/doc/kafka/licenses/LICENSE-scala-java8-compat_2.12-0.9.0.jar"}                                                                                                           
2023-03-22T15:59:45.224+0100    DEBUG   Parsing Java artifacts...       {"file": "opt/bitnami/ksql/share/java/confluent-common/common-metrics-7.2.4.jar"}                                                                                                                         
2023-03-22T15:59:45.224+0100    DEBUG   Parsing Java artifacts...       {"file": "opt/bitnami/ksql/share/java/confluent-common/common-utils-7.2.4.jar"}                                                                                                                           
2023-03-22T15:59:45.224+0100    DEBUG   Parsing Java artifacts...       {"file": "opt/bitnami/ksql/share/java/confluent-common/common-config-7.2.4.jar"}                                                                                                                          
2023-03-22T15:59:45.224+0100    DEBUG   Parsing Java artifacts...       {"file": "opt/bitnami/ksql/share/java/confluent-common/slf4j-api-1.7.36.jar"}                                                                                                                             
2023-03-22T15:59:45.225+0100    DEBUG   No such POM in the central repositories {"file": "connect-file-7.2.4-ce.jar"}                                                                                                                                                             
2023-03-22T15:59:45.225+0100    DEBUG   Parsing Java artifacts...       {"file": "opt/bitnami/ksql/share/java/confluent-control-center/HdrHistogram-2.1.12.jar"}                                                                                                                  
2023-03-22T15:59:45.225+0100    DEBUG   No such POM in the central repositories {"file": "jrt-fs.jar"}                                                                                                                                                                            
2023-03-22T15:59:45.226+0100    DEBUG   POM was determined in a heuristic way   {"file": "connect-file-7.2.4-ce.jar", "artifact": "org.apache.kafka:connect-file:7.2.4-ce"}
2023-03-22T15:59:46.033+0100    FATAL   image scan error:                                                                                
    github.com/aquasecurity/trivy/pkg/commands/artifact.Run                                                                              
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:427
  - scan error:                                         
    github.com/aquasecurity/trivy/pkg/commands/artifact.(*runner).scanArtifact
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:266                                
  - scan failed:                                                                                                                         
    github.com/aquasecurity/trivy/pkg/commands/artifact.scan                                                                             
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:668
  - failed analysis:                                                                                                                     
    github.com/aquasecurity/trivy/pkg/scanner.Scanner.ScanArtifact                                                                       
        /home/runner/work/trivy/trivy/pkg/scanner/scan.go:146
  - analyze error:
    github.com/aquasecurity/trivy/pkg/fanal/artifact/image.Artifact.Inspect
        /home/runner/work/trivy/trivy/pkg/fanal/artifact/image/image.go:139
  - failed to analyze layer (sha256:08000f09d6ffa7f2cdd654e0fc0ce14de861e02bd96c5cb9f4a3bdf6e49d6df4):
    github.com/aquasecurity/trivy/pkg/fanal/artifact/image.Artifact.inspect.func1
        /home/runner/work/trivy/trivy/pkg/fanal/artifact/image/image.go:242
  - post analysis error:
    github.com/aquasecurity/trivy/pkg/fanal/artifact/image.Artifact.inspectLayer
        /home/runner/work/trivy/trivy/pkg/fanal/artifact/image/image.go:320
  - post analysis error:
    github.com/aquasecurity/trivy/pkg/fanal/analyzer.AnalyzerGroup.PostAnalyze
        /home/runner/work/trivy/trivy/pkg/fanal/analyzer/analyzer.go:486
  - walk dir error:
    github.com/aquasecurity/trivy/pkg/fanal/analyzer/language/java/jar.(*javaLibraryAnalyzer).PostAnalyze
        /home/runner/work/trivy/trivy/pkg/fanal/analyzer/language/java/jar/jar.go:91
  - on file:
    github.com/aquasecurity/trivy/pkg/parallel.walk[...]
        /home/runner/work/trivy/trivy/pkg/parallel/walk.go:107
  - "opt/bitnami/ksql/share/doc/kafka/licenses/LICENSE-scala-java8-compat_2.12-0.9.0.jar" parse error:
    github.com/aquasecurity/trivy/pkg/fanal/analyzer/language/java/jar.(*javaLibraryAnalyzer).PostAnalyze.func2
        /home/runner/work/trivy/trivy/pkg/fanal/analyzer/language/java/jar/jar.go:75
  - zip error:
    github.com/aquasecurity/go-dep-parser/pkg/java/jar.(*Parser).parseArtifact
        /home/runner/go/pkg/mod/github.com/aquasecurity/go-dep-parser@v0.0.0-20230309121549-fcc0deb06781/pkg/java/jar/parse.go:82
  - zip: not a valid zip file
```

## Output of `trivy -v`:

```
Version: 0.38.3
Vulnerability DB:
  Version: 2
  UpdatedAt: 2023-03-20 12:08:42.807958363 +0000 UTC
  NextUpdate: 2023-03-20 18:08:42.807957763 +0000 UTC
  DownloadedAt: 2023-03-20 14:14:15.681424518 +0000 UTC

```

## Additional details (base image name, container registry info...):

### PR DESCRIPTION
**Pull request by DmitriyLewen**
## Description
Use debug message for post-analyze errors as for [AnalyzeFile](https://github.com/aquasecurity/trivy/blob/707ea94234925f8ac60ca25a02e2a3345a0eeb84/pkg/fanal/analyzer/analyzer.go#L447-L448).

## Related issues
- Close #3869
- Close #3885

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by knqyf263** [comment]
After retaking a look at this PR, another concern came to my mind. What if there are 100 valid JAR files and one broken JAR file? Do we not show 100 valid JAR files now?

**Comment by DmitriyLewen** [comment]
@knqyf263  hm... you are right. I will try to fix this.

**Comment by DmitriyLewen** [comment]
@knqyf263 
I added changes. Take a look, when you have time, please

**Comment by beltran-rubo** [comment]
Any progress or ETA for this one? Thanks

**Review by knqyf263 — APPROVED** [review]

**Comment by knqyf263** [comment]
Will be included in v0.41.0

**Pull request merged**
