### PR TITLE
docs(vuln): Document inline vulnerability filtering comments

### LINKED ISSUE #4023: trivy should document all of the Vulnerability Filtering options, including inline comments
Trivy doesn't currently comprehensively document all of the vulnerability filtering options, notably inline filtering.

Trivy should document some of the inline filtering possibilities and requirements in the filtering examples page (docs/docs/vulnerability/examples/filter.md)

### PR DESCRIPTION
**Pull request by jof**
## Description
Document inline vulnerability filtering comments. I use and love this feature, and couldn't find it in the docs, so here is a little blurb about it.

## Related issues
- Close #4023

## Checklist
- [X] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [X] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [X] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).

### CODE REVIEW

**Comment by itaysk** [comment]
@AnaisUrlichs can you PTAL?

**Comment by knqyf263** [comment]
Hi @jof, we recently restructured the document so that options can be in a single place. Could you update this PR accordingly?
https://github.com/aquasecurity/trivy/blob/57bb77c060afcf93e7952867af5922783dc1e55e/docs/docs/configuration/filtering.md

**Comment by jof** [comment]
A git rebase delightfully moved my patch to the renamed file. Updated.

**Review by knqyf263 — APPROVED** [review]

**Comment by knqyf263** [comment]
>A git rebase delightfully moved my patch to the renamed file. Updated.

Smart! Thanks for updating.

I've added a table as this filtering is dedicated to misconfiguration.
https://github.com/aquasecurity/trivy/pull/4024/commits/07bb6e5320d199a970e5c3e46244db9bed630403

**Pull request merged**
