### PR TITLE
Add image subcommand

### PR DESCRIPTION
**Pull request by simar7**
This will add a new `image` subcommand to Trivy.

Usage:
```
$ trivy image <imagename>
```

It maintains backwards compatibility with the `trivy <imagename>` command.

Signed-off-by: Simarpreet Singh <simar@linux.com>

### CODE REVIEW

**Comment by simar7** [comment]
@knqyf263 I'm thinking we should change the usage a bit to make these subcommands visible. So for instance currently it reads:

**Current**
```
./trivy --help
NAME:
  trivy - A simple and comprehensive vulnerability scanner for containers
USAGE:
  trivy [options] image_name
VERSION:
  v0.7.0-3-g47b09a3

[...other options here...]

```

But I think it's better to have no defined help template and use the default one, like this:

**New**
```
$ ./trivy --help
NAME:
   trivy - A simple and comprehensive vulnerability scanner for containers

USAGE:
   trivy [global options] command [command options] image_name

VERSION:
   v0.7.0-3-g47b09a3

COMMANDS:
   client, c  client mode
   server, s  server mode
   image, i   scan an image with trivy
   help, h    Shows a list of commands or help for one command

[...other options here...]
```

What do you think?

**Comment by knqyf263** [comment]
@simar7 I agree with you. Trivy didn't have sub commands before, so I wanted to suppress `global options` with help template, but we have sub commands now. As you said, we should change it.

**Comment by knqyf263** [comment]
Ah, but I found a problem. The options for image scan look like global options.

```
NAME:
   trivy - A simple and comprehensive vulnerability scanner for containers

USAGE:
   main [global options] command [command options] image_name

VERSION:
   dev

COMMANDS:
   client, c  client mode
   server, s  server mode
   help, h    Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --template value     output template [$TRIVY_TEMPLATE]
   --format value       format (table, json, template) (default: "table") [$TRIVY_FORMAT]
   --input value        input file path instead of image name [$TRIVY_INPUT]
   --severity value     severities of vulnerabilities to be displayed (comma separated) (default: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL") [$TRIVY_SEVERITY]
   --output value       output file name [$TRIVY_OUTPUT]
   --exit-code value    Exit code when vulnerabilities were found (default: 0) [$TRIVY_EXIT_CODE]
   --skip-update        skip db update (default: false) [$TRIVY_SKIP_UPDATE]
   --download-db-only   download/update vulnerability database but don't run a scan (default: false) [$TRIVY_DOWNLOAD_DB_ONLY]
   --reset              remove all caches and database (default: false) [$TRIVY_RESET]
   --clear-cache        clear image caches without scanning (default: false) [$TRIVY_CLEAR_CACHE]
   --quiet              suppress progress bar and log output (default: false) [$TRIVY_QUIET]
   --no-progress        suppress progress bar (default: false) [$TRIVY_NO_PROGRESS]
   --ignore-unfixed     display only fixed vulnerabilities (default: false) [$TRIVY_IGNORE_UNFIXED]
   --debug              debug mode (default: false) [$TRIVY_DEBUG]
   --removed-pkgs       detect vulnerabilities of removed packages (only for Alpine) (default: false) [$TRIVY_REMOVED_PKGS]
   --vuln-type value    comma-separated list of vulnerability types (os,library) (default: "os,library") [$TRIVY_VULN_TYPE]
   --cache-dir value    cache directory (default: "/Users/teppei/Library/Caches/trivy") [$TRIVY_CACHE_DIR]
   --ignorefile value   specify .trivyignore file (default: ".trivyignore") [$TRIVY_IGNOREFILE]
   --timeout value      docker timeout (default: 2m0s) [$TRIVY_TIMEOUT]
   --light              light mode: it's faster, but vulnerability descriptions and references are not displayed (default: false) [$TRIVY_LIGHT]
   --only-update value  deprecated [$TRIVY_ONLY_UPDATE]
   --refresh            deprecated (default: false) [$TRIVY_REFRESH]
   --auto-refresh       deprecated (default: false) [$TRIVY_AUTO_REFRESH]
   --help, -h           show help (default: false)
   --version, -v        print the version (default: false)
```

But you can't specify some of the options with `server` subcommand. Also, you can't use some of the options with `client` subcommand. We probably need to hide some of the global options.

**Comment by knqyf263** [comment]
To address the above problem, I set Hidden=true in https://github.com/aquasecurity/trivy/pull/493/commits/92fa4f7eb3dfd1d84a39db0a423899bde8931e07.

`cli.Flag` is an interface and it doesn't have `Hidden` member, so I needed to assert type. I don't think it's a smart way. If you have any better idea, let me know, please.

**Comment by knqyf263** [comment]
Also, we should update README to promote the use of image subcommand.

**Comment by simar7** [comment]
@knqyf263 after the latest merge from master it looks like `TestRegistry` is failing within Github Actions. Would you know why?

**Comment by knqyf263** [comment]
Hmm. It's weird since it passed in the master branch. I don't know why. Is it reproducible?

**Comment by simar7** [comment]
> Hmm. It's weird since the test passed in the master branch. I don't know why. Is it reproducible?

Hmm I could reproduce it every single time yesterday but not today. Must've been a Github Actions issue. Seems to be fine now.

**Comment by knqyf263** [comment]
I added `image` subcommand to some examples in README. https://github.com/aquasecurity/trivy/pull/493/commits/3cbe4db80049a61f15915c0f5f4a92d470fc6420

**Pull request merged**
