### PR TITLE
fix: ingress helm manifest-update trivy image

### PR DESCRIPTION
**Pull request by krol3**
Fixing the helm deploy using `Ingress: true`.

Related to https://github.com/aquasecurity/trivy/issues/1320

### CODE REVIEW

**Comment by krol3** [comment]
@robervexcel could you take a look? I run locally using the Ingress.enable: true and works.

**Comment by georgekaz** [comment]
I'm getting `groupVersion shouldn't be empty`

which I think also means there are too many whitespace removing hyphens here:

```
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" -}}
apiVersion: networking.k8s.io/v1
{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
```

I think should be
```
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
```

**Comment by georgekaz** [comment]
Actually, looking at it, I've just realised, there's no fall back version there, i.e. there's no {{- else }}, so it also could be there's a logic error meaning there's no version included.

**Comment by knqyf263** [comment]
@krol3 Could you look into the issue reported by @georgekaz?

**Comment by krol3** [comment]
> Actually, looking at it, I've just realised, there's no fall back version there, i.e. there's no {{- else }}, so it also could be there's a logic error meaning there's no version included.
> 
> I'm seeing this problem when deploying with ArgoCD which is having issues evaluating the API version, but I still think this should be
> 
> ```
> {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" -}}
> apiVersion: networking.k8s.io/v1
> {{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" -}}
> apiVersion: networking.k8s.io/v1beta1
> {{- else -}}
> apiVersion: extensions/v1beta1
> {{- end -}}
> ```
> 
> Different issue from the original I know, but the same manifest so thought it should be raised

Nice catch @georgekaz , please review the last commit.

**Comment by krol3** [comment]
@knqyf263 I considered the points of @georgekaz and I added a gh steps to test the helm chart with ingress(false & true)

**Comment by knqyf263** [comment]
@krol3 Looks good. Thanks.

**Review by knqyf263 — APPROVED** [review]

**Pull request merged**
