### PR TITLE
docs: fix the broken link

### PR DESCRIPTION
**Pull request by dulltz**
## Description

Fix the broken link in the markdown. This PR is just a trivial document issue.

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ]  I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Review by simar7 — APPROVED** [review]

**Comment by simar7** [comment]
@DmitriyLewen @knqyf263 the error seems unrelated to this change

**Comment by DmitriyLewen** [comment]
@nikpivkin got similar error with downloading Go dependencies (`go mod tidy`) - https://github.com/aquasecurity/trivy/actions/runs/6611239867/job/17956478809?pr=5382
Looks like it is bug in GitHub Actions, but we didn't find way to fix this. 
After few hours Action ran correct.

**Comment by knqyf263** [comment]
@DmitriyLewen Do you think the python version is relevant?

**Comment by DmitriyLewen** [comment]
Python 3.12 is latest version.

I was able to reproduce this error in Ubuntu container and am working on solution to this problem.

**Comment by DmitriyLewen** [comment]
Created #5462 for docs issue.

**Pull request merged**
