### PR TITLE
feat: add Julia language support

### PR DESCRIPTION
**Pull request by Octogonapus**
## Description

This PR adds Julia language support to the analyzer. My primary motivation is for generating SBOMs.

I would love to include package licenses, but this information is not stored in the Julia manifest file.
You need to reach out to the package source to get it; is this something Trivy can (or should) do?

### TODO before merging

- Update https://github.com/package-url/packageurl-go with a new entry for Julia
- Update https://github.com/aquasecurity/go-dep-parser with a new parser for Julia
  - For now, I've included the parser in this repo. This will get moved out.

## Related issues
#4437

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [x] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Review by knqyf263 — COMMENTED** [review]
Thanks for your contribution. We usually add a parser in [go-dep-parser](https://github.com/aquasecurity/go-dep-parser). Could you refer to the repository and open a PR?

**Comment by Octogonapus** [comment]
This will be ready to go as soon as https://github.com/aquasecurity/go-dep-parser/pull/219 is merged

**Comment by ericphanson** [comment]
I saw this was closed for inactivity, could it be reopened? I am interested in using trivy with Julia

**Comment by Octogonapus** [comment]
The latest work is here and is waiting on review https://github.com/aquasecurity/trivy/pull/5635

**Comment by ericphanson** [comment]
aha nevermind, I see it is now over here: https://github.com/aquasecurity/trivy/pull/5635

**Pull request closed without merging**
