### PR TITLE
docs: add asdf and mise installation method

### PR DESCRIPTION
**Pull request by jylenhof**
## Description

- Add basic documentation to install trivy tool using asdf and mise tool

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [x] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [x] I've added usage information (if the PR introduces new options)
- [x] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by knqyf263** [comment]
Thanks for your contribution. We need your signature on our CLA.

**Comment by jylenhof** [comment]
It seems there's something wrong with the check on CLA...

>You have agreed to the CLA for multiple repositories or organizations
>
>Version: 2021-09-09

**Comment by knqyf263** [comment]
Are you using the same email address for CLA and commits?

**Comment by knqyf263** [comment]
It's conflicting now

**Review by knqyf263 — APPROVED** [review]
Thanks

**Pull request merged**
