### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by justfortee**
Grammatical error.

### CODE REVIEW

**Comment by knqyf263** [comment]
It doesn't mean a "different" update, but rather an "incremental" update. What do you think? @simar7

**Comment by simar7** [comment]
> It doesn't mean a "different" update, but rather an "incremental" update. What do you think? @simar7

Yes incremental sounds more appropriate. Could you make that change @justfortee?

**Review by simar7 — CHANGES_REQUESTED** [review]
left comments.

**Review by lizrice — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
