### PR TITLE
fix(java): fix unmarshal pom exclusions

### LINKED ISSUE #2920: FP on pom.xml
## Description
Running with version 0.32.0  I FP on the below pom.xml scanning. As far as I can tell only the older versions has a vulnerability

input pom.xml
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.test</groupId>
    <artifactId>test</artifactId>
    <packaging>war</packaging>
    <version>0.0.1-SNAPSHOT</version>
    <name>test</name>
    <url>http://maven.apache.org</url>
    <dependencies>
        <dependency>
            <groupId>org.jetbrains.dokka</groupId>
            <artifactId>dokka-gradle-plugin</artifactId>
            <version>1.7.10</version>
        </dependency>
    </dependencies>
</project>
```

## Output of `trivy -v`:

```
Version: 0.32.0
Vulnerability DB:
  Version: 2
  UpdatedAt: 2022-09-20 12:08:53.045849991 +0000 UTC
  NextUpdate: 2022-09-20 18:08:53.045849691 +0000 UTC
  DownloadedAt: 2022-09-20 12:27:43.7916 +0000 UTC
```

### PR DESCRIPTION
**Pull request by DmitriyLewen**
## Description
When we unmarshal `pom.xml` files, we only keep the last `exclusion` for each dependency.
Fixed it.

## Related issues
- Close #2920

## Related PRs
- [ ] https://github.com/aquasecurity/go-dep-parser/pull/135

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by knqyf263** [comment]
@DmitriyLewen Could you update go-dep-parser and make this PR ready for review?

**Comment by DmitriyLewen** [comment]
@knqyf263 Done!

**Comment by knqyf263** [comment]
Oops...I forgot to include that in v0.32.1... @DmitriyLewen Can you please resolve conflicts?

**Review by knqyf263 — APPROVED** [review]

**Comment by knqyf263** [comment]
>@DmitriyLewen Can you please resolve conflicts?

I did

**Pull request merged**
