### PR TITLE
refactor: clarify db update warning messages

### PR DESCRIPTION
**Pull request by Dentrax**
Signed-off-by: Furkan <furkan.turkal@trendyol.com>

## Related issues
- Close #XXX

## Related PRs
- [ ] #XXX
- [ ] #YYY

Remove this section if you don't have related PRs.

## Checklist
- [X] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy/blob/main/CONTRIBUTING.md) to this repository.
- [X] I've followed the [conventions](https://github.com/aquasecurity/trivy/blob/main/CONTRIBUTING.md#title) in the PR title.
- [X] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by knqyf263** [comment]
Thanks for your contribution! Could you sign our CLA?

**Comment by Dentrax** [comment]
Oh, forgot this. @knqyf263 I opened the CLA sign web page but couldn't see any button for signing. What should I do here?

Screen Shot 2022-03-15 at 12 49 34

**Comment by knqyf263** [comment]
I think it is taking a while to load the CLA content. After a few seconds or more, you will see this.
image

**Comment by knqyf263** [comment]
Thanks for signing our CLA! As for the detected vulnerability, it is not related to this PR. We'll fix it soon. Just a moment.

**Review by knqyf263 — APPROVED** [review]

**Comment by knqyf263** [comment]
Thanks!

**Pull request merged**
