### PR TITLE
chore: add prefix to image errors

### PR DESCRIPTION
**Pull request by knqyf263**
## Description
Show more friendly errors from image sources.

### Before

```
$ trivy image foo
...
2023-11-16T15:21:08.107+0900    FATAL   image scan error: scan error: unable to initialize a scanner: unable to initialize a docker scanner: 4 errors occurred:
        * unable to inspect the image (foo): Error response from daemon: No such image: foo:latest
        * containerd socket not found: /run/containerd/containerd.sock
        * unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such file or directory
        * GET https://index.docker.io/v2/library/foo/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/foo Type:repository]]

```

### After

```
$ trivy image foo
...
2023-11-16T15:19:48.658+0900    FATAL   image scan error: scan error: unable to initialize a scanner: unable to initialize a docker scanner: 4 errors occurred:
        * docker error: unable to inspect the image (foo): Error response from daemon: No such image: foo:latest
        * containerd error: containerd socket not found: /run/containerd/containerd.sock
        * podman error: unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such file or directory
        * remote error: GET https://index.docker.io/v2/library/foo/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/foo Type:repository]]
```

## Related issues
- Close https://github.com/aquasecurity/trivy/issues/5600

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by knqyf263** [comment]
@AXDOOMER Does it help?

**Comment by knqyf263** [comment]
@DmitriyLewen I didn't see his response, but I believe it's useful anyway.

**Comment by DmitriyLewen** [comment]
> image scan error: scan error: unable to initialize a scanner: unable to initialize a docker scanner: 4 errors occurred:

`docker scanner` can still be confusing.
What if you use an `image scanner`?

**Comment by knqyf263** [comment]
Good point. I was not aware of that. Thanks!
https://github.com/aquasecurity/trivy/pull/5601/commits/2e6b7bfeca00ec9a7c4ae1c7ef5fcdc56ded86e6

**Review by DmitriyLewen — APPROVED** [review]
LGTM

**Pull request merged**
