### PR TITLE
feat(cli): Do not set default commands when a plugin is being run (#1548)

### LINKED ISSUE #1548: Add support for plugins to override existing commands
When running a Trivy plugin, the existing set of commands cannot be used. Ideally a plugin, for example, would be able to provide an implementation of the `config` command.

This could be achieved by removing the existing commands when a plugin is being run.

### PR DESCRIPTION
**Pull request by liamg**
Resolves #1548

### CODE REVIEW

**Comment by knqyf263** [comment]
Looks totally good, but we may want to disable `--help` to call the help menu of the plugin.
https://github.com/urfave/cli/issues/174

**Review by owenrumney — APPROVED** [review]

**Comment by liamg** [comment]
> Looks totally good, but we may want to disable `--help` so that the help menu of the plugin can be called. [urfave/cli#174](https://github.com/urfave/cli/issues/174)

We were just talking about this exact issue on Zoom!

**Comment by knqyf263** [comment]
I can predict the future lol

**Comment by liamg** [comment]
It looks like there's an issue where instead of passing the `--help` through, it picks up an undefined flag error: https://github.com/urfave/cli/issues/1290 - so to workaround this I've defined a help flag to allow the plugin to run when `--help` is requested.

**Review by knqyf263 — APPROVED** [review]

**Comment by knqyf263** [comment]
Thanks. I've not tested it, but trust you😄

**Pull request merged**
