### PR TITLE
Fix comparison table to use words instead of symbols

### LINKED ISSUE #301: Missing Legend in Readme for Comparison with other scanners
The Comparison with other scanners section does not appear to contain a legend that explains what the various symbols mean. Would be handy to know, how to interpret the various symbols in the comparison table.

### PR DESCRIPTION
**Pull request by rndmh3ro**
fixes #301

### CODE REVIEW

**Comment by knqyf263** [comment]
This data is as of May 2019. I'm not sure about the current status of the other projects. We can remove this table.

**Comment by knqyf263** [comment]
I merged this PR once, but let's consider if we should keep this table.

**Comment by AkihiroSuda** [comment]
This conversion doesn't seem correct.
△ means "Not so bad, but not good either".
It never means "Good".

**Comment by knqyf263** [comment]
@AkihiroSuda You're right, but I couldn't come up with a good short phrase. Can we say "not bad"?

**Comment by AkihiroSuda** [comment]
sgtm

**Comment by knqyf263** [comment]
Thanks. I fixed it. https://github.com/aquasecurity/trivy/pull/623

**Pull request merged**
