### PR TITLE
feat(nodejs): parse package.json files alongside package-lock.json

### PR DESCRIPTION
**Pull request by DmitriyLewen**
## Description
`package-lock.json` files do not contain dependency license information.
This PR parses `*/node_modules/<package_name>/package.json` files alongside `package-lock.json` and identify licenses.

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by naortalmor1** [comment]
Hey @DmitriyLewen,
Is there something new with that?

**Comment by DmitriyLewen** [comment]
Hello @naortalmor1 
It is currently required that @knqyf263 review this PR.

**Comment by agdimech** [comment]
Any updates on this?

**Comment by knqyf263** [comment]
@DmitriyLewen Now, we can use post-analyzers like [poetry](https://github.com/aquasecurity/trivy/pull/3695). Would you rewrite this PR?

**Review by knqyf263 — APPROVED** [review]

**Pull request merged**
