### PR TITLE
fix(misconf): handle dot files better

### PR DESCRIPTION
**Pull request by simar7**
Signed-off-by: Simar <simar@linux.com>

## Description
We shouldn't trim out dot prefixes as they are valid usable directories.

## Related issues
- Close https://github.com/aquasecurity/trivy/issues/3549

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Review by giorod3 — APPROVED** [review]

**Comment by simar7** [comment]
The failure in the test seems unrelated to this change.

**Comment by simar7** [comment]
@knqyf263 - could you review this as well? Seems to have been introduced here https://github.com/aquasecurity/trivy/pull/3437/files#diff-50dbe9b7496c81601826d673eea9cf88d33170ff79be2ca201032a187adc5219R173

I believe this function might be used somewhere else as well. I'm unclear on the intention or any case that would require trimming the dot prefix, would you know?

I've added a few tests here: https://github.com/aquasecurity/trivy/blob/ad92d341990979e36015b22a4f41db3895634499/pkg/misconf/scanner_test.go#L145-L172

**Comment by knqyf263** [comment]
@simar7 I just refactored and moved the original code to another package. I didn't change any logic, and it was originally written by Owen and Liam. I'm not sure what was intended. What do you think about using `filepath.Clean`?

**Comment by simar7** [comment]
> @simar7 I just refactored and moved the original code to a new package. I didn't change any logic, and it was originally written by Owen and Liam. I'm not sure what was intended. What do you think about using `filepath.Clean`?

thanks that's good to learn, I've updated it.

**Review by knqyf263 — APPROVED** [review]

**Comment by knqyf263** [comment]
I guess this bug existed for a long time, but it was not a problem as embedded policies had been used. It appeared in v0.37.0 because of policy distribution.

**Pull request merged**
