### PR TITLE
fix(server): add indirect prop to package

### PR DESCRIPTION
**Pull request by roi-orca**
## Description
When the packages are sent to trivy server for persisting the blob info, the indirect attribute is missing, and then when retrieving the scan results the packages are treat as direct dependency always which is not correct 

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [x] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [x] I've added usage information (if the PR introduces new options)
- [x] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by knqyf263** [comment]
Looks like this PR is not ready for review. I've converted it into draft.

**Comment by roi-orca** [comment]
> Looks like this PR is not ready for review. I've converted it into a draft. It helps us triage PRs to review.

what is missing?

**Comment by knqyf263** [comment]
No description, PRs, issues, etc.

**Comment by roi-orca** [comment]
@knqyf263 can you please review? thanks!

**Comment by knqyf263** [comment]
Also, please read the checklist and mark them.

**Review by knqyf263 — APPROVED** [review]

**Pull request merged**
