### PR TITLE
+ improve gitlab-ci template

### PR DESCRIPTION
**Pull request by strowi**
solves #454 
- removed the need for dind
- added gitlab authentication variables
- almost a drop-in replacement except for TRIVY_VERSION and TRIVY_SEVERITY variables

### CODE REVIEW

**Comment by knqyf263** [comment]
@tnir Does it look good to you?

**Comment by simar7** [comment]
@tnir ping :)

**Comment by Johannestegner** [comment]
Would be sweet if there was a way to set a variable to use a remote trivy service, I wrote this a while back if you wish to take some inspiration:

https://gitlab.com/jitesoft/gitlab-ci-lib/-/blob/master/Scan/trivy.yml

**Comment by krol3** [comment]
@strowi @Johannestegner are you working in this issue?

**Comment by Johannestegner** [comment]
> 
> 
> @strowi @Johannestegner are you working in this issue?

Not actively, I could for sure update the template and create a PR if you wish :)

**Comment by Johannestegner** [comment]
Also, I do think that the default container scan script for GitLab now uses trivy, so this might not be needed anymore?

For reference, the scripts I use in my pipelines looks something like this:

Container scanning:

```yaml
variables:
  TRIVY_FORMAT: "template"
  TRIVY_TEMPLATE: "/contrib/gitlab.tpl"
  TRIVY_OUTPUT: "gl-container-scanning-report.json"
  TRIVY_NO_PROGRESS: "true"
  TRIVY_EXIT_CODE: 0

.container_scanning: &container_scanning
  stage: scan
  image:
    name: registry.gitlab.com/jitesoft/dockerfiles/trivy:latest
    entrypoint:
      - ""
  variables:
    GIT_STRATEGY: none
  script:
    - if [ -z ${SCANNING_IMAGE_NAME+x} ]; then export SCANNING_IMAGE_NAME="${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}"; echo "SCANNING_IMAGE_NAME set to default (${SCANNING_IMAGE_NAME})"; fi
    - if [ -z ${TRIVY_CACHE_DIR+x} ]; then TRIVY_CACHE_DIR="$(pwd)/.trivy_cache"; mkdir -p ${TRIVY_CACHE_DIR}; echo "Using default cache location if cache is needed (${TRIVY_CACHE_DIR})."; fi
    - if [ -n "${TRIVY_ENDPOINT}" ]; then ARGS="client --remote=${TRIVY_ENDPOINT} ${EXTRA_ARGS} "; fi
    - if [ ! -n "${TRIVY_ENDPOINT}" ]; then ARGS="image ${EXTRA_ARGS}"; fi
    - trivy ${ARGS}${SCANNING_IMAGE_NAME}
    - if [ -z ${NO_OUTPUT+x} ]; then trivy ${ARGS}--format=table ${SCANNING_IMAGE_NAME}; fi
  allow_failure: true
  artifacts:
    reports:
      container_scanning: gl-container-scanning-report.json
  rules:
    - if: $NO_AUTO && $NO_AUTO == 'true'
      when: never
    - if: $CONTAINER_SCANNING_DISABLED
      when: never
    - exists:
        - '{Dockerfile,*/Dockerfile,*/*/Dockerfile}'
      when: always
```

Standard dependency scanning:

```yaml

auto.scan.trivy:
  stage: test
  services: []
  variables:
    TRIVY_CACHE_DIR: "${CI_PROJECT_DIR}/.trivycache"
    TRIVY_NO_PROGRESS: "true"
    TRIVY_VULN_TYPE: "library"
  image:
    name: registry.gitlab.com/jitesoft/dockerfiles/trivy:latest
    entrypoint:
      - ""
  before_script:
    - mkdir -p ${TRIVY_CACHE_DIR}
    - trivy --download-db-only --cache-dir ${TRIVY_CACHE_DIR}
    - wget https://gitlab.com/jitesoft/gitlab-ci-lib/-/raw/master/templates/gitlab-dependency-scanning.tpl
  script:
    - trivy fs --exit-code 0 --format template --template "@${CI_PROJECT_DIR}/gitlab-dependency-scanning.tpl" --output "${CI_PROJECT_DIR}/gl-dependency-scanning-report.json" ./
    - trivy fs --exit-code 0 --output table ./
    - trivy fs --exit-code 1 --severity HIGH,CRITICAL -o table ./
  allow_failure: true
  cache:
    paths:
      - .trivycache/
  artifacts:
    reports:
      dependency_scanning: gl-dependency-scanning-report.json
  allow_failure: true
  rules:
    - if: $DEPENDENCY_SCANNING_DISABLED
      when: never
    - if: '$CI_COMMIT_BRANCH || $CI_PIPELINE_SOURCE == "external_pull_request_event" || $CI_PIPELINE_SOURCE == "merge_request_event"'
      exists:
        - '{composer.lock,*/composer.lock,*/*/composer.lock}'
        - '{poetry.lock,*/poetry.lock,*/*/poetry.lock}'
        - '{yarn.lock,*/yarn.lock,*/*/yarn.lock}'
        - '{Cargo.lock,*/Cargo.lock,*/*/Cargo.lock}'
        - '{packages.lock.json,*/packages.lock.json,*/*/packages.lock.json}'
        - '{package-lock.json,*/package-lock.json,*/*/package-lock.json}'
        - '{Gemfile.lock,*/Gemfile.lock,*/*/Gemfile.lock}'
        - '{Pipfile.lock,*/Pipfile.lock,*/*/Pipfile.lock}'
        - '{*.jar,*/*.jar,*/*/*.jar}'
        - '{*.war,*/*.war,*/*/*.war}'
        - '{*.ear,*/*.ear,*/*/*.ear}'
      when: always
    - when: never


```

**Comment by strowi** [comment]
Since i didn't get any more feedback, i haven't bothered doing more work on this. But your templates look  quite good, haven't thought about dep-scanning + excludes.;) 
Oh and btw. it seems to me gitlab is still using clair within their template: https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Security/Container-Scanning.gitlab-ci.yml

**Comment by Johannestegner** [comment]
> 
> 
> Since i didn't get any more feedback, i haven't bothered doing more work on this. But your templates look quite good, haven't thought about dep-scanning + excludes.;)
> Oh and btw. it seems to me gitlab is still using clair within their template: https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Security/Container-Scanning.gitlab-ci.yml

Thnx :)

Aye, they will be using clair til next major version, which I think is coming up quite soon, see notice at: https://docs.gitlab.com/ee/user/application_security/container_scanning/

**Comment by krol3** [comment]
@strowi I'm sorry for the delay. @Johannestegner Do you have any public repository using gitlab-template? We could add to the [Trivy GitLab documentation](https://aquasecurity.github.io/trivy/latest/integrations/gitlab-ci/) as example repositories.

**Comment by Johannestegner** [comment]
> 
> 
> @strowi I'm sorry for the delay. @Johannestegner Do you have any public repository using gitlab-template? We could add to the [Trivy GitLab documentation](https://aquasecurity.github.io/trivy/latest/integrations/gitlab-ci/) as example repositories.

Most of my repositories does actually, but I use the `include` feature in gitlabs ci YAML to import the scripts.

So I include them from this repository:

https://gitlab.com/jitesoft/gitlab-ci-lib/-/blob/master/Scan/trivy.yml
https://gitlab.com/jitesoft/gitlab-ci-lib/-/blob/master/Scan/dependency.yml#L49

If you give me a moment, I will try to re-write them a bit to be a bit easier to read, hehe, using lots of "special cases" in those :)

**Comment by Johannestegner** [comment]
Updated my scripts slightly and created a "readme" for them if you wish to extract anything useful for the documentation! :)
https://gitlab.com/jitesoft/gitlab-ci-lib/-/blob/master/docs/scan.trivy.md

A file which uses them can be found here: https://gitlab.com/jitesoft/dockerfiles/alpine/-/blob/master/.gitlab-ci.yml#L41

Hope anything can be used! ;)

**Comment by krol3** [comment]
@Johannestegner could you add your references in the trivy/docs: https://github.com/aquasecurity/trivy/blob/main/docs/integrations/gitlab-ci.md

**Comment by Johannestegner** [comment]
> 
> @Johannestegner could you add your references in the trivy/docs: https://github.com/aquasecurity/trivy/blob/main/docs/integrations/gitlab-ci.md

For sure. About to head to bed, but will keep this page up to remind me of doing it tomorrow! :)

**Pull request closed without merging**
