### PR TITLE
ci: add `trivy` group for `dependabot`

### PR DESCRIPTION
**Pull request by DmitriyLewen**
## Description
Add `trivy` group for `dependabot`

Test PRs:
- https://github.com/DmitriyLewen/trivy/pull/107
- https://github.com/DmitriyLewen/trivy/pull/111

## Related PRs
- [ ] #6904

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by knqyf263** [comment]
I think `trivy-*` should be bumped manually. What if just excluding them?

**Review by knqyf263 — APPROVED** [review]

**Comment by DmitriyLewen** [comment]
@knqyf263 I updated this PR.

But dependabot will create separate PR for each `trivy-` deps (e.g. https://github.com/DmitriyLewen/trivy/pull/107)
We can add `trivy-` deps to `ignore` field (https://github.com/DmitriyLewen/trivy/blob/b8e4484761a237ec00366a7a259353ba36a391e4/.github/dependabot.yml#L24-L25)
https://github.com/DmitriyLewen/trivy/pull/107

wdyt?

**Comment by simar7** [comment]
> >But dependabot will create separate PR for each trivy- deps (e.g. https://github.com/DmitriyLewen/trivy/pull/107)
> 
> 
> 
> @simar7 @nikpivkin @chen-keinan What do you think? You guys have more chances to bump `trivy-*`. Do you prefer bumping them manually? Or do you want Dependabot to create a PR?

I think I would prefer a manual bump. Sometimes we have to coordinate changes in Trivy and the ancillary repos in a way that they don't cause breakage.

**Comment by DmitriyLewen** [comment]
@knqyf263 ignore `trivy-*` deps - https://github.com/aquasecurity/trivy/pull/6908/commits/23aa9264cdc60551f8321a6a41ce7a75356a0371

**Comment by knqyf263** [comment]
Tests are still failing?

**Comment by DmitriyLewen** [comment]
First we need to merge #6914.

**Pull request merged**
