### PR TITLE
ci: run golangci in docker if possible

### PR DESCRIPTION
**Pull request by nikpivkin**
## Description
I have a different version of `golangci-lint` installed on my machine than the ones listed in the magefile or GitHub workflow. Because of this, I get different results when running linter, which makes it difficult to maintain code quality without submitting changes to Github. I suggest running `golangci` in the docker if it is running.

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by nikpivkin** [comment]
The developer may forget to update the linter. Or Trivy may not be using the latest linter version.

**Comment by knqyf263** [comment]
>The developer may forget to update the linter.

What if we show a warning if the golangci-lint version is different?

**Comment by knqyf263** [comment]
> > The developer may forget to update the linter.
> 
> What if we show a warning if the golangci-lint version is different? Or even fail on that.

I implemented my idea. Please let me know if it works for you.
https://github.com/aquasecurity/trivy/pull/6700

**Comment by nikpivkin** [comment]
@knqyf263 lgtm

**Pull request closed without merging**
