### PR TITLE
docs: add note about Bun

### PR DESCRIPTION
**Pull request by nikpivkin**
## Description
Users have [questions](https://github.com/aquasecurity/trivy/discussions/5996) about Bun support, so I've added a note to the documentation.

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [x] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Review by knqyf263 — COMMENTED** [review]
We should update the tables as well.

**Review by knqyf263 — APPROVED** [review]

**Comment by itaysk** [comment]
needs to be added [here](https://aquasecurity.github.io/trivy/v0.48/docs/coverage/language/) and [here](https://aquasecurity.github.io/trivy/v0.48/docs/coverage/language/nodejs/)
N.B not sure why we need 3 places but for now at least keep it consistent

**Comment by knqyf263** [comment]
>needs to be added [here](https://aquasecurity.github.io/trivy/v0.48/docs/coverage/language/) and [here](https://aquasecurity.github.io/trivy/v0.48/docs/coverage/language/nodejs/)

We don't need to update [this page](https://aquasecurity.github.io/trivy/v0.48/docs/coverage/language/) as it doesn't mention package managers.

And [this page](https://aquasecurity.github.io/trivy/v0.48/docs/coverage/language/nodejs/) is exactly what we updated in this PR. Am I missing something? Note that it is not deployed yet and exists only in dev.
https://aquasecurity.github.io/trivy/dev/docs/coverage/language/nodejs/

**Comment by knqyf263** [comment]
>N.B not sure why we need 3 places but for now at least keep it consistent

Therefore, we have two places. One place is for an overview, and the other is for details.

**Pull request merged**
