### PR TITLE
feat: added misconfiguration field for html.tpl

### PR DESCRIPTION
**Pull request by DmitriyLewen**
Trivi there is only tables of vulnerabilities for the html.tpl config.
For example.:
```
➜ ls
Dockerfile
➜  trivy config .

2021-12-09T10:45:09.460+0600	INFO	Detected config files: 1

Dockerfile (dockerfile)
=======================
Tests: 23 (SUCCESSES: 22, FAILURES: 1, EXCEPTIONS: 0)
Failures: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 1, CRITICAL: 0)

+---------------------------+------------+-----------+----------+------------------------------------------+
|           TYPE            | MISCONF ID |   CHECK   | SEVERITY |                 MESSAGE                  |
+---------------------------+------------+-----------+----------+------------------------------------------+
| Dockerfile Security Check |   DS002    | root user |   HIGH   | Specify at least 1 USER                  |
|                           |            |           |          | command in Dockerfile with               |
|                           |            |           |          | non-root user as argument                |
|                           |            |           |          | -->avd.aquasec.com/appshield/ds002       |
+---------------------------+------------+-----------+----------+------------------------------------------+
➜  trivy config --format=template --template='@contrib/html.tpl' .
```
Trivy now generates valid html with no misconfigurations: 
misconf-old

I added new tables for report misconfiguration:
misconf-new

### CODE REVIEW

**Comment by knqyf263** [comment]
Can we add description? Otherwise, it is hard to understand where the problem is in the config file.

**Comment by DmitriyLewen** [comment]
Hello @knqyf263 
I changed the description, can you look at this?

**Comment by knqyf263** [comment]
Where did you find...? I didn't see it. I meant description or message should be displayed in the HTML table.

**Comment by DmitriyLewen** [comment]
Sorry, I didn't understand You the first time. "Message" added to HTML table.

**Comment by knqyf263** [comment]
@DmitriyLewen Thanks for the update! Is it ready for review? It is still a draft.

**Comment by DmitriyLewen** [comment]
@knqyf263 , yes, review this, please

**Review by knqyf263 — APPROVED** [review]

**Pull request merged**
