### PR TITLE
chore: replace interface{} with any

### PR DESCRIPTION
**Pull request by nikpivkin**
## Description
`any` is an alias of `interface{}`. any is more concise and better reflects its purpose.

Just run `gofmt -w -r 'interface{} -> any' $(find . -name "*.go" ! -name "mock_*" ! -name "*twirp.go" ! -name "*pb.go" ! -name "*_gen.go")`

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by simar7** [comment]
Since they are interchangeable, I'm fine with the actual change. However I do have a few small concerns:
1. It's not easy to review this PR for any accidental changes.
2. The commit history is affected for many lines.
3. (not so relevant) It only works with Go 1.18 and newer. 

I reviewed the `pkg/iac` directory so far.

**Comment by knqyf263** [comment]
I'm also okay with these changes, although it's hard to review all of them. For the future, what if we introduce a linter to enforce `any`? Then, we can auto-fix them with `golangci-lint—- fix`.

**Comment by nikpivkin** [comment]
@knqyf263 Should the golangci-lint configuration be updated in another PR?

**Comment by knqyf263** [comment]
Did you find such a linter?

**Review by simar7 — APPROVED** [review]

**Comment by nikpivkin** [comment]
@knqyf263 it's gofmt https://golangci-lint.run/usage/linters/#gofmt

**Comment by knqyf263** [comment]
I didn't know golangci-lint can define such replaces. We can add it in this PR.

**Pull request merged**
