### PR TITLE
feat(report): add location.message to SARIF output (#3002)

### LINKED ISSUE #3002: Specify location.message in SARIF reports
SARIF allows a "message" to be provided for a location and that can have more useful information. See:
https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317675

It would be helpful to set this property so SARIF consumers can display better information. It would be particularly nice if Trivy includes the file and the package name and version (ex, `pom.xml:org.yaml:snakeyaml@1.30`).

### PR DESCRIPTION
**Pull request by candrews**
## Description
SARIF allows a "message" to be provided for a location and that can have more useful information. See:
https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317675

It would be helpful to set this property so SARIF consumers can display better information. It would be particularly nice if Trivy includes the file and the package name and version (ex, `pom.xml:org.yaml:snakeyaml@1.30`).

## Related issues
- Close #3002

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [x] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [x] I've added usage information (if the PR introduces new options)
- [x] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by candrews** [comment]
I think I'm finished.

I'm having trouble running the tests myself [(tinygo is broken in Fedora 37 so I haven't been able to use it)](https://bugzilla.redhat.com/show_bug.cgi?id=2133123), sorry for the noise :(

**Comment by candrews** [comment]
@afdesk can this be merged now?

If not, please let me know what I can do and I'll get right on it - thank you!

**Comment by afdesk** [comment]
@candrews thanks! 
I've updated a sarif golden file for the integration test.

**Comment by candrews** [comment]
> @candrews thanks! I've updated a sarif golden file for the integration test.

Thank you!

**Review by afdesk — APPROVED** [review]

**Comment by candrews** [comment]
> it seems this change doesn't affect on the SARIF for github security, right?

According to https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning#location-object
> location.message.text | Optional. A message relevant to the location.

So GitHub at least knows about this field. I don't know exactly how it will present it in the UI.

**Comment by afdesk** [comment]
@candrews thanks! it's ok, I understand your point.
it was just interesting.

**Review by knqyf263 — APPROVED** [review]

**Comment by knqyf263** [comment]
Thanks

**Pull request merged**
