### PR TITLE
feat(python): Include Conda packages in SBOMs

### LINKED ISSUE #3321: Include Conda packages in SBOMs
This is a follow up from #1856 to track scanning for Anaconda packages and including them in generates SBOMs separately. Potential next step after that would be to track vulnerabilities in Anaconda packages.

### PR DESCRIPTION
**Pull request by maitre-matt**
## Description

Discover conda (aka Anaconda) packages to include them in SBOMs.

## Related issues
- Close #3321

## Related PRs
- https://github.com/aquasecurity/go-dep-parser/pull/151

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [x] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by maitre-matt** [comment]
@DmitriyLewen: following up on the ask to add integration tests. Would there be guidance on where to add them? I was thinking about adding an entry in [/integration/fs_test.go](https://github.com/aquasecurity/trivy/blob/main/integration/fs_test.go) but noticed that `"--format", "json"` was hardcoded in `osArgs`. Would it make sense to make that configurable to allow setting `"--format", "cyclonedx"` (keeping `json` as default value)?

**Comment by knqyf263** [comment]
>Would it make sense to make that configurable to allow setting "--format", "cyclonedx" (keeping json as default value)?

Sounds good to me.

**Comment by mmaitre314** [comment]
Integration tests have been added. One thing I am not sure about in the generated SBOM [integration/testdata/conda.json.golden](https://github.com/aquasecurity/trivy/pull/3379/files#diff-10dfadc456487069982706cb91632d9002a91ec02f7510c5037643317ca1b051): the SBOM lists packages as both `application` and `library` instead of just `library`. I would have expected a dependency tree more like `application` -> `library` instead of `application` -> `application` -> `library`.

**Comment by maitre-matt** [comment]
Integration tests have been added. One thing I am not sure about in the generated SBOM [integration/testdata/conda.json.golden](https://github.com/aquasecurity/trivy/pull/3379/files#diff-10dfadc456487069982706cb91632d9002a91ec02f7510c5037643317ca1b051): the SBOM lists packages as both `application` and `library` instead of just `library`. I would have expected a dependency tree more like `application` -> `library` instead of `application` -> `application` -> `library`.

**Comment by maitre-matt** [comment]
That did the trick. There were a few more places which had `PythonPkg` but not `CondaPkg` so I updated those too, and added a test to cover SPDX. In SPDX the hierarchy is `document` -> `filesystem` -> `application` -> `package`, which looks reasonable.

**Review by knqyf263 — APPROVED** [review]

**Comment by knqyf263** [comment]
Thanks👍

**Pull request merged**
