### PR TITLE
chore: auto label discussions

### PR DESCRIPTION
**Pull request by itaysk**
## Description
automatically label "Idea" discussions based on the form category that the author selects.
if this is working for us, we can extend this action to other use cases. for example, labels based on key words, or use chatgpt.

## Related Issues
- #4190 

Remove this section if you don't have related PRs.

## Checklist
- [ ] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [ ] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by knqyf263** [comment]
Wouldn't it be simpler to use [actions/github-script](https://docs.github.com/en/actions/managing-issues-and-pull-requests/adding-labels-to-issues)? Something like:

```
name: Auto Label Discussion

on:
  discussion:
    types: [opened]

jobs:
  label_discussion:
    runs-on: ubuntu-latest
    steps:
    - name: Conditionally label discussions based on category and content
      uses: actions/github-script@v6
      with:
        script: |
          const discussion = context.payload.discussion;
          const discussionNumber = discussion.number;
          const category = discussion.category.name;
          const body = discussion.body;

          // Check if the discussion category is "Ideas"
          if (category === "Ideas") {
            // Check if the body contains the specified string
            if (body.includes("### Scanner\n\nVulnerability")) {
              await github.rest.discussions.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                discussion_number: discussionNumber,
                labels: ['scan/vulnerability']
              });
              console.log(`Added "scan/vulnerability" label to discussion #${discussionNumber}.`);
            }
          }
```

**Comment by itaysk** [comment]
yes looks so much better. I'll give it another go with github script. 
(I did the first try with github script a few months ago but faced an issue with updating discussions specifically. will try again now)

**Comment by itaysk** [comment]
for reference, this is why I stopped my previous attempt with github script: https://github.com/octokit/octokit.js/issues/2489
I'll look into other approaches with octokit

**Comment by knqyf263** [comment]
oh...

**Comment by itaysk** [comment]
closing in favor of: https://github.com/aquasecurity/trivy/pull/5259

**Pull request closed without merging**
