### PR TITLE
docs: add pre-commit hook to community tools

### PR DESCRIPTION
**Pull request by mxab**
## Description

Mention trivy pre-commit hook https://github.com/mxab/pre-commit-trivy

## Related issues
- Relates to #1858

## Related PRs
- [x] #2490

Remove this section if you don't have related PRs.

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [x] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [x] I've added usage information (if the PR introduces new options)
- [x] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by knqyf263** [comment]
@mxab Could you resolve the conflict?

**Comment by mxab** [comment]
ok moved it under the ide section now

By the way do you have any opionions on the pre-commit hook?
Since I run it via docker now, I cannot use the default cache dir, therefore creating a cache directory in the repo it self via `.. fs --cache-dir /src/.pre-commit-trivv-cache`

**Comment by knqyf263** [comment]
>Since I run it via docker now, I cannot use the default cache dir, therefore creating a cache directory in the repo it self via .. fs --cache-dir /src/.pre-commit-trivv-cache

Does pre-commit automatically mount the repository directory under `/src`? If it is the case, your approach `--cache-dir `/src/.pre-commit-trivy-cache` sounds good.

**Comment by mxab** [comment]
ok good to know, I look if I can get pre-commit to created a named volume

**Review by knqyf263 — APPROVED** [review]
This PR looks good to me anyway. Thanks!

**Pull request merged**
