### PR TITLE
fix(sbom): scan results of SBOMs generated from container images are missing layers

### PR DESCRIPTION
**Pull request by fabriziosestito**
## Description

When scanning a SBOM generated from a container image, layers are missing from the scan results.
This happens because layers are explicitly removed if the scanned artifact is not of the type container image.
However, this removes the layers when a container image SBOM is generated from a container image.
Moreover, setting layers to an empty value is not needed as layers are not present when scanning artifacts that are not container images or SBOMs of container images anyway.

## Related issues
- Related to discussion: https://github.com/aquasecurity/trivy/discussions/6504

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by knqyf263** [comment]
Thanks for your contribution. Could you fix tests?

**Comment by fabriziosestito** [comment]
@knqyf263 I've updated the existing integration tests and fixtures

**Comment by knqyf263** [comment]
@DmitriyLewen Would you also take a look?

**Review by DmitriyLewen — APPROVED** [review]
I tried, but couldn't think of a issues for these changes 😄
Approved.

cc. @knqyf263

**Review by knqyf263 — APPROVED** [review]

**Pull request merged**
