### PR TITLE
feat: add support for Chainguard's commercial distro

### LINKED ISSUE #3630: Support for Chainguard's commercial distro
Chainguard has created a new commercial distro that's based on [Wolfi](https://github.com/wolfi-dev/). This new distro has additional packages and consequently, a security data feed that's separate from Wolfi's.

It'd be **amazing** to see Trivy support scanning container images that are using this distro. 😃

The `id` for the new distro is just `chainguard`. The secdb structure is exactly the same as Wolfi's. The expected location of the secdb is `https://packages.cgr.dev/chainguard/security.json`.

I'm starting to prepare branches for the various Trivy repos now. I'll be applying the learnings from the PRs and your helpful review feedback from #3205. 🙏 

Please let me know if you have any additional pointers or questions about this!

### PR DESCRIPTION
**Pull request by luhring**
## Description

This PR adds support for Chainguard's commercial Linux distribution, which is based on [Wolfi](https://github.com/wolfi-dev/).

### Before

```console
$ trivy i ghcr.io/luhring/trivy-chainguard:latest
2023-02-16T16:37:55.851-0500	INFO	Vulnerability scanning is enabled
2023-02-16T16:37:55.851-0500	INFO	Secret scanning is enabled
2023-02-16T16:37:55.851-0500	INFO	If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2023-02-16T16:37:55.851-0500	INFO	Please see also https://aquasecurity.github.io/trivy/v0.37/docs/secret/scanning/#recommendation for faster secret detection
2023-02-16T16:37:55.860-0500	INFO	Detected OS: none
2023-02-16T16:37:55.860-0500	WARN	unsupported os : none
2023-02-16T16:37:55.860-0500	INFO	Number of language-specific files: 0
```

### After

```console
$ go run ./cmd/trivy --cache-dir '../trivy-db/cache' i --skip-db-update ghcr.io/luhring/trivy-chainguard:latest
2023-02-16T16:38:28.870-0500	INFO	Vulnerability scanning is enabled
2023-02-16T16:38:28.870-0500	INFO	Secret scanning is enabled
2023-02-16T16:38:28.870-0500	INFO	If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2023-02-16T16:38:28.870-0500	INFO	Please see also https://aquasecurity.github.io/trivy/dev/docs/secret/scanning/#recommendation for faster secret detection
2023-02-16T16:38:28.875-0500	INFO	Detected OS: chainguard
2023-02-16T16:38:28.875-0500	INFO	Detecting Chainguard vulnerabilities...
2023-02-16T16:38:28.876-0500	INFO	Number of language-specific files: 0

ghcr.io/luhring/trivy-chainguard:latest (chainguard 20230214)

Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
```

### Notes

- Depends on `trivy-db` version bump once https://github.com/aquasecurity/trivy-db/pull/281 is merged
- See related re: Wolfi support: https://github.com/aquasecurity/trivy/pull/3215

## Related issues
- Close #3630 

## Related PRs
- [ ] https://github.com/aquasecurity/vuln-list-update/pull/190
- [ ] https://github.com/aquasecurity/trivy-db/pull/281

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [x] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [x] I've added usage information (if the PR introduces new options)
- [x] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by knqyf263** [comment]
Hi @luhring, we've merged https://github.com/aquasecurity/trivy-db/pull/281. Could you update this PR?

**Comment by luhring** [comment]
> You tested with `ghcr.io/luhring/trivy-chainguard:latest`. It looks like your personal image. Is there any official image we can use for testing?

Good question, and yes! We've since made `ghcr.io/chainguard-images/scanner-test`.

```console
$ go run ./cmd/trivy image ghcr.io/chainguard-images/scanner-test
2023-04-11T11:33:52.571-0400	INFO	Vulnerability scanning is enabled
2023-04-11T11:33:52.572-0400	INFO	Secret scanning is enabled
2023-04-11T11:33:52.572-0400	INFO	If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2023-04-11T11:33:52.572-0400	INFO	Please see also https://aquasecurity.github.io/trivy/dev/docs/secret/scanning/#recommendation for faster secret detection
2023-04-11T11:33:52.589-0400	INFO	Detected OS: chainguard
2023-04-11T11:33:52.589-0400	INFO	Detecting Chainguard vulnerabilities...
2023-04-11T11:33:52.589-0400	INFO	Number of language-specific files: 0

ghcr.io/chainguard-images/scanner-test (chainguard 20230214)

Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
`

**Comment by knqyf263** [comment]
Are you sure `ghcr.io/chainguard-images/scanner-test` has no vulnerability now? Seems like it's been two months since the image was built as it shows `20230214`.

**Comment by luhring** [comment]
> Are you sure `ghcr.io/chainguard-images/scanner-test` has no vulnerability now? Seems like it's been two months since the image was built as it shows `20230214`.

`20230214` isn't when the image was built, that's the version of the package that manages the `/etc/os-release` file. You can find when the image was built with:

```shell
docker image inspect ghcr.io/chainguard-images/scanner-test | jq 'first | .Created'
```

The packages in this image are the latest version of each, so I wouldn't expect there to be any vulnerabilities.

**Comment by knqyf263** [comment]
Thanks! Will be included in [v0.40.0](https://github.com/aquasecurity/trivy/milestone/17).

**Comment by luhring** [comment]
Thanks so much!

**Pull request merged**
