### PR TITLE
fix(java): update logic to detect `pom.xml` file snapshot artifacts from remote repositories

### LINKED ISSUE #6374: 0.50.0 : big time increase of FS scanning vs 0.49.1
### Discussed in https://github.com/aquasecurity/trivy/discussions/6355

<div type='discussions-op-text'>

<sup>Originally posted by **jlamande** March 20, 2024</sup>
### Question

Scanning in a CI job with exactly the same setup (only changed the trivy version, scanned fs is the same).

With trivy 0.50.0 _(done multiple times with equivalent durations)_

```
time trivy fs --exit-code 0 --scanners vuln --ignore-unfixed "pom.xml"
2024-03-20T05:21:41.521Z	INFO	Vulnerability scanning is enabled
2024-03-20T05:25:47.917Z	INFO	Number of language-specific files: 1
2024-03-20T05:25:47.917Z	INFO	Detecting pom vulnerabilities...
pom.xml (pom)
=============
Total: 6 (UNKNOWN: 0, LOW: 0, MEDIUM: 2, HIGH: 4, CRITICAL: 0)
real	4m 7.63s
user	0m 12.08s
sys	0m 2.10s
```

With trivy 0.49.1 _(done multiple times with equivalent durations)_

```
time trivy fs --exit-code 0 --scanners vuln --ignore-unfixed "pom.xml"
2024-03-20T07:36:22.530Z	INFO	Vulnerability scanning is enabled
2024-03-20T07:36:30.896Z	INFO	Number of language-specific files: 1
2024-03-20T07:36:30.896Z	INFO	Detecting pom vulnerabilities...
pom.xml (pom)
=============
Total: 6 (UNKNOWN: 0, LOW: 0, MEDIUM: 2, HIGH: 4, CRITICAL: 0)

real	0m 9.59s
user	0m 6.63s
sys	0m 0.31s
```

Does anyone see the same behavior ?

Is there some new option to enable in 0.50 to avoid this time increase ?

### Target

Filesystem

### Scanner

Vulnerability

### Output Format

None

### Mode

Standalone

### Operating System

Docker

### Version

```bash
Version: 0.50.0
```
</div>

### PR DESCRIPTION
**Pull request by DmitriyLewen**
## Description
Maven splits release and snapshot repositories - https://github.com/apache/maven/blob/259404701402230299fe05ee889ecdf1c9dae816/maven-core/src/main/java/org/apache/maven/project/MavenProject.java#L144-L146.
Maven uses snapshot remote repos for snapshot artifacts[^1] and release remote repos + maven central for other artifacts:
- https://github.com/apache/maven/blob/259404701402230299fe05ee889ecdf1c9dae816/maven-compat/src/main/java/org/apache/maven/repository/legacy/resolver/transform/AbstractVersionTransformation.java#L76-L79
- https://github.com/apache/maven/blob/259404701402230299fe05ee889ecdf1c9dae816/maven-core/src/main/java/org/apache/maven/project/MavenProject.java#L767-L771

[^1]: Maven detects snapshot artifacts by artifact version - https://github.com/apache/maven/blob/259404701402230299fe05ee889ecdf1c9dae816/maven-artifact/src/main/java/org/apache/maven/artifact/DefaultArtifact.java#L482-L486

We need reproduce this logic:
- snapshot artifact
  - check snapshot repositories from pom file (`metadata.xml` -> `*.pom`)
- other artifacts
  - check releases repositories from pom file (only `*.pom`)
  - check maven central

Tests with `mvn` and `trivy`:

<details> <summary> snapshot version + snapshot repo enable </summary>
test pom.xml file:

  ```xml
  ...
  <dependencies>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>2.17.0-SNAPSHOT</version>
    </dependency>      
  </dependencies>

  <repositories>
    <repository>
      <id>sonatype-nexus-snapshots</id>
      <name>Sonatype Nexus Snapshots</name>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
      <releases><enabled>false</enabled></releases>
      <snapshots><enabled>true</enabled></snapshots>
    </repository>
  </repositories>
  ...
  ```

  mvn (`jackson-annotations` is child dependency of `jackson-databind`):
  ```bash
  ➜  6355 mvn dependency:resolve | grep jackson-annotations
  Downloading from sonatype-nexus-snapshots: https://oss.sonatype.org/content/repositories/snapshots/com/fasterxml/jackson/core/jackson-annotations/2.17.0-SNAPSHOT/maven-metadata.xml
  Downloaded from sonatype-nexus-snapshots: https://oss.sonatype.org/content/repositories/snapshots/com/fasterxml/jackson/core/jackson-annotations/2.17.0-SNAPSHOT/maven-metadata.xml (1.2 kB at 7.3 kB/s)
  Downloading from sonatype-nexus-snapshots: https://oss.sonatype.org/content/repositories/snapshots/com/fasterxml/jackson/core/jackson-annotations/2.17.0-SNAPSHOT/jackson-annotations-2.17.0-20240312.035235-10.pom
  Downloaded from sonatype-nexus-snapshots: https://oss.sonatype.org/content/repositories/snapshots/com/fasterxml/jackson/core/jackson-annotations/2.17.0-SNAPSHOT/jackson-annotations-2.17.0-20240312.035235-10.pom (7.0 kB at 42 kB/s)
  Downloading from sonatype-nexus-snapshots: https://oss.sonatype.org/content/repositories/snapshots/com/fasterxml/jackson/core/jackson-annotations/2.17.0-SNAPSHOT/jackson-annotations-2.17.0-20240312.035235-10.jar
  Downloaded from sonatype-nexus-snapshots: https://oss.sonatype.org/content/repositories/snapshots/com/fasterxml/jackson/core/jackson-annotations/2.17.0-SNAPSHOT/jackson-annotations-2.17.0-20240312.035235-10.jar (79 kB at 454 kB/s)
  [INFO]    com.fasterxml.jackson.core:jackson-annotations:jar:2.17.0-SNAPSHOT:compile -- module com.fasterxml.jackson.annotation
  ```

  trivy (need add logic for metadata.xml):
  ```bash
  ➜ ./trivy -d fs pom.xml | grep jackson-databind
  ...
  2024-03-29T09:32:49.948+0600	DEBUG	Resolving com.fasterxml.jackson.core:jackson-databind:2.17.0-SNAPSHOT...
  2024-03-29T09:32:53.265+0600	DEBUG	Failed to fetch from oss.sonatype.org/content/repositories/snapshots/com/fasterxml/jackson/core/jackson-databind/2.17.0-SNAPSHOT/jackson-databind-2.17.0-SNAPSHOT.pom
  ```
</details>

<details> <summary> snapshot version (maven central contains this version) + repositories disable </summary>
  
!!! This test shows that maven doesn't check central for snapshots.

  test pom.xml file (https://repo.maven.apache.org/maven2/ai/kassette/kassette-java-sdk/1.0.4-SNAPSHOT/kassette-java-sdk-1.0.4-SNAPSHOT.pom):

  ```xml
  ...
  <dependencies>
    <dependency>
      <groupId>ai.kassette</groupId>
      <artifactId>kassette-java-sdk</artifactId>
      <version>1.0.4-SNAPSHOT</version>
    </dependency>      
  </dependencies>
  ...
  ```

  mvn:
  ```bash
  ➜  6355 mvn dependency:resolve                           
  [ERROR] Failed to execute goal on project pom: Could not resolve dependencies for project root:pom:jar:1.0.0: The following artifacts could not be resolved: ai.kassette:kassette-java-sdk:jar:1.0.4-SNAPSHOT (absent): Could not find artifact ai.kassette:kassette-java-sdk:jar:1.0.4-SNAPSHOT -> [Help 1]
  ```

  trivy:
  ```bash
  ➜ ./trivy -d fs pom.xml                        
  2024-03-29T09:42:57.580+0600	DEBUG	Resolving ai.kassette:kassette-java-sdk:1.0.4-SNAPSHOT...
  2024-03-29T09:42:57.580+0600	DEBUG	ai.kassette:kassette-java-sdk:1.0.4-SNAPSHOT was not found in local/remote repositories
  ```
</details>

<details> <summary> release version + release repository enable </summary>
  
!!! This test shows that maven checks repositories from pom file before maven central

  test pom.xml file:

  ```xml
  ...
  <dependencies>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>2.17.0</version>
    </dependency>      
  </dependencies>

  <repositories>
    <repository>
      <id>sonatype-nexus-snapshots</id>
      <name>Sonatype Nexus Snapshots</name>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
      <releases><enabled>true</enabled></releases>
      <snapshots><enabled>false</enabled></snapshots>
    </repository>
  </repositories>

  ...
  ```

  mvn:
  ```bash
  ➜ mvn dependency:resolve
  Downloading from sonatype-nexus-snapshots: https://oss.sonatype.org/content/repositories/snapshots/com/fasterxml/jackson/core/jackson-databind/2.17.0/jackson-databind-2.17.0.pom
  Downloading from central: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.17.0/jackson-databind-2.17.0.pom
  Downloaded from central: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.17.0/jackson-databind-2.17.0.pom (21 kB at 52 kB/s)
  ```

  trivy:
  ```bash
  ➜ ./trivy -d fs pom.xml -f json --list-all-pkgs | grep jackson-annotations 
  ...
  2024-03-29T10:10:24.421+0600	DEBUG	Resolving com.fasterxml.jackson.core:jackson-databind:2.17.0...
  2024-03-29T10:10:25.149+0600	DEBUG	Failed to fetch from oss.sonatype.org/content/repositories/snapshots/com/fasterxml/jackson/core/jackson-databind/2.17.0/jackson-databind-2.17.0.pom
  ...
          "ID": "com.fasterxml.jackson.core:jackson-annotations:2.17.0",
  ```
</details>

## Changes for another PR:
Maven uses `metadata.xml` file to find `*.pom` file for `snapshots`.
e.g. (https://oss.sonatype.org/content/repositories/snapshots/com/fasterxml/jackson/core/jackson-annotations/2.17.0-SNAPSHOT/):
```bash
Downloading from sonatype-nexus-snapshots: https://oss.sonatype.org/content/repositories/snapshots/com/fasterxml/jackson/core/jackson-annotations/2.17.0-SNAPSHOT/maven-metadata.xml
Downloaded from sonatype-nexus-snapshots: https://oss.sonatype.org/content/repositories/snapshots/com/fasterxml/jackson/core/jackson-annotations/2.17.0-SNAPSHOT/maven-metadata.xml (1.2 kB at 171 B/s)
Downloading from sonatype-nexus-snapshots: https://oss.sonatype.org/content/repositories/snapshots/com/fasterxml/jackson/core/jackson-annotations/2.17.0-SNAPSHOT/jackson-annotations-2.17.0-20240312.035235-10.pom
Downloaded from sonatype-nexus-snapshots: https://oss.sonatype.org/content/repositories/snapshots/com/fasterxml/jackson/core/jackson-annotations/2.17.0-SNAPSHOT/jackson-annotations-2.17.0-20240312.035235-10.pom (7.0 kB at 33 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/jackson-parent/2.17/jackson-parent-2.17.pom
Downloaded from central: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/jackson-parent/2.17/jackson-parent-2.17.pom (6.5 kB at 22 kB/s)
```

## Related issues
- Close #6374

## Related PRs
- [x] #6171

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [x] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by knqyf263** [comment]
This change looks awesome! I have one question.

>snapshot artifact
>check snapshot repositories from pom file (metadata.xml -> *.pom)

What is `metadata.xml`? I didn't find it tried to extract repositories from `metadata.xml`. I might be missing something.

**Comment by DmitriyLewen** [comment]
IIUC `metadata.xml` file contains info about latest versions of jar, pom, etc. for snapshot version.
e.g. https://oss.sonatype.org/content/repositories/snapshots/com/fasterxml/jackson/core/jackson-annotations/2.17.0-SNAPSHOT/maven-metadata.xml

Take a look this `mvn` log:
```bash
Downloading from sonatype-nexus-snapshots: https://oss.sonatype.org/content/repositories/snapshots/com/fasterxml/jackson/core/jackson-annotations/2.17.0-SNAPSHOT/maven-metadata.xml
Downloaded from sonatype-nexus-snapshots: https://oss.sonatype.org/content/repositories/snapshots/com/fasterxml/jackson/core/jackson-annotations/2.17.0-SNAPSHOT/maven-metadata.xml (1.2 kB at 171 B/s)
Downloading from sonatype-nexus-snapshots: https://oss.sonatype.org/content/repositories/snapshots/com/fasterxml/jackson/core/jackson-annotations/2.17.0-SNAPSHOT/jackson-annotations-2.17.0-20240312.035235-10.pom
Downloaded from sonatype-nexus-snapshots: https://oss.sonatype.org/content/repositories/snapshots/com/fasterxml/jackson/core/jackson-annotations/2.17.0-SNAPSHOT/jackson-annotations-2.17.0-20240312.035235-10.pom (7.0 kB at 33 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/jackson-parent/2.17/jackson-parent-2.17.pom
Downloaded from central: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/jackson-parent/2.17/jackson-parent-2.17.pom (6.5 kB at 22 kB/s)
```
mvn checks https://oss.sonatype.org/content/repositories/snapshots/com/fasterxml/jackson/core/jackson-annotations/2.17.0-SNAPSHOT/maven-metadata.xml -> takes version for pom (`<value>2.17.0-20240312.035235-10</value>`) -> check url with this version (https://oss.sonatype.org/content/repositories/snapshots/com/fasterxml/jackson/core/jackson-annotations/2.17.0-SNAPSHOT/jackson-annotations-2.17.0-20240312.035235-10.pom)

**Comment by knqyf263** [comment]
Thanks for explaining. I got it. So, it sounds like we also need to fetch `metadata.xml` to identify the latest version. I'm wondering if our current logic works.
https://github.com/aquasecurity/trivy/blob/6c19ae700e6d7e34c7b2a97c24734ad40e9f667e/pkg/dependency/parser/java/pom/parse.go#L651-L661

**Comment by DmitriyLewen** [comment]
I don't have much experience with custom repositories.
But I think that if repository uses structure as maven central (without metadata.xml) (if this is possible) - our logic should work.

> it sounds like we also need to fetch metadata.xml to identify the latest version

I thought I'd add this to another PR. But I can do it in this PR.

**Review by knqyf263 — APPROVED** [review]

**Comment by knqyf263** [comment]
When the artifact is `org.example:example-api:2.0.0-SNAPSHOT`, the current logic tries to access `https://oss.sonatype.org/content/repositories/snapshots/org/example/example-api/2.0.0-SNAPSHOT/example-api-2.0.0-SNAPSHOT.pom`, right?  But it should be `https://oss.sonatype.org/content/repositories/snapshots/org/example/example-api/2.0.0-SNAPSHOT/maven-metadata.xml`. Am I correct?

**Comment by knqyf263** [comment]
Anyway, it's not a bug from this PR. I'll merge this one, and we'll implement the snapshot logic later.

**Comment by DmitriyLewen** [comment]
> When the artifact is org.example:example-api:2.0.0-SNAPSHOT, the current logic tries to access https://oss.sonatype.org/content/repositories/snapshots/org/example/example-api/2.0.0-SNAPSHOT/example-api-2.0.0-SNAPSHOT.pom, right? But it should be https://oss.sonatype.org/content/repositories/snapshots/org/example/example-api/2.0.0-SNAPSHOT/maven-metadata.xml. Am I correct?

`mvn` first checks `https://oss.sonatype.org/content/repositories/snapshots/org/example/example-api/2.0.0-SNAPSHOT/maven-metadata.xml`
But if this file doesn't exist - mvn will try to check `https://oss.sonatype.org/content/repositories/snapshots/org/example/example-api/2.0.0-SNAPSHOT/example-api-2.0.0-SNAPSHOT.pom`

**Comment by knqyf263** [comment]
So, Trivy currently accesses the following URL and fails as it's 404.
https://oss.sonatype.org/content/repositories/snapshots/com/fasterxml/jackson/core/jackson-annotations/2.17.0-SNAPSHOT/jackson-annotations-2.17.0-SNAPSHOT.pom

It looks like Trivy tries snapshot repositories and most likely fails because Trivy doesn't support `maven-metadata.xml`. Please correct me if I'm wrong.

**Comment by DmitriyLewen** [comment]
> In short, Trivy tries snapshot repositories and most likely fails because Trivy doesn't support maven-metadata.xml

if the repository uses `maven-metadata.xml` files, you are right.

thus `oss` doesn't currently support

**Comment by knqyf263** [comment]
I randomly picked up some artifacts in the snapshot repository. All of them use `maven-metadata.xml`.
https://oss.sonatype.org/content/repositories/snapshots/com/zendesk/jazon/jazon-core/maven-metadata.xml

Is it possible that a snapshot repository doesn't use `maven-metadata.xml`?

**Comment by DmitriyLewen** [comment]
as i wrote in https://github.com/aquasecurity/trivy/pull/6412#issuecomment-2058459718:
mvn checks `<artifactid>-<version>.pom` file if `maven-metadata.xml` file doesn't exist - so i think this is possible, but i didn't see these repositories 😄

**Pull request merged**
