### PR TITLE
db: Update trivy-db to include CVSS score info

### PR DESCRIPTION
**Pull request by simar7**
After https://github.com/aquasecurity/trivy-db/pull/48 gets merged, Trivy can also display the CVSS Score attached to a severity along with the vector. 

image

Addresses: https://github.com/aquasecurity/trivy/issues/92

Signed-off-by: Simarpreet Singh <simar@linux.com>

### CODE REVIEW

**Comment by knqyf263** [comment]
I tested this branch in my environment and realized that go.mod pointed to the old commit. We need to update go.mod.

**Comment by simar7** [comment]
> I tested this branch in my environment and realized that go.mod pointed to the old commit. We need to update go.mod.

I updated it. Would you give it another try @knqyf263?

**Comment by knqyf263** [comment]
I tested this branch and I found they were snake case...

```
        "CVSS": {
          "nvd": {
            "v2_vector": "AV:L/AC:M/Au:N/C:P/I:N/A:N",
            "v3_vector": "CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:H/I:N/A:N",
            "v2_score": 1.9,
            "v3_score": 4.7
          },
          "redhat": {
            "v3_vector": "CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
            "v3_score": 5.5
          }
        },
```

All other keys are upper camel case.

**Comment by simar7** [comment]
> I tested this branch and I found they were snake case...
> 
> ```
>         "CVSS": {
>           "nvd": {
>             "v2_vector": "AV:L/AC:M/Au:N/C:P/I:N/A:N",
>             "v3_vector": "CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:H/I:N/A:N",
>             "v2_score": 1.9,
>             "v3_score": 4.7
>           },
>           "redhat": {
>             "v3_vector": "CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
>             "v3_score": 5.5
>           }
>         },
> ```
> 
> All other keys are upper camel case.

OK I've updated here https://github.com/aquasecurity/trivy-db/pull/50/files

**Comment by simar7** [comment]
I update trivy-db to include the new CamelCase changes. Could you take another look at it @knqyf263?

**Pull request merged**
