### PR TITLE
Modify cache-dir usage comment

### PR DESCRIPTION
**Pull request by homoluctus**
Hi.

Trivy cache dir is changed by `--cache-dir` option.
But image cache is not changed and stored in /path/to/cache/fanal ( /path/to/cache/ = os.UserCacheDir() ).
So, I changed `--cache-dir` option usage comment.

If we want to change image cache dir too, we need to fix [aquasecurity/fanal/utils/utils.go - CacheDir](https://github.com/aquasecurity/fanal/blob/master/utils/utils.go#L14).

### CODE REVIEW

**Comment by knqyf263** [comment]
@homoluctus Could you implement `--cache-dir` to change the image cache path?

**Comment by homoluctus** [comment]
@knqyf263 

OK 👍
I'll try to implement.

I will modify aquasecurity/fanal code too, is it okay?

**Comment by knqyf263** [comment]
@homoluctus Absolutely. I'll merge this PR once.

**Comment by knqyf263** [comment]
Thanks.

**Pull request merged**
