### PR TITLE
feat(repo): support local repositories

### PR DESCRIPTION
**Pull request by knqyf263**
## Description
`trivy repo` now scans local repositories as well as remote repositories.

### Usage

```
$ trivy repo --scanners vuln /path/to/repo
```

It is equivalent to `trivy fs`.

## Related issues
- Close https://github.com/aquasecurity/trivy/issues/4888

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Review by DmitriyLewen — COMMENTED** [review]
LGTM.
I understand that we are using `fs Artifact` for `repo` mode and it looks like there is no case we could miss for `fs` mode, but maybe we want to use `args.command == 'fs'` for some test cases?

**Comment by knqyf263** [comment]
>but maybe we want to use args.command == 'fs' for some test cases?

Do you mean integration tests?

**Comment by DmitriyLewen** [comment]
right.

**Comment by knqyf263** [comment]
@DmitriyLewen Added in https://github.com/aquasecurity/trivy/pull/4890/commits/d35fa12b5c4236a8afffc1d4c0b635c833396ec3. I'm not sure if it will pass tests, but does it answer your question?

**Comment by DmitriyLewen** [comment]
yes. Thanks!

**Review by DmitriyLewen — APPROVED** [review]
LGTM

**Pull request merged**
