### PR TITLE
Using trivy with jenkins

### PR DESCRIPTION
**Pull request by tofuatjava**

### CODE REVIEW

**Comment by krol3** [comment]
@tofuatjava we migrated to mkdocs, are you still working in that?

**Comment by tofuatjava** [comment]
Hi Carol,
Its already working. and released with the "warnings ng plugin" in jenkins.

So I only want to add this information to your documentation. No codechange
in your repository.

Thomas

Am Mo., 22. März 2021 um 03:42 Uhr schrieb Carol Valencia <
***@***.***>:

**Comment by krol3** [comment]
@tofuatjava  could you please the jenkins integration in https://github.com/aquasecurity/trivy/tree/main/docs/integrations?

**Comment by hectoralicea** [comment]
> @tofuatjava could you please the jenkins integration in https://github.com/aquasecurity/trivy/tree/main/docs/integrations?

yes, please.  adding the jenkins pipeline sample would be very helpful

**Comment by ebarped** [comment]
i agree, having an .md in the docs/advanced/integrations, the same as with gitlab-ci, travis-ci, etc would be helpful

**Comment by krol3** [comment]
@ebarped we have a PR with jenkins in progress https://github.com/aquasecurity/trivy/pull/1266

**Pull request closed without merging**
