### PR TITLE
ci: Add support for `linux/riscv64`

### PR DESCRIPTION
**Pull request by michalbiesek**
## Description

Add support for RISC-V 64 bit.

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [x] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by knqyf263** [comment]
@michalbiesek Do you actually need riscv64 support? We're recently facing a disk space issue in our release workflow. Therefore, we're carefully adding more arches now.

**Comment by michalbiesek** [comment]
Hi @knqyf263, I am using Trivy in one of my home projects with Go and RISCV64 SBC.
On the other hand, I understand your argumentation and disk space considerations. Please let me know your preferred approach with this Pull Request - should it be closed, or do you think I need to perform additional changes?

**Comment by knqyf263** [comment]
@michalbiesek We'd like to see how much demand there is from the community. Can you please open a discussion first? I'll convert this PR to a draft until we confirm many users need riscv64 support.

**Comment by itaysk** [comment]
I'm closing this as there isn't a widespread need for this. you can still build Trivy locally or even in GitHub but not as official Trivy release for now.

**Pull request closed without merging**
