### PR TITLE
refactor: merge trivy-iac

### PR DESCRIPTION
**Pull request by nikpivkin**
## Related issues
- Close https://github.com/aquasecurity/trivy/issues/5626

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [x] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Review by simar7 — APPROVED** [review]
lgtm to @nikpivkin - just need to iron out a merge conflict

**Comment by simar7** [comment]
@knqyf263 when you have time, could you help us review it?

**Comment by knqyf263** [comment]
Don't we want to keep the commit history?
https://github.com/aquasecurity/trivy/pull/2356

**Comment by simar7** [comment]
> Don't we want to keep the commit history?
> #2356

trivy-iac doesn't have much of a commit history as of today. As for defsec repo itself, we split it up into three different repos and duplicating commit history would be unnecessary in each.

**Comment by knqyf263** [comment]
OK, but the change is huge. I need some time.

**Comment by simar7** [comment]
Requires https://github.com/aquasecurity/trivy-iac/pull/72 to be merged first and then this PR must be updated. Overall it'll be a smaller change once the aforementioned change is merged.

**Comment by simar7** [comment]
@nikpivkin can we close this one?

**Pull request closed without merging**
