### PR TITLE
docs: add 'Signature Verification' guide

### PR DESCRIPTION
**Pull request by nikpivkin**
## Related issues
- Close https://github.com/aquasecurity/trivy/issues/3881

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [x] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by knqyf263** [comment]
@nikpivkin LGTM! Thanks 👍 

@AnaisUrlichs Where do we want to add this page? NIkita added it to "getting started".

**Review by AnaisUrlichs — APPROVED** [review]

**Review by AnaisUrlichs — COMMENTED** [review]
I would like to add that to supply-chain https://aquasecurity.github.io/trivy/v0.43/docs/supply-chain/sbom/
what do you think @knqyf263

**Comment by itaysk** [comment]
no supply chain is about how trivy is securing the supply chain. this should be somewhere around the installation docs

**Comment by knqyf263** [comment]
It is not a functionality of Trivy. As @itaysk, it is more like installation, but I want to keep the installation page as much as simple so that people can easily start using Trivy. Should we add a new page under `getting started`?

**Comment by itaysk** [comment]
If not under installation, maybe under "advanced"? we also have air-gapped setup guide there

**Comment by AnaisUrlichs** [comment]
Oh sorry, I did not look at the PR properly -- maybe under a separate page e.g. https://aquasecurity.github.io/trivy/v0.43/trivy-signature-verification

**Comment by nikpivkin** [comment]
@itaysk  @AnaisUrlichs  Okay, I'll wait for your decision and move the documentation to the appropriate section.

**Review by knqyf263 — APPROVED** [review]

**Pull request merged**
