### PR TITLE
ci: auto generation configs for deb packages

### LINKED ISSUE #1692: Installation on Ubuntu 21.10 Impish not working
## Description

Installing Trivy according to [official instruction here](https://aquasecurity.github.io/trivy/v0.21.2/getting-started/installation/#debianubuntu)

Installation via `apt` on the latest version of Ubuntu is not supported.

## What did you expect to happen?
Successfull installation

## What happened instead?
```
$ sudo apt-get update
Err:12 https://aquasecurity.github.io/trivy-repo/deb impish Release
  404  Not Found [IP: 185.199.110.153 443]
```

### PR DESCRIPTION
**Pull request by afdesk**
## Description
Added auto generation `conf/distributions` for building deb packages.

## Related issues
- Close #1692 
- the first PR #1775

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by afdesk** [comment]
> Oh, I might be missing something. Don't we remove old releases?
> 
> https://github.com/aquasecurity/trivy/blob/1b4d38629c642117fb6801aeaa1c7d3b6b2d6a27/ci/deploy-deb.sh#L10-L12
> 
> For example, what happens to Debian 8 after it reaches EOL? I wanted to keep the binary for Debian 8.

if i understand correctly, this script removes only supported version for update:
https://github.com/aquasecurity/trivy/blob/1b4d38629c642117fb6801aeaa1c7d3b6b2d6a27/ci/deploy-deb.sh#L3-L13

**Comment by afdesk** [comment]
or i missed something now

**Comment by knqyf263** [comment]
Seems like so. You can revert a commit with `--all`. I'm sorry for my bad. I misunderstood all releases were removed.

**Comment by afdesk** [comment]
maybe i miss something, 
the my idea was about generation `distributions` file automatically and so we should build it with `--all` flag.
now this file is static: https://github.com/aquasecurity/trivy-repo/blob/main/deb/conf/distributions
we don't change the rest of the script, right?

**Pull request closed without merging**
