### PR TITLE
chore(deps): bump trivy-kubernetes version

### LINKED ISSUE #7011: Error when scanning a Kubernetes workload or ServiceAccount with an empty item in `imagePullSecrets` array
### Discussed in https://github.com/aquasecurity/trivy/discussions/6928

<div type='discussions-op-text'>

<sup>Originally posted by **matheusfm** June 13, 2024</sup>
### Description

Trivy fails when scanning a Kubernetes workload with an empty item in `imagePullSecrets` array:
```yaml
  imagePullSecrets:
    - {}
```

### Desired Behavior

I expect this object to be scanned without errors, ignoring the empty `imagePullSecrets` item.

### Actual Behavior

Trivy fails with the following output:
```
2024-06-13T17:04:23-03:00	FATAL	Fatal error	get k8s artifacts with node info error: failed getting auth for gvr: /v1, Resource=pods - getting secret by name: default/: resource name may not be empty
```

### Reproduction Steps

1. Create a kind cluster

```bash
kind create cluster
```

2. Create a pod with an empty item in `imagePullSecrets` array

```
cat << EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    role: nginx
spec:
  imagePullSecrets:
    - {}
  containers:
    - name: nginx
      image: nginx
EOF
```

3. Run trivy:

```
trivy k8s --report summary
```

### Target

Kubernetes

### Scanner

Vulnerability

### Output Format

Table

### Mode

Standalone

### Debug Output

```bash
2024-06-13T17:04:22-03:00	DEBUG	Parsed severities	severities=[UNKNOWN LOW MEDIUM HIGH CRITICAL]
2024-06-13T17:04:22-03:00	DEBUG	Ignore statuses	statuses=[]
2024-06-13T17:04:23-03:00	FATAL	Fatal error	get k8s artifacts with node info error: failed getting auth for gvr: /v1, Resource=pods - getting secret by name: default/: resource name may not be empty
```

### Operating System

linux

### Version

```bash
Version: 0.52.1
Vulnerability DB:
  Version: 2
  UpdatedAt: 2024-06-10 12:13:28.957657425 +0000 UTC
  NextUpdate: 2024-06-10 18:13:28.957657255 +0000 UTC
  DownloadedAt: 2024-06-10 13:43:20.101006187 +0000 UTC
Java DB:
  Version: 1
  UpdatedAt: 2024-06-10 01:05:31.416428614 +0000 UTC
  NextUpdate: 2024-06-13 01:05:31.416428444 +0000 UTC
  DownloadedAt: 2024-06-10 13:53:07.844808071 +0000 UTC
```

### Checklist

- [X] Run `trivy image --reset`
- [X] Read [the troubleshooting](https://aquasecurity.github.io/trivy/latest/docs/references/troubleshooting/)</div>

### PR DESCRIPTION
**Pull request by matheusfm**
## Description

This PR bumps [trivy-kubernetes](https://github.com/aquasecurity/trivy-kubernetes) from `87c0f9c7bcf4` to `f39bd949a3ac`.

See full diff in [compare view](https://github.com/aquasecurity/trivy-kubernetes/compare/87c0f9c7bcf4...f39bd949a3ac)

## Related issues
- Close #7011

## Related PRs
- [x] https://github.com/aquasecurity/trivy-kubernetes/pull/362

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by chen-keinan** [comment]
@matheusfm I realize now that bumping `trivy-kubernetes v0.6.7-0.20240625124151-899963fa9335` is depend on this pr #6861 that's why tests are failing.

maybe it better I'll bump latest `trivy-kubernetes` it on this PR  #6861  and close your PR.
wdyt ?

**Comment by matheusfm** [comment]
@chen-keinan 
I’m ok with either option, whatever you think is best. 
I don’t mind waiting for PR #6861 to be merged and updating my branch afterwards.

**Comment by chen-keinan** [comment]
@matheusfm you can rebase your branch with upstream now, #6861 has been merged

**Comment by matheusfm** [comment]
@chen-keinan 
I've updated my branch. Note that now trivy-kubernetes version is being bumped to the latest commit (`f39bd949a3ac`).

**Review by chen-keinan — APPROVED** [review]

**Comment by chen-keinan** [comment]
@knqyf263 please have a look at this PR

**Review by knqyf263 — APPROVED** [review]

**Pull request merged**
