### PR TITLE
chore(helm): remove psp from helm manifest

### LINKED ISSUE #1305: Remove PodSecurityPolicy in the helm manifest
Remove PodSecurityPolicy in the helm manifest

```
helm install trivy . --namespace trivy --create-namespace

W1018 19:47:44.637292   21571 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W1018 19:47:44.745250   21571 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
```

### PR DESCRIPTION
**Pull request by kaitoii11**
fix #1305

### CODE REVIEW

**Comment by krol3** [comment]
@kaitoii11 similar to ingress, we need to support the current PSP and the new approach using [Pod Security Standards’ PSPs](https://kubernetes.io/docs/concepts/security/pod-security-standards/)

The ingress supporting both versions: https://github.com/aquasecurity/trivy/blob/main/helm/trivy/templates/ingress.yaml#L3

**Comment by knqyf263** [comment]
>@kaitoii11 similar to ingress, we need to support the current PSP and the new approach using Pod Security Standards’ PSPs

@krol3 How can we fix this PR?

**Review by krol3 — CHANGES_REQUESTED** [review]
@kaitoii11  sorry for the delay. Before remove the PodSecurityPolicy. we could add some validations using the SecurityContext in the Pod Level. 

For example, we could drop the capabilities using SecurityContext. https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod

Screen Shot 2022-02-07 at 15 10 43

**Review by krol3 — APPROVED** [review]

**Comment by krol3** [comment]
LGTM we are checking if it's enabled the PSP

**Comment by knqyf263** [comment]
Thanks!

**Pull request merged**
