### PR TITLE
chore(deps): bump github.com/Masterminds/sprig/ from v2.22.0 to v3.2.2

### LINKED ISSUE #1809: Update to latest sprig version
Currently trivy seems to use an very old sprig version, so that many function like: Regex, mustToJson etc. are not supported. Would it be possible to update the version, so that it is possible to use the newest sprig fuction documented in: http://masterminds.github.io/sprig/

In the report documentation is a reference to sprig an many commands are currently not compatible with the latest trivy version: https://aquasecurity.github.io/trivy/v0.24.2/vulnerability/examples/report/

### PR DESCRIPTION
**Pull request by DmitriyLewen**
## Description

- Sprig has been updated from v2.22.0 to v3.2.2.
- Updated link to information about *asff template* in [report doc](https://github.com/aquasecurity/trivy/blob/main/docs/vulnerability/examples/report.md).

## Related issues
- Close #1809 

## Checklist
- [x] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy/blob/main/CONTRIBUTING.md) to this repository.
- [x] I've followed the [conventions](https://github.com/aquasecurity/trivy/blob/main/CONTRIBUTING.md#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by knqyf263** [comment]
@DmitriyLewen Thanks! Did you confirm our templates work properly with the new version of sprig?

**Comment by DmitriyLewen** [comment]
@knqyf263 Yes, i do. Templates work correctly.

**Comment by knqyf263** [comment]
@AndreyLevchenko Can you please review it first?

**Comment by AndreyLevchenko** [comment]
@knqyf263 @DmitriyLewen 
Looks good to me

**Pull request merged**
