### PR TITLE
gracefully handle invalid lockfiles

### LINKED ISSUE #179: invalid composer.lock format: invalid character ',' looking for beginning of object key string
Hi,

I'm running trivy like so
`docker run --rm -v /var/run/docker.sock:/var/run/docker.sock     -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy lss:latest`

```
+ trivy --exit-code 1 --severity HIGH,CRITICAL --quiet --input docker/image

2019-10-04T09:24:19.801Z	INFO	Updating vulnerability database...

2019-10-04T09:25:33.288Z	INFO	Updating nvd data...

2019-10-04T09:26:18.586Z	INFO	Updating alpine data...

2019-10-04T09:26:23.762Z	INFO	Updating redhat data...

2019-10-04T09:26:27.712Z	INFO	Updating debian data...

2019-10-04T09:26:39.378Z	INFO	Updating debian-oval data...

2019-10-04T09:26:46.362Z	INFO	Updating ubuntu data...

2019-10-04T09:26:55.645Z	INFO	Detecting Alpine vulnerabilities...

2019-10-04T09:26:55.649Z	FATAL	error in image scan: failed to scan libraries: failed to analyze libraries: failed to analyze libraries: invalid composer.lock format: invalid character ',' looking for beginning of object key string

```
Anyone else come across this?

Regards

### PR DESCRIPTION
**Pull request by imnotjames**
scan each file individually when we are scanning an image
so that we are able to handle the failed parse of a lockfile
without bailing out entirely.

instead, emit a warning

Closes #179

### CODE REVIEW

**Comment by imnotjames** [comment]
I'm not sure how to add a test to exhibit this behavior.

**Comment by carlad** [comment]
Would love to get this PR reviewed. The team I'm working with want to use this tool but are blocked by the `invalid composer.lock` error.

**Comment by knqyf263** [comment]
@carlad I'm sorry for the late reply. After merging this PR, you can ignore composer.lock under vendor dir.
https://github.com/aquasecurity/trivy/pull/279

**Comment by knqyf263** [comment]
We added `--skip-dirs` to avoid scanning invalid lockfiles. If we need this feature, let me reopen the PR. Thank you for your contribution.

**Pull request closed without merging**
