### PR TITLE
Update cks.md

### PR DESCRIPTION
**Pull request by johnsoncharlie98**
Practice exam recommended by CKS professionals, contains comprehensive collection of questions that cover all core exam topics.

## Related issues
- Close #XXX

## Related PRs
- [ ] #XXX
- [ ] #YYY

Remove this section if you don't have related PRs.

## Checklist
- [ ] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [ ] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by knqyf263** [comment]
@AnaisUrlichs Can you please take a look?

**Comment by AnaisUrlichs** [comment]
Hi [johnsoncharlie98](https://github.com/johnsoncharlie98), thank you for adding the resource. How did you come across the cks section in Trivy? Since I saw your PR last week, I have been wondering about the value of this question and knowing how/that people find it, helps a lot in deciding what to do with it moving forward.

Initially, I wanted to keep it to resources related to Trivy and other exceptionally useful resources. Otherwise, this section could be a lot bigger. 

Thank you!

**Comment by AnaisUrlichs** [comment]
@johnsoncharlie98 awesome, thank you for sharing. Feel free to add any resources that you found particularly useful to the changes in this PR

**Comment by knqyf263** [comment]
Please see https://aquasecurity.github.io/trivy/v0.45/community/contribute/pr/

**Pull request closed without merging**
