### PR TITLE
fix: Fixed the test cases for iam passing role

### PR DESCRIPTION
**Pull request by r-khurram**
## Description
Added a field `DisableEmbeddedPolicies: true`  in the test case. So that test cases can only use the given policy. 

## Related issues
- Close https://github.com/aquasecurity/trivy/issues/4591

## Related PRs
- [ ] #XXX
- [ ] #YYY

Remove this section if you don't have related PRs.

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [x] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [x] I've added usage information (if the PR introduces new options)
- [x] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Review by simar7 — APPROVED** [review]

**Comment by simar7** [comment]
lgtm but could you please sign the CLA?

**Review by simar7 — APPROVED** [review]

**Comment by simar7** [comment]
@knqyf263 - I think @r-khurram has signed the CLA but the checker has got stuck. Can we merge this manually?

**Comment by knqyf263** [comment]
I didn't see the CLA signature. How did you get to know @r-khurram signed?

**Comment by simar7** [comment]
> I didn't see the CLA signature. How did you get to know @r-khurram signed?

@r-khurram claims offline that he has signed. @r-khurram can you please confirm if you have signed?

**Comment by r-khurram** [comment]
> > I didn't see the CLA signature. How did you get to know @r-khurram signed?
> 
> @r-khurram claims offline that he has signed. @r-khurram can you please confirm if you have signed?

image
@simar7 here You can see when i clicked on the CLA

**Comment by itaysk** [comment]
the CLA bot said what the problem is

> Phaedra Solutions seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by r-khurram** [comment]
> the CLA bot [said](https://github.com/aquasecurity/trivy/pull/4667#issuecomment-1597094670) what the problem is
> 
> > Phaedra Solutions seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

@itaysk  Thanks i have fixed that.

**Comment by simar7** [comment]
Closing as I've cut https://github.com/aquasecurity/trivy/pull/4723 that supersedes this.

**Pull request closed without merging**
