### PR TITLE
feat(template) Add misconfigurations to gitlab codequality report

### PR DESCRIPTION
**Pull request by natefear**
Gitlab codequality report for misconfigurations was missing

Usage example:
trivy fs --security-checks config,vuln --format template --template "@contrib/gitlab-codequality.tpl" -o report.json {folder}

## Checklist
- [x] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy/blob/main/CONTRIBUTING.md) to this repository.
- [x] I've followed the [conventions](https://github.com/aquasecurity/trivy/blob/main/CONTRIBUTING.md#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [x] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [x] I've added usage information (if the PR introduces new options)
- [x] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by krol3** [comment]
@natefear thanks for your contribution, do you think that you could update the documentation about how to use it, some screenshots about the report will be nice to have in the documentation too. 

https://aquasecurity.github.io/trivy/v0.23.0/advanced/integrations/gitlab-ci/

**Comment by natefear** [comment]
Hi @krol3 I'll add some screen shots in a bit I just would like to discuss the template further first :)

At present the gitlab-codequality.tpl template will set the  package name and version as the path for vulnerabilities (cve's)        https://github.com/aquasecurity/trivy/blob/378b115deceba50b18c9120b1d90e776b50d88da/contrib/gitlab-codequality.tpl#L31 whilst this is more useful when doing an image scan because the target https://github.com/aquasecurity/trivy/blob/378b115deceba50b18c9120b1d90e776b50d88da/contrib/gitlab-codequality.tpl#L5 is just the  image name e.g. `aquasec/trivy (alpine 3.15.0)` when scanning trivy, this is however not as useful as it could be when doing filesystem scan as in this scenario the `.Target` key is able to point to the exact file the vulnerability (cve) originates from e.g. a pip file and you can then click on it in the Gitlab UI to take you to the file.

To try to get the best of both, should I:

1. Always set path to $target for vulnerabilities (cve's) but include the package name and version in the description
2. Try to get the `ArtifactType` field exposed to the report templating logic then use this to create conditions - at present the untemplated json report includes an `ArtifactType` field (see code block below) which lets you know if the report is from an image or file system scan however the templating fuction only knows about the contents of the results array. See error: "output template" at <.ArtifactType>: can't evaluate field ArtifactType in type report.Results"

```
  "SchemaVersion": 2,
  "ArtifactName": ".",
  "ArtifactType": "filesystem",
  "Metadata": {
    "ImageConfig": {
      "architecture": "",
      "created": "0001-01-01T00:00:00Z",
      "os": "",
      "rootfs": {
        "type": "",
        "diff_ids": null
      },
      "config": {}
    }
  },
  "Results": [
```

**Comment by natefear** [comment]
@knqyf263 would I be able to get your thoughts on the above ^? :)

**Comment by knqyf263** [comment]
To be honest, I've never used GitLab Code Quality, but it seems to be associated with the project's files. I feel like we should use `path` for file paths. #1 looks good from that perspective.

**Review by krol3 — COMMENTED** [review]
Please add the screenshots in 'gitlab-ci.md' about the expected result in the Gitlab/codeQuality too.

**Comment by knqyf263** [comment]
@natefear Thanks for the detailed explanation. It looks good.

**Comment by natefear** [comment]
Added a screen shot of a sample output using the template to the docs, let me know if you want me to crop the screen shot further :) thanks

**Comment by knqyf263** [comment]
Thanks, but the link seems to be broken.

image

You can see the doc by running `make mkdocs-serve` and visiting http://localhost:8000. Also, you can refer to other places.
https://github.com/aquasecurity/trivy/blob/9e08bd44fb3c50360d4b992a4d843824c8272c95/docs/advanced/modes/standalone.md?plain=1#L7

**Comment by natefear** [comment]
@knqyf263 It works [here](https://github.com/aquasecurity/trivy/blob/8cab693fbad4755f14346f4fcc78613514d20bf6/docs/advanced/integrations/gitlab-ci.md) and locally via mkdocs, I think it's broken when viewing in blob mode in the files changes UI because it's trying to look in the main branch -> https://github.com/aquasecurity/trivy/blob/main/docs/imgs/gitlab-codequality.png which is 404

**Comment by natefear** [comment]
fixed failing integration tests - https://github.com/aquasecurity/trivy/runs/5410960038?check_suite_focus=true#step:4:352 by updating the expected output https://github.com/aquasecurity/trivy/pull/1756/files#diff-987afca26799d63f38791b6b5f7f8e7dce0b1d123ea64db563f7e59ba92cae2fR6

**Comment by knqyf263** [comment]
>@knqyf263 It works [here](https://github.com/aquasecurity/trivy/blob/8cab693fbad4755f14346f4fcc78613514d20bf6/docs/advanced/integrations/gitlab-ci.md) and locally via mkdocs, I think it's broken when viewing in rich diff mode in the files changes UI because it's trying to look in the main branch -> https://github.com/aquasecurity/trivy/blob/main/docs/imgs/gitlab-codequality.png which is 404

We use MkDocs and it must work here.
https://aquasecurity.github.io/trivy/v0.24.2/advanced/integrations/gitlab-ci/

**Comment by knqyf263** [comment]
Oh, I missed you said it worked locally via mkdocs. Let me check it again.

**Comment by knqyf263** [comment]
Again, it doesn't work. The path seems to be wrong.
image

**Comment by natefear** [comment]
@knqyf263 ahh you're right apologies I'd not pushed the extra `../`, I've pushed it now

**Comment by natefear** [comment]
@knqyf263 @krol3 can someone kick the tests off, approve and merge this if you think it's ready :) thanks

the tests had already run successfully once, but I've had to rebase because the main branch has been updated

**Comment by natefear** [comment]
@knqyf263 @krol3 -  by the time someone responds to run the tests or approves the PR my branch becomes out of sync with main :( try again please?

**Comment by natefear** [comment]
@knqyf263 @krol3 not sure if one of you triggered the tests, but they're done and ready for approval :) thanks

**Review by krol3 — CHANGES_REQUESTED** [review]
Nice improvement! Please consider this PR https://github.com/aquasecurity/trivy/pull/1801
"Updated the GitLab CI examples to use the environment variables TRIVY_CACHE_DIR and TRIVY_NO_PROGRESS instead of providing them for every commands"

**Comment by natefear** [comment]
@krol3 Seems odd that you want me to include the proposed changes from someone else's PR in this one? shouldn't you be letting me merge and then asking other PR author to rebase so they can add it where relevant

**Comment by krol3** [comment]
@natefear, I was trying to tell you, is that you'll probably need to do a remerge. I will focus on reviewing your PR

**Comment by natefear** [comment]
@krol3 ahh okay sorry didn't see there MR had already been approved :) I guess I'll wait for them to merge

**Comment by natefear** [comment]
@krol3 @knqyf263 rebased to include the CI env var changes

**Review by krol3 — APPROVED** [review]
LGTM. Thanks @natefear

**Comment by natefear** [comment]
@krol3 @knqyf263 are either of you authorised to merge :) ty

**Review by knqyf263 — APPROVED** [review]

**Comment by knqyf263** [comment]
Thanks!

**Pull request merged**
