### PR TITLE
docs: add community integrations

### PR DESCRIPTION
**Pull request by knqyf263**
Close https://github.com/aquasecurity/trivy/issues/1222 and https://github.com/aquasecurity/trivy/issues/967

### CODE REVIEW

**Review by itaysk — COMMENTED** [review]
some thoughts:
1. the line between "community integrations" and other existing integrations is not clear
1. there's already a page about using trivy in circle ci, doesn't this orb belong there?
1. what about other examples like recently Semaphore CI?
1. what about the VS Code extension?
1. since some integrations-related content might be in other places and some in our docs, maybe it's better to have one big table of all integrations (not just "community") with links to the relevant docs. some of the links will be external and some will be internal.

**Comment by knqyf263** [comment]
For example, [trivy-action](https://github.com/aquasecurity/trivy-action) is official since Aqua Security maintains it. VS Code extension is also official as it is under `aquasecurity` org. "Community integrations" are not managed by us. I'd like to explicitly distinguish between official and community-created integrations.

1. maintained by aqua or not
2. The page of CircleCI is the official approach maintained by aquasecurity. We can mention "you can also check community orbs" and link to this page in the CircleCI page.
3. It is a blog. I wanted to mean "Community integrations" are more packages or tools. "Community tools" or something like that might be better?
4. It is official. We can create a new page for it.
5. If official and unofficial/community tools are mixed in the same table, it will be confusing. Users might ask us questions regarding community tools. I want to have another table for community tools.
  - https://www.fluentd.org/plugins
  - https://www.elastic.co/guide/en/beats/libbeat/current/community-beats.html

**Comment by itaysk** [comment]
it doesn't feel like a conceptual difference between the circle CI "doc" and the semaphone CI "blog". both are just examples for how to use trivy within those tools. but these are all just thoughts, choose if/which you want to consider.

**Review by itaysk — APPROVED** [review]

**Comment by knqyf263** [comment]
>both are just examples for how to use trivy within those tools

You're right. The difference is that we will maintain the CircleCI doc and keep it up-to-date so that the example could work. It means the official example must work always. If a user finds it doesn't work, they should report it to us. 

On the other hand, we're not sure if the example in 3rd-party blogs works or not. If a user finds an issue, they should report it to the blog owner directly, not us.

If we decide to maintain the example of Semaphore CI/CD, we can copy it to our docs or add a link to the blog.

We already have a list of external blogs here. I'll consider how to structure it more.
https://aquasecurity.github.io/trivy/v0.20.2/getting-started/further/

**Comment by knqyf263** [comment]
@itaysk "Community integrations" might be confusing. I've added "Community" section for unofficial tools and blogs. I've put all external tools and blogs there. Is it relatively better? Let me know if you have any feedback.

**Comment by Morl99** [comment]
Awesome, I think this is helpful and I like the approach. Here is a text that I would choose for the trivy vulnerability explorer, feel free to use it if you like it:

"Explore trivy vulnerability reports in your browser and crrate .trivyignore files interactively. Can be integrated in your CI/CD tooling with deep links."

**Comment by itaysk** [comment]
> @itaysk "Community integrations" might be confusing. I've added "Community" section for unofficial tools and blogs. I've put all external tools and blogs there. Is it relatively better? Let me know if you have any feedback.

fine with me

**Pull request merged**
