### PR TITLE
fix(sarif): change `help` field in the sarif template.

### LINKED ISSUE #1419: Sarif results version in 0.21.1
## Description

Using the latest sarif template of trivy 0.21.1. I see some differences between the older version.
It's missing some fields in the new version of sarif

### Older sarif template

Screen Shot 2021-11-26 at 17 13 25

### New sarif template

Screen Shot 2021-11-26 at 17 15 40

### PR DESCRIPTION
**Pull request by afdesk**
Added `help` block with a detailed vulnerability description and changed a title for a specific result.

Fixes #1419

### CODE REVIEW

**Comment by afdesk** [comment]
Hi @krol3! 
Could you take a look at this sarif template? thanks!

**Comment by simar7** [comment]
> There were restored two blocks:
> 
> * a detailed description of the vulnerability,
> * a package name tag.
> 
> Fixes #1419

Do we know why they were removed in the first place?

**Comment by afdesk** [comment]
> > There were restored two blocks:
> > 
> > * a detailed description of the vulnerability,
> > * a package name tag.
> > 
> > Fixes #1419
> 
> Do we know why they were removed in the first place?

I think it was a mistake, but I'll clarify it with the author.

**Comment by afdesk** [comment]
@simar7 you're right.
I've did some changes in the sarif template.

**Review by knqyf263 — APPROVED** [review]

**Pull request merged**
