### PR TITLE
fix: ASFF template to match ASFF schema

### LINKED ISSUE #1684: Sample ASFF template doesn't include wrapping structure
## Description

Currently the asff template just provides an array of all the findings; however, the format specifies that it should be an object with an attribute called "Findings" that consists of that array of all the findings.

You can see this specification on the ["ASFF Syntax"](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-findings-format-syntax.html) and ["BatchImportFindings"](https://docs.aws.amazon.com/securityhub/1.0/APIReference/API_BatchImportFindings.html) pages.

## What did you expect to happen?

I expected the templated file to be an object consisting of an attribute called "Findings" pointing at the array of findings.

## What happened instead?

The templated file consisted of an array of findings.

## Output of `trivy -v`:

```
Version: 0.23.0
Vulnerability DB:
  Version: 2
  UpdatedAt: 2022-02-08 00:09:40.961465287 +0000 UTC
  NextUpdate: 2022-02-08 06:09:40.961464687 +0000 UTC
  DownloadedAt: 2022-02-08 04:33:24.241013 +0000 UTC
```

## Additional details (base image name, container registry info...):

Calling command:

```
AWS_REGION=us-east-1 AWS_ACCOUNT_ID=123456789012 trivy image --no-progress --format template --template "@/absolute_path_to/git_clone_of/trivy/contrib/asff.tpl" -o trivy_asff.json golang:1.12-alpine
```

### PR DESCRIPTION
**Pull request by Amndeep7**
Fix asff template to produce an array within an object instead of just an array so as to match asff schema

Signed-off-by: Amndeep Singh Mann <amann@mitre.org>

## Related issues
- Close #1684 

## Related PRs
- [ ] #594

Remove this section if you don't have related PRs.

## Checklist
- [x] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy/blob/main/CONTRIBUTING.md) to this repository.
- [x] I've followed the [conventions](https://github.com/aquasecurity/trivy/blob/main/CONTRIBUTING.md#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by afdesk** [comment]
these changes look good for me. 

but I'd like to figure out it was a mistake or the ASFF schema was changed.
and for the second option, should we support backward compatibility? 

I took a look at the documentation and couldn't find version changes:
> In the current release, the AWS Security Finding Format schema version is 2018-10-08.

so it looks like a small mistake...

@Amndeep7 is it right? thanks again!

**Review by afdesk — APPROVED** [review]

**Comment by afdesk** [comment]
@Amndeep7 thanks, you're right!
I'd approve this PR.

@knqyf263 what do you think?

**Comment by Amndeep7** [comment]
@afdesk @knqyf263 Sorry for the delay, still waiting for legal to do their thing w/r to the CLA.

**Comment by Amndeep7** [comment]
@afdesk @knqyf263 sorry for the delay, but the CLA has now been signed.

**Comment by oliviergaumond** [comment]
@afdesk @knqyf263 @Amndeep7 are you uploading using the CLI or the REST API?

Using the CLI and the instructions provided on the following page it doesn't work for me with the new template: https://aquasecurity.github.io/trivy/v0.17.0/integrations/aws-security-hub/

It seems the CLI expects a simple array, as the API expects the array to be wrapped in a Findings object
API ref: https://docs.aws.amazon.com/securityhub/1.0/APIReference/API_BatchImportFindings.html
CLI ref: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/securityhub/batch-import-findings.html

**Comment by afdesk** [comment]
@oliviergaumond thanks for your report. It;s interesting.
could you create a new issue for this problem?

**Pull request merged**
