### PR TITLE
chore(docs): update comparison table

### PR DESCRIPTION
**Pull request by knqyf263**
# Changes
- Convert "Good" to "Not bad" (we converted △ to "Good" for clarification, but I originally meant "not so good, not so bad".)
- Remove MicroScanner
- Convert "Not present" to "Not good" in DockerHub

# Issue
https://github.com/aquasecurity/trivy/pull/587#issuecomment-684447331

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]

**Comment by AkihiroSuda** [comment]
LGTM

Another way might be using star symbols:
* ◎ → ⭐ ⭐ ⭐ ⭐ 
* ○ → ⭐ ⭐ ⭐ 
* △ → ⭐ ⭐ 
* × → ⭐

**Comment by knqyf263** [comment]
It sounds nice. What do you think, @lizrice?

**Comment by lizrice** [comment]
Yes, there are definitely some issues with the wording currently. "Good" means better than "OK", but I'm not sure that's what is intended in this table? And "not good" and "not bad" are very ambiguous terms (it's unclear whether they are better or worse than "OK"!) 

I think that for the first two columns, OS packages and App dependencies, it's a yes/no question of whether they are supported or not? In which case how about 
- supported →✅ 
- not supported → ×

And then for the other three columns, I'd suggest 
- ◎ (best) → ⭐ ⭐ ⭐ 
- ○ → ⭐ ⭐ 
- △ → ⭐ 
- × (not supported) → ×

**Comment by knqyf263** [comment]
@lizrice Thanks. I've updated.

**Review by lizrice — APPROVED** [review]
lgtm

**Pull request merged**
